[1단계 - 나만의 유튜브 강의실] 병민(윤병인) 미션 제출합니다.
woowacourse/youtube-classroom pull request #111
Opened 2022-03-11 08:59 UTC by airman5573

[나만의 유튜브 강의실 데모 페이지](https://airman5573.github.io/javascript-youtube-classroom/)

안녕하십니까 리뷰어님! 이번 리뷰 잘 부탁드립니다 :D

2022-03-12 04:30 UTC, roy-jung commented
API 횟수제한이 초과되어 있네요. 데모페이지 테스트는 미뤄두고 코드만 먼저 보도록 하겠습니다.

2022-03-12 05:26 UTC, roy-jung approved these changes
병민님 안녕하세요, 리뷰어 로이입니다.
필요한 코드만 간결하게 작성하셔서 읽기에 좋았습니다.
코멘트 남겼고, 추가로 몇가지 피드백 드릴게요.

- 화면 레이아웃은 한 줄에 4개씩이니 한 번에 로드하는 컨텐츠 개수도 4의 배수로 맞추면 좋겠어요.
- 역할이 모호한 변수나 여러가지 역할을 수행하는 함수 등은 주의가 필요해요.
- 다음 스텝 때는 intersectionObserver를 활용해보시면 어떨까 합니다.

2022-03-12 05:26 UTC, roy-jung commented on .cz-config.js
> +};
나중에 참고하시라는 차원에서 링크 투척합니다) https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github

2022-03-12 05:26 UTC, roy-jung commented on src/js/__test__/searchModal.test.js
> +    expect(videos).toHaveLength(MAX_RENDER_VIDEOS_COUNT);
이 테스트는 이 자체로는 별 의미가 없는 것 같은데, 15번줄의 테스트와 병합하는게 어떨까요?

2022-03-12 05:26 UTC, roy-jung commented on src/js/app.js
> +    this.addEvent();
제 리뷰 단골메뉴입니다만, 이 메소드들을 분리하는 실익이 있나요? 기능별로 분리한 취지는 이해하지만, 실제로는 '초기화' 프로세스 중 일부에 불과하고 달리 따로 호출될 일이 없는데 말이에요. 불필요한 prototype 메모리만 차지하는 것이 아닐까요? 가독성을 위해 희생할 가치가 있다고 보시나요?

2022-03-12 05:26 UTC, roy-jung commented on src/js/app.js
> +    $('.dimmer').addEventListener('click', this.closeModal.bind(this));
`bind(this)` 대신 handler로 등록할 메소드들을 class field (arrow function)으로 전환하시는걸 추천합니다.

2022-03-12 05:26 UTC, roy-jung commented on src/js/app.js
> +new App();
EOF 처리가 필요합니다.
prettier를 사용하신걸로 보이는데 왜 이럴까요...

2022-03-12 05:26 UTC, roy-jung commented on src/js/searchModal.js
> +      .join('\n'); // new line해주지 않으면 insertAdjacentHTML을 사용할때 element가 5개만 생성된다.
왜 그런가요??

2022-03-12 05:26 UTC, roy-jung commented on src/js/searchModal.js
> +      $el.addEventListener('click', this.handleClickSaveButton.bind(this));
아이템 생성시마다 매번 listener를 등록해주는 것보다는,
최초 한 번 상위 element에 등록해두고 event delegation을 활용하는 편이 훨씬 좋습니다.

2022-03-12 05:26 UTC, roy-jung commented on src/js/searchModal.js
> +      .join('');
여기서는 new line 해주지 않아도 element가 5개만 생성되지 않는건가요? 그 이유는 뭘까요?

2022-03-12 05:26 UTC, roy-jung commented on src/js/searchModal.js
> +    this.removeSkeleton();
로딩완료시 loading중에 보여주는 임시 element들을 전부 삭제했다가 다음번 loading시 다시 삽입하는 방식 대신에
처음부터 loading중에 보여줄 요소를 맨 뒤에 만들어두고, show/hide만 하는 방식이 성능상 더 좋을 것 같아요.

2022-03-12 05:26 UTC, roy-jung commented on src/js/searchModal.js
> +    }
api 초과로 테스트해보진 못했지만, 코드상으로 봤을 때 다른 크루들과 마찬가지의 문제가 있을걸로 추측됩니다.

- 사용자 성향에 따라 순식간에 요청이 엄청 많아질 수 있습니다. 한 번 요청 후 응답이 오기 전, 즉 '로딩중'일때는 추가로 요청을 하지 않도록 하는 처리가 필요해요.
- 전체 리스트가 로딩 완료되고 난 뒤에 다시 스크롤을 내리면, 첫 페이지에 대해 다시 요청(pageToken 없이 요청)을 하게 될 것으로 보입니다. 특정 검색어에 대한 전체 페이지 개수는 정해져 있음에도, 무한히 같은 데이터가 반복해서 로드되는 거죠. 테스트 해보시고 실제로 그렇다면 이는 서비스로서는 매우 심각한 문제이니 반드시 해결해 주셔야 합니다!

2022-03-12 05:26 UTC, roy-jung commented on src/js/searchModal.js
> +  }
테스트해보지 못해서 확신할 순 없지만, 코드상으로 보기엔 초기 로딩시에 localStorage에 저장된 값과 비교하는 과정이 빠져있어서, 

1. 같은 검색어로 다시 검색하면,
2. 앞서 말씀드린 '무한! 로딩'으로 인해 스크롤을 내리면,

이미 저장된 비디오를 중복하여 저장할 수 있을것으로 추측되네요.

2022-03-12 05:26 UTC, roy-jung commented on src/js/utils/dom.js
> +};
https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren

2022-03-12 05:26 UTC, roy-jung commented on src/js/videoItem.js
> +  }
별도의 함수로 빼는게 더 나을 것 같아요.

2022-03-12 05:26 UTC, roy-jung commented on src/js/app.js
> +    const $modalContainer = $('.modal-container');
$modalContainer는 몇군데서 중복 호출되니 class의 멤버로 미리 지정해두는 편이 어떨까요?

2022-03-12 05:26 UTC, roy-jung commented on src/js/searchModal.js
> +  }
saveVideo의 역할이 너무 많습니다.
validation 체크는 별도로 분리해두는게 좋을 것 같네요.

2022-03-12 12:01 UTC, roy-jung requested changes
제가 request change를 선택한 줄 알았는데 approve로 잘못 골랐나봐요 ^^;

2022-03-12 12:05 UTC, airman5573 commented
> 제가 request change를 선택한 줄 알았는데 approve로 잘못 골랐나봐요 ^^;

그렇군요, 그러면 혹시 제가 뭔가 해야하는건가요?

2022-03-12 12:10 UTC, roy-jung commented
> 제가 request change를 선택한 줄 알았는데 approve로 잘못 골랐나봐요 ^^;
> 그렇군요, 그러면 혹시 제가 뭔가 해야하는건가요?

리뷰 진행방식에 대해서는 이전 미션들에서 많이 경험해보시지 않았나요? 혹시 그간 리뷰 진행이 제대로 안되었나요?

코멘트 확인해보시고 수정하고 싶은 부분이 있다면 수정하신 다음 다시 리뷰요청 해주시면 됩니다.
코멘트에 대해 저에게 의견 남겨주셔도 좋고요.
수정할 것이나 코멘트할 내용이 없다면 없다고 말씀해주세요 :)

2022-03-12 12:22 UTC, airman5573 commented
아 저는 뭔가 잘못 골랐다고 하셔서 제가 추가적으로 뭔가를 해야하나 싶어서 질문 드렸습니다. 제가 용어를 잘 몰라서요.
리뷰 주신 부분들에 대해서는 잘 수정해서 다시 요청 드리겠습니다. 감사합니다 :D

2022-03-13 04:17 UTC, roy-jung commented
> 아 그리고 ㅋㅋ,, 저는 콤피가 아니라 병민입니다!
에고 죄송합니다 ㅠ

2022-03-13 09:25 UTC, airman5573 commented on .cz-config.js
> +};
감사합니다 :D

2022-03-13 09:45 UTC, airman5573 commented on src/js/__test__/searchModal.test.js
> +    expect(videos).toHaveLength(MAX_RENDER_VIDEOS_COUNT);
네 동감입니다. 첫번째 테스트 케이스는 테스트로서의 효용성은 없어보이고, 두번째 테스트 코드 같은경우에는 Youtube Data API정책이 바뀌지 않았는데 실수로 checkSearchResult함수나 VideoItem클래스를 바꾸었을때 이를 알려주는 용도로는 필요할듯 싶습니다.
병합 보다는, 그냥 첫번째 케이스만 삭제하는건 어떻게 생각 하시나요? 첫번째 테스트 케이스에서는 그냥 10개로 잘라서 그 길이가 10인지 테스트 하고 있기 때문에, 실상 a = 1으로 하고 a가 1인지 테스트하는것과 비슷하다고 느껴집니다.

2022-03-13 10:21 UTC, airman5573 commented on src/js/app.js
> +    this.addEvent();
네, 짚어주신 부분에 대해서 다시 깊이 고민해보았습니다. 아래와 같은 기준이 결정에 영향을 끼칠것 같습니다.

1. 함수 코드의 길이
render함수 안에서 addEvent함수 안에 있는 일을 해도, 아래와 같이 리팩토링 하면 함수 길이가 별로 늘어나지 않습니다.
```
searchResultTemplate() {
  return `
    <section class="search-result">
      <ul class="video-list">
      </ul>
      <div class="no-result">
        <img src="${NotFoundImage}" alt="no result image" class="no-result__image">
        <p class="no-result__description">
          검색 결과가 없습니다<br />
          다른 키워드로 검색해보세요
        </p>
      </div>
    </section>`;
}

render() {
  $('.search-modal').insertAdjacentHTML('beforeend', this.searchResultTemplate());
  $('#search-modal-button', this.$nav).addEventListener('click', this.openModal);
  $('.dimmer').addEventListener('click', this.closeModal.bind(this));
}
```

2. 역할
화면에 View를 그리는것과, 내부 요소에 이벤트를 거는것은 다른 역할이라고 생각합니다. 그리고 항상 같이 세트로 다니리라는 보장도 하기는 어렵지 않나 싶습니다. 왜냐하면, 화면에 그리고 -> 어떤 일을 한다음에 그 일이 잘 되었을때 -> 이벤트 리스너를 걸어서 Interactive하게 만든다. 이런 프로세스가 있을 수도 있기 때문입니다.  혹은 이런 경우도 생각이 납니다.  
Event Delegation패턴을 사용하고, render함수가 자주 호출되는 경우에는 render함수에 (Event Delegation을 위한) 이벤트 리스너를 계속 거는것은 버그를 발생시킬 수 있다고 생각합니다(핸들러의 중복 호출).  
다만, 지금의 경우에는 위 두가지 항목이 해당되지 않는다고 생각합니다.

3. 가독성
1, 2번과 연결되는 부분인데, 엄연히 다른 역할을 가지고 있고 코드길이가 늘어나면 가독성도 떨어질것이라 생각합니다. 하지만, 지금의 경우에는 가독성에 영향을 주지 않아 보입니다.

그래서 지금의 경우에는 리뷰어님이 말씀하신 대로 둘을 합치는게 좋아보입니다.  
다만, 위에 말씀드린것처럼 분리하는 경우가 더 좋을때도 있을것 같은데, 이에 대한 리뷰어님의 생각이 궁금합니다.

추가적으로, 2번에 말씀드린 render함수가 자주 호출되는 경우는, Component형식으로 View를 만들어서, 리액트 처럼 state가 바뀔때마다 다시 그려주는(replace)방식을 의미한것입니다.

2022-03-13 10:24 UTC, airman5573 commented on src/js/app.js
> +    $('.dimmer').addEventListener('click', this.closeModal.bind(this));
감사합니다 :D 
혹시 해당 방식을 추천해주시는 이유가 있는지 궁금합니다.

2022-03-13 10:25 UTC, airman5573 commented on src/js/app.js
> +new App();
앗, 수정하겠습니다, 짚어주셔서 감사합니다 :D

2022-03-13 11:07 UTC, roy-jung commented on src/js/__test__/searchModal.test.js
> +    expect(videos).toHaveLength(MAX_RENDER_VIDEOS_COUNT);
동의합니다.

2022-03-13 12:51 UTC, roy-jung commented on src/js/app.js
> +    this.addEvent();
1. 함수길이가 늘어나면 문제가 있나요? 요구사항에 함수길이에 대한 제한이 있었나요?
2. '역할이 다르다'는 건 해석하기 나름인데, '화면에 그린다'는 의미의 render와, 화면에서 일어나는 사용자의 행동을 감시하여 명령을 수행한다는 의미의 event listener 둘을 합쳐서 View로 해석하는 것이 일반적입니다. render와 event listener는 상호 결합도가 높기 때문입니다. 
+ 말씀하신 render시마다 event listener를 등록하는 것은 당연히 해서는 안되는 일이죠. 그런 의미에서 분리한 취지는 이해한다고 말씀드린 거였고, 현재의 코드만을 바탕으로 의견을 드린 겁니다.
3. 반드시 코드 길이와 가독성이 연관되지는 않는다고 봅니다. 필요에 따라 적절한 구획을 나누어 줄바꿈 처리만 해주어도 가독성은 월등히 높아지게 되죠. 리액트를 예로 들면, 함수형 컴포넌트는 실제로는 '하나의 함수' 입니다. return구문의 위쪽에 매우 많은 로직이 들어가게 되는데, 단지 이것만 가지고 가독성이 떨어진다고 하지는 않습니다.
4. render를 여러번 호출할 필요가 있는 경우에는, render함수와 무관하게 delegation 처리한 event listener를 한 번만 등록해두고, 이후에는 render만 호출하면 되겠죠. 그런 경우에는 위 코드 중에서 `this.render()`는 남겨두는 가치가 있을 것이고, 그런 경우에도 여전히 `this.addEvent()`는 constructor로 옮기는 것이 맞다고 봅니다.
+ 만약 addEvent 메소드를 여러번 호출할 필요가 있는 경우라면, 코드를 리팩토링할 좋은 기회로 삼아야 하겠습니다.

2022-03-13 12:53 UTC, roy-jung commented on src/js/app.js
> +    $('.dimmer').addEventListener('click', this.closeModal.bind(this));
메소드 선언 방식에 의하면 prototype에 원본메소드가 남아있는 채로, 실제로 호출되는건 새로 만들어진 bound 메소드입니다. 반면 class field를 이용하면 prototype에는 남아있지 않고, 인스턴스 자신이 사용할 함수만 들고 있게 됩니다.

2022-03-13 12:54 UTC, airman5573 commented on src/js/searchModal.js
> +      .join('\n'); // new line해주지 않으면 insertAdjacentHTML을 사용할때 element가 5개만 생성된다.
사실 처음에는 크롬의 파서 오류인줄 알았는데, 알고보니 아니었습니다.

## arr.forEach
```
var arr = [1, 2, 3, 4, 5];

arr.forEach((num) => {
  console.log('num : ', num);
  arr.pop();
});
```
위 코드는 1, 2, 3만 출력하고 끝납니다. 제 예상으로는 아마 이런식으로 작동하지 않을까 싶습니다.  
1. index 0번째 요소를 callback함수에 넣는다 -> num : 1
2. arr.pop() -> arr = [1, 2, 3, 4];
3. index = index + 1  //  index < arr.length 가 참이면 계속 진행한다
4. index 1번째 요소를 callback함수에 넣는다 -> num : 2;
5. arr.pop() -> arr = [1, 2, 3];
6. index = index + 1  //  index < arr.length 가 참이면 계속 진행한다
7. index 2번째 요소를 callback함수에 넣는다 -> num : 3;
8. app.pop() -> arr = [1, 2];
9. index = index + 1  //  index < arr.length 가 참이면 계속 진행한다. 그런데 index = 3이고, arr.length는 2이기 때문에 여기서 멈춘다.

그래서 arr는 [1, 2]가 되고, 콘솔창에는 1, 2, 3만 찍힙니다.

## insertAdjacentElement
```
$template.childNodes.forEach($el => {
  this.$videoList.insertAdjacentElement('beforeend', $el);
});
```
위의 forEach 예제처럼 arr.pop같은건 없지만, $template안에 있는 childNode(=$el)를 $videoList안에 **이동**시켰기 때문에 $template.childNodes 배열의 길이는 점점 줄어듭니다. 그래서 childNode가 10개의 반인 5개만 그려졌습니다.

## .join('\n')
재미있는 점은 '\n'을 사이사이에 넣었을때 10개가 제대로 그려졌다는 것입니다.  
.join('\n')을 하면, $template.childNodes의 모습은 다음과 같습니다.
```
[
  element,
  textNode,
  element,
  textNode,
  element,
  ....
]
```
'\n'가 textNode로 판정되어, 배열의 길이는 총 19가 됩니다.

그래서 forEach를 쓰면,  
처음에 element (index = 0) 가 이동하고 -> 배열에서 빠지고 -> index += 1 했기 때문에 textNode는 지나치고 -> 다음 element가 이동하고 ... 이런식으로 되서 정말 우연히(?) '\n'을 넣었을때 19개의 요소중 textNode만 지나치고, element만 쏙쏙 이동되서 10개가 잘 그려진것이었습니다.


정말 별일이 다 있습니다.

## 해결책
$el.cloneNode(true)를 하거나, 아니면 forEach대신에, 다른 방식으로 루프를 돌면 될것 같습니다.


리뷰어님께서 질문해주신 덕분에 재밌는 사실을 발견했습니다. 감사합니다 :D

---

[codepen](https://codepen.io/YOONBYEONGIN/pen/GRyRBeO)에 코드를 올려두었으니, 확인 가능합니다 :D

2022-03-13 12:56 UTC, airman5573 commented on src/js/searchModal.js
> +      $el.addEventListener('click', this.handleClickSaveButton.bind(this));
네, 감사합니다 :D

2022-03-13 12:59 UTC, airman5573 commented on src/js/searchModal.js
> +      .join('');
위의 내용과 같습니다 :D

2022-03-13 13:07 UTC, airman5573 commented on src/js/searchModal.js
> +    this.removeSkeleton();
동감입니다. 좋은 아이디어 감사합니다 :D

2022-03-13 13:09 UTC, roy-jung commented on src/js/searchModal.js
> +      .join('\n'); // new line해주지 않으면 insertAdjacentHTML을 사용할때 element가 5개만 생성된다.
훌륭한 분석입니다. 다만 코드에 대한 해결책은 의외로 엄청 간단할 수 있어요.
DOM을 추가/수정/삭제하는 건 비용이 많이 드는 작업입니다. 가능한 한번에 처리하는게 제일 좋아요.
그러니까 `this.$videoList.insertAdjacentElement('beforeend', $el);` 을 모든 $el마다 하는 대신에
`this.$videoList.insertAdjacentElement('beforeend', template.children);` 한 번에 처리하면 해결될 것 같네요.

2022-03-13 13:20 UTC, airman5573 commented on src/js/searchModal.js
> +    }
생각 못한 부분이네요. 꼭 고치겠습니다. 감사합니다 :D

2022-03-13 13:21 UTC, airman5573 commented on src/js/searchModal.js
> +  }
아 맞습니다. 감사합니다 :D

2022-03-13 13:22 UTC, airman5573 commented on src/js/utils/dom.js
> +};
이미 있었군요. 감사합니다 :D

2022-03-13 13:26 UTC, airman5573 commented on src/js/videoItem.js
> +  }
처음에 말씀하신 대로 하려 했는데, 함수명 짓기가 어려웠습니다.  
그래서 videoItem안에 있으면 해당 함수를 한정적으로 사용하는것이기 때문에 함수명을 general하게 지을 수 있다고 생각했습니다.  
밖으로 뺀다면 'ISO8601형식의 날짜를을 년월일로 변환한다'라는 의미를 가진 함수명을 짓고 싶은데,, 혹시 추천해주실 만한 함수명이 있을까요? 아니면 해당 함수가 밖에 있어도 함수명을 좀 general하게 지어도 될까요?

2022-03-13 13:27 UTC, airman5573 commented on src/js/app.js
> +    const $modalContainer = $('.modal-container');
동감입니다. 감사합니다 :D

2022-03-13 13:27 UTC, airman5573 commented on src/js/searchModal.js
> +  }
네, 동감입니다. 감사합니다 :D

2022-03-13 15:19 UTC, airman5573 commented on src/js/app.js
> +    this.addEvent();
1. 함수길이가 늘어나면 문제가 있나요? 요구사항에 함수길이에 대한 제한이 있었나요?

- 함수 길이가 늘어나도 사실 잘 읽히기만 한다면 문제는 없다고 생각합니다.  
함수 길이의 제한은 요구사항에 없었지만, 15줄까지만 작성해보도록 권고를 받은적이 있어서 가능하면 나누려 했습니다.

2. '역할이 다르다'는 건 해석하기 나름인데, '화면에 그린다'는 의미의 render와, 화면에서 일어나는 사용자의 행동을 감시하여 명령을 수행한다는 의미의 event listener 둘을 합쳐서 View로 해석하는 것이 일반적입니다. render와 event listener는 상호 결합도가 높기 때문입니다.
말씀하신 render시마다 event listener를 등록하는 것은 당연히 해서는 안되는 일이죠. 그런 의미에서 분리한 취지는 이해한다고 말씀드린 거였고, 현재의 코드만을 바탕으로 의견을 드린 겁니다.

- 네, 이해했습니다. 감사합니다 :D

3. 반드시 코드 길이와 가독성이 연관되지는 않는다고 봅니다. 필요에 따라 적절한 구획을 나누어 줄바꿈 처리만 해주어도 가독성은 월등히 높아지게 되죠. 리액트를 예로 들면, 함수형 컴포넌트는 실제로는 '하나의 함수' 입니다. return구문의 위쪽에 매우 많은 로직이 들어가게 되는데, 단지 이것만 가지고 가독성이 떨어진다고 하지는 않습니다.

- 네, 맞습니다.

4. render를 여러번 호출할 필요가 있는 경우에는, render함수와 무관하게 delegation 처리한 event listener를 한 번만 등록해두고, 이후에는 render만 호출하면 되겠죠. 그런 경우에는 위 코드 중에서 this.render()는 남겨두는 가치가 있을 것이고, 그런 경우에도 여전히 this.addEvent()는 constructor로 옮기는 것이 맞다고 봅니다.
만약 addEvent 메소드를 여러번 호출할 필요가 있는 경우라면, 코드를 리팩토링할 좋은 기회로 삼아야 하겠습니다.

- 아, 아마 제가 리뷰어님의 말을 잘못 이해한듯 싶습니다. this.render()와 this.addEvent()를 분리 하는 실익이 있냐는 말을 저는 this.render()함수 안에 this.addEvent()함수의 내용물을 넣어도 괜찮다는 말로 이해했습니다. 그런데 지금 답변해 주신 내용과 리뷰를 다시  읽어보니, render()와 addEvent()안에 있는 코드를 모두 초기화 단계에 그냥 적어도 괜찮다는 의미인것 같습니다.  

비교를 위해서 아래 코드를 작성해 보았습니다.

### 함수를 분리하는 경우

```
class MyView1 {
  constructor() {
    this.render();
    this.bindElements();
    this.addEvents();
  }

  templateList() {
    return `
      <li>A</li>
      <li>B</li>
      <li>C</li>
      <li>D</li>
    `;
  }

  template() {
    return `
      <button class="my-btn">BUTTON</button>
      <ul class="my-list">
        ${templateInner()}
      </ul>
    `;
  }

  render() {
    document.querySelector('.container').innerHTML = this.template();
  }

  bindElements() {
    this.$container = document.querySelector('.container');
    this.$button = this.$container.querySelector('.my-btn');
    this.$list = this.$container.querySelector('.my-list');
  }

  addEvents() {
    this.$button.addEventListener('click', this.clickHandler);
    this.$list.addEventListener('scroll', this.scrollHandler);
  }
}
```

### 초기화 단계에서 전부 처리해 주는 경우
```
class MyView2 {
  constructor() {
    this.$container = document.querySelector('.container');
    this.$container.innerHTML = this.template();
    this.$button = this.$container.querySelector('.my-btn');
    this.$list = this.$container.querySelector('.my-list');
    this.$button.addEventListener('click', this.clickHandler);
    this.$list.addEventListener('scroll', this.scrollHandler);
  }
  
  templateList() {
    return `
      <li>A</li>
      <li>B</li>
      <li>C</li>
      <li>D</li>
      ...
    `;
  }

  template() {
    return `
      <button class="my-btn">BUTTON</button>
      <ul class="my-list">
        ${templateInner()}
      </ul>
      ...
    `;
  }
}
```

이렇게 두개를 놓고 보니, 대략적으로 이 Class가 뭘 하려는 건지는 전자가 조금 더 잘 표현한것 같은데('그리고 -> 바인딩하고 -> 이벤트를 거는구나'), addEvent()와 bindElements()의 위치가 바뀌면 에러가 발생하기 때문에 좀 아슬아슬 해보입니다.  
구체적으로 뭘 하려는지는 후자가 더 잘 읽힙니다.  
말씀하신 대로 하는게 더 좋아보입니다. 알려주셔서 감사합니다 :D

2022-03-14 10:35 UTC, airman5573 commented on src/js/app.js
> +    $('.dimmer').addEventListener('click', this.closeModal.bind(this));
알려주셔서 감사합니다. 적용하겠습니다 :D

2022-03-14 10:36 UTC, airman5573 commented on src/js/searchModal.js
> +      .join('\n'); // new line해주지 않으면 insertAdjacentHTML을 사용할때 element가 5개만 생성된다.
네, 동감입니다. 수정하겠습니다 :D

2022-03-15 06:16 UTC, airman5573 commented on .cz-config.js
> +};
적용해 보았습니다 :D
[18fbc92](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/18fbc92e6140ab53294137052be8d8c328624633)
[81ecd60](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/81ecd60d08918f1b24c9fe7e9fea1187cc15d15e)

2022-03-15 06:17 UTC, airman5573 commented on src/js/__test__/searchModal.test.js
> +    expect(videos).toHaveLength(MAX_RENDER_VIDEOS_COUNT);
수정했습니다 :D
[2c4d3f9](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/2c4d3f96c00e006faebc7b932c90f20fd2027ac7)

2022-03-15 06:18 UTC, airman5573 commented on src/js/app.js
> +    this.addEvent();
수정 했습니다 :D 
[0633b20](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/0633b20aa6441ca1fea8fc2c5b9dafb4e53bde4e)
[70928d8](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/70928d8530e173591e72d2a443846c679ff57622)

2022-03-15 06:20 UTC, airman5573 commented on src/js/app.js
> +    $('.dimmer').addEventListener('click', this.closeModal.bind(this));
수정했습니다 :D 
[b29e9e9](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/b29e9e9398dc70c65d08f3019c42972fdc5427fd)

2022-03-15 06:24 UTC, airman5573 commented on src/js/searchModal.js
> +      .join('\n'); // new line해주지 않으면 insertAdjacentHTML을 사용할때 element가 5개만 생성된다.
Event Delegation 패턴을 적용하면서 같이 자연스레 수정되었습니다 :D 
[5778d07](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/5778d07644bfed8a2c506810965c5e779eac8274)

2022-03-15 06:25 UTC, airman5573 commented on src/js/searchModal.js
> +      $el.addEventListener('click', this.handleClickSaveButton.bind(this));
수정했습니다 :D 
[5778d07](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/5778d07644bfed8a2c506810965c5e779eac8274)

2022-03-15 06:25 UTC, airman5573 commented on src/js/searchModal.js
> +    this.removeSkeleton();
수정했습니다 :D 
[ca660ed](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/ca660edb931012931b3cb9c616d0f25915c7c062)

2022-03-15 06:26 UTC, roy-jung commented on src/js/videoItem.js
> +  }
`IsoToKoreanDateConverter` 어떨까요

2022-03-15 06:38 UTC, airman5573 commented on src/js/searchModal.js
> +    }
수정했습니다 :D 
- '로딩중'일때는 추가로 요청을 하지 않도록 : [4e37c05](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/4e37c05a4c39ed2c5561a859c6dc9ba022c7a75f)
- 무한히 같은 데이터가 로드되지 않도록 : [fff917c](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/fff917c758550bad67aa7bb53e0743e5eaef7bfa), [dbb5c33](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/dbb5c339472a1581d58332076fc4a6e460641609)

2022-03-15 06:38 UTC, airman5573 commented on src/js/searchModal.js
> +  }
수정했습니다 :D 
[e505d5a](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/e505d5ab04d014e8fc3da083412afb83fbbb25fc), [715ad2d](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/715ad2dd2bbf3bede18df19c84beedb7ab8c7633)

2022-03-15 06:39 UTC, airman5573 commented on src/js/utils/dom.js
> +};
수정했습니다 :D 
[2a634f4](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/2a634f44ea003d43191544956604d3449a532ddb)

2022-03-15 06:40 UTC, airman5573 commented on src/js/app.js
> +    const $modalContainer = $('.modal-container');
수정했습니다 :D  
[aa3b963](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/aa3b963aa0abfd44f519ca124613a8d371a19206)

2022-03-15 06:45 UTC, airman5573 commented on src/js/searchModal.js
> +  }
한번 try - catch문으로 작성해 보았습니다.  확인 부탁드립니다 :D 
[44c435c](https://github.com/woowacourse/javascript-youtube-classroom/pull/111/commits/44c435c907db21ec68e1974ea8c0a9323648c1db)

2022-03-15 06:47 UTC, airman5573 commented on src/js/app.js
> +    $('.dimmer').addEventListener('click', this.closeModal.bind(this));
> 병민님 안녕하세요, 리뷰어 로이입니다. 필요한 코드만 간결하게 작성하셔서 읽기에 좋았습니다. 코멘트 남겼고, 추가로 몇가지 피드백 드릴게요.
> 
> * 화면 레이아웃은 한 줄에 4개씩이니 한 번에 로드하는 컨텐츠 개수도 4의 배수로 맞추면 좋겠어요.
> * 역할이 모호한 변수나 여러가지 역할을 수행하는 함수 등은 주의가 필요해요.
> * 다음 스텝 때는 intersectionObserver를 활용해보시면 어떨까 합니다.

로드하는 컨텐츠의 개수는 요구사항에 10개로 지정되어 있어서, 수정하지 않은점 참고 바랍니다 :D

2022-03-15 09:45 UTC, roy-jung commented
데모페이지는 다시 배포되지 않은것일까요?

2022-03-15 10:49 UTC, airman5573 commented
> 나만의 유튜브 강의실 데모 페이지

재배포 되었습니다!

[데모페이지](https://airman5573.github.io/javascript-youtube-classroom/)

확인 바랍니다 :D

2022-03-15 11:02 UTC, roy-jung approved these changes
데모 돌려보니 "더 이상 불러올 동영상이 없는 경우에는 로드하지 않는다" 이 부분 제대로 반영이 안된 것 같습니다. 이 부분은 2단계에서 재점검하고 꼭 반영해 주세요. 나머지 역시 2단계때 계속 발전시켜 나가면 되니까, 이쯤에서 마무리 지을게요. 고생하셨고 2단계때 뵈어요 :)

2022-03-15 11:02 UTC, merged