[2단계 - 나만의 유튜브 강의실] 준찌(장준혁) 미션 제출합니다.
woowacourse/youtube-classroom pull request #117
Opened 2022-03-18 14:18 UTC by juunzzi

2022-03-19 10:08 UTC, lsw1164 commented on cypress/integration/manageVideo.test.js
> +describe('사용자는 검색된 비디오를 관리할 수 있다.', () => {
테스트가 명확하고 좋네요 :) 
성공 케이스에 대한 검증은 충분한 거 같습니다! 
예외 상황에 대한 테스트도 몇가지 고민해보면 좋겠습니다!

2022-03-19 12:04 UTC, lsw1164 requested changes
> 1. 캐시 스토어를 구현하는 다른 아이디어를 여쭙고 싶습니다.
 
캐시 관리에 setTimeout을 쓰는 방식이 적절한가? 의문이라 질문해주셨다고 생각하는데요.

현 로직상 set이 일어난 시점에서 1분 뒤에 무조건 값을 지우는 방식입니다.
만약 최초 set을 하고 59초 뒤에 두번째 set이 일어난다면?
두번째 set은 1초 뒤에 바로 지워질 겁니다.
즉, set 지우는 로직이 다음 set 로직에 영향을 준다고 할 수 있겠습니다.

클로저를 적절히 활용해서 clearTimeout을 써볼 수 있겠지만, 이 역시 브라우져가 아예 종료된 시점에서는 동작하지 않을겁니다.

브라우저, 권한 및 로그인 서비스의 토큰 관리 방법 등 다른 프로그램이나 서비스에서는 어떻게 캐시를 관리하고 있을까? 리처치해보시면 적절한 아이디어를 얻을 수 있을겁니다 :)


> 2. 한 개의 컴포넌트 클래스가 무거워지는 것 VS 추상화된 클래스를 만들어 이를 상속받는 클래스들을 추가하는 것

무조건 추상화하는 게 정답일까? 라는 의문이 듭니다.  
추상화는 확장성을 얻는 대신 설계 구조를 복잡하게 만들기에 항상 고민됩니다.  
심지어 섣부른 추상화는 확장성도 놓치고 설계 구조도 복잡하게 만드는 최악의 결과를 초래하기도 합니다. 


### 개인적인 추상화 시점

1. 지금까지 실제로 변경이 있었고 앞으로도 변경이 예상되는 부분인가?   
(지금처럼 연습 과정에서는 변경 히스토리가 당연히 없으니 앞으로 변경이 예상되는 부분의 추상화를 많이 경험해보는 게 좋다고 생각합니다)   
모든 로직을 전부 확장성 있게 짜면 오래걸리고 구조가 복잡해집니다. 딱히 바뀔 일이 없는 로직을 억지로 확장성 있게 짤 필요는 없습니다. 가능하다면 단순한 게 베스트죠. 추상화가 들어가는 순간 복잡도가 올라갑니다. 항상 트레이드 오프를 고민해야합니다.
 
2. 두 객체가 동일한 "역할"을 수행하는지 충분히 고민해보고 추상화한다.  
동일한 역할은 대체 가능을 의미합니다. 개념적으로 대체될 수 없는 두 객체를 추상화 하는 건 추상화를 위한 추상화가 될 수 있습니다.

적어주신 글을 보면 이미 준찌님은 장단점을 충분히 인지하고 계신거 같습니다. 
설계는 정답이 없으니 장단점 파악하신 것만으로도 이번 미션에서 많은 것을 얻어가셨을 거라 생각되네요 :)

2022-03-19 12:04 UTC, lsw1164 commented on cypress/support/commands.js
> +Cypress.Commands.add('showModal', () => {
Command 활용 좋네요 👍

2022-03-19 12:04 UTC, lsw1164 commented on src/js/__test__/webStore.test.js
> +describe('webStore 모듈 테스트', () => {
webStore 모듈이 localStorage가 아니라 다른 Stroeage를 사용하게되면 테스트 코드도 같이 바꿔줘야될까요?

2022-03-19 12:04 UTC, lsw1164 commented on src/js/business/index.js
> +      const savedVideoList = await Promise.all(
멀티 비동기 요청을 적절히 처리하셨군요 :)

2022-03-19 12:04 UTC, lsw1164 commented on src/js/modules/WebStore.js
> +    return JSON.parse(localStorage.getItem(key) ?? '[]');
JSON.parse 과정에서 Exception이 발생할 수 있겠군요.

2022-03-19 12:04 UTC, lsw1164 commented on src/js/components/SearchResultComponent.js
> +    /** 검색 결과가 없다면 */
코드에 의도가 충분히 드러나는 거 같아서 주석이 없어도 될거같군요 :)

2022-03-19 12:04 UTC, lsw1164 commented on src/js/components/VideoComponent/SavedVideoComponent.js
> +    this.#mount();
상위 컴포넌트 생성자에서 mount가 호출될텐데 하위 컴포넌트에서 mount를 또 호출해도 괜찮을까요?

2022-03-19 12:04 UTC, lsw1164 commented on src/js/components/VideoComponent/SavedVideoComponent.js
> +    this.#mount();
아 beforeend에 추가하는 방식이라 이렇게 해주셨군요.   
private이라 mount는 override가 안된거고요.

2022-03-20 04:40 UTC, juunzzi commented on cypress/support/commands.js
> +Cypress.Commands.add('showModal', () => {
![image](https://user-images.githubusercontent.com/78349600/159148508-8faeabf0-ab65-4a18-910c-bee1f91f2268.png)

2022-03-20 05:38 UTC, juunzzi commented on src/js/components/VideoComponent/SavedVideoComponent.js
> +    this.#mount();
이 부분이 '섣부른 추상화'로 생긴 문제일 수 있을 것 같네요.... ㅋㅋㅋ...

오해를 불러 일으키는 코드.. 죄송합니다..

2022-03-20 05:40 UTC, juunzzi commented on src/js/business/index.js
> +      const savedVideoList = await Promise.all(
![image](https://user-images.githubusercontent.com/78349600/159149778-7cf2e723-df05-4ed7-b711-c69cb3e7387f.png)

2022-03-20 06:34 UTC, juunzzi commented on src/js/__test__/webStore.test.js
> +describe('webStore 모듈 테스트', () => {
모듈의 이름이 webStore인데, localStorage 만을 사용할 것이다 가정하고 코드를 작성한것 같네요.... 혼란이 생길만 한 것 같습니다.

모듈의 이름을 localStorageStore 혹은 localStorageModule로 네이밍을 변경하면 리뷰어님이 생각하시는 문제가 해결될 것 같으실까요?

2022-03-20 06:45 UTC, juunzzi commented on src/js/modules/WebStore.js
> +    return JSON.parse(localStorage.getItem(key) ?? '[]');
처리 해보았습니다!!

2022-03-20 07:51 UTC, juunzzi commented on src/js/components/SearchResultComponent.js
> +    /** 검색 결과가 없다면 */
오 그렇군요 !!!

제가 보기엔 명확하지 않을 수 있겠다 싶어 주석을 추가하였는데, 그게 아니였나봐요 !! 제거하였습니다.

2022-03-20 08:20 UTC, juunzzi commented on cypress/integration/manageVideo.test.js
> +describe('사용자는 검색된 비디오를 관리할 수 있다.', () => {
예외 사항을 점검하는 테스트를 분리해보았고, 한 가지 (검색결과가 없는 경우에 대해) 테스트를 추가하였습니다!!!!

2022-03-20 16:34 UTC, lsw1164 commented on src/js/__test__/webStore.test.js
> +describe('webStore 모듈 테스트', () => {
말씀하신대로 localStorage를 쓰는 모듈이라고 명시해서 해결할 수도 있겠군요

2022-03-21 15:35 UTC, lsw1164 approved these changes
준찌님, 미션 수고 많으셨어요! Approve 하겠습니다!

2022-03-21 15:35 UTC, merged