[2단계 - 나만의 유튜브 강의실] 태태(김태윤) 미션 제출합니다.
woowacourse/youtube-classroom pull request #118
Opened 2022-03-18 14:56 UTC by nan-noo

지금 api를 다 써서 내일쯤 실행 가능할 것 같습니다ㅠㅠ

### 데모페이지
[나만의유튜브](https://nan-noo.github.io/javascript-youtube-classroom/)

### 구조 설계도
![youtube-classroom-step2](https://user-images.githubusercontent.com/54002105/159019073-c84f8707-c0e6-4218-924d-34a1058ba409.png)

### step1과 비교해서 바뀐 것
* localStorage에 저장하는 데이터: videoId -> videoId, title, channelTitle, publishTime, isChecked
* 스크롤에 throttle 적용
* 스켈레톤 렌더링하는 방식: 검색할 때마다 매번 새 element 생성 -> 클래스로 display만 변경
* 모달창의 바깥쪽 클릭시 창을 끌 수 있음
* jest 테스트 수정, cypress E2E 테스트 추가
* step2 기능 구현
* 등등 

### 생각
* 다른 크루분과 이야기하면서 나온 궁금증입니다. 지금은 저장한 비디오의 필요한 정보를 모두 localStorage에 담고 있는데, 일정 주기마다 갱신하는 일 없이 계속 가지고 있으면, 오래된 데이터를 사용자에게 보여준다는 단점이 있습니다. 그렇다고 매번 유튜브 api 통신으로 저장한 비디오 데이터를 받아오기엔, 다뤄야 할 네트워크 오류가 많다는 단점이 있습니다. 어떤 방법이 더 나을까 얘기하다가 결론은 백엔드에서 어느정도 처리해주는 게 필요하다..(백엔드에서 일정 주기마다 DB 갱신 하는 등의 방법)였습니다 :D 그런데 아직은 프론트만 생각해야 하니까 프론트에서 백엔드처럼 주기적으로 갱신할 수 있는 어떤 방법이 있을까요? 제가 생각한 방법은 구현하진 않았지만, timestamp를 같이 저장해서 데이터를 가져올 때 일정 기간이 지난 데이터는 처리후 삭제하는 방법입니다.
* 중복되는 로직은 꽤 많이 함수나 메서드로 분리하긴 했는데, 잘 분리한건지 좀 지저분하진 않은지 걱정이 듭니다ㅠㅠ 아직도 리팩토링 많이 어렵네요. 

---
사소한 것이라도 피드백 많이 남겨주세요..!! 감사합니다.

2022-03-19 17:17 UTC, lsw1164 requested changes
안녕하세요 태태 코드 잘봤습니다. 코멘트 남겼으니 참고부탁드려요~

### 적어주신 생각에 대한 답변
- 캐시 데이터 관리를 고민하고 계시는군요. 생각하신 방법도 좋은 거 같습니다 :) 혼자 고민해보는 것도 필요하지만 다른 프로그램과 서비스에서는 캐시데이터를 어떻게 관리하고 있을지 리서치해보는 것도 도움이 될 것입니다.

- 리팩토링은 꾸준히 경험해보시면서 쌓아가는 수밖에 없다고 생각합니다.  
(주니어 때 리팩토링 관련 도서 한 권은 필수로 읽어야 된다고 생각합니다)

2022-03-19 17:17 UTC, lsw1164 commented on cypress/integration/youtubeClassroom.spec.js
> +  const baseUrl = 'http://localhost:9000/';
cypress config로 baseUrl 관리할 수 있습니다 :)

https://docs.cypress.io/guides/references/configuration#cypress-json

2022-03-19 17:17 UTC, lsw1164 commented on cypress/integration/youtubeClassroom.spec.js
> +Cypress.Commands.add('normalSearchKeyword', (keyword, nextActionCallback) => {
Command 활용 좋습니다 👍

2022-03-19 17:17 UTC, lsw1164 commented on src/js/utils/handleElement.js
> +  element.insertAdjacentHTML(position, insertHtmlString);
표준 API들을 래핑하셨는데요. 래핑하신 의도가 있을까요? 
insertHtmlToElement 같은 경우 래핑 전/후로 차이가 없어보입니다.

2022-03-19 17:17 UTC, lsw1164 commented on src/js/renderVideo.js
>    constructor() {
생성자 안에 너무 많은 로직들이 들어가 있어서 어떤 일들이 일어나는지 파악하기 어렵습니다. 
이럴 때 고려해보면 좋은 건  '함수로 추출하기'입니다.
관련 있는 로직들을 함수로 추출해서 적절한 네이밍을 고민해보면 좋겠습니다. 
그럼 생성자 내부에서 어떤 일들이 일어나는지 보다 쉽게 파악할 수 있겠습니다.

2022-03-19 17:17 UTC, lsw1164 commented on src/js/saveVideo.js
>      return JSON.parse(localStorage.getItem(VIDEO_ID_LIST_KEY)) || [];
JSON.parse는 Exception이 발생할 수 있습니다. 예외 상황은 어떻게 핸들하는 게 좋을까요?

2022-03-19 17:17 UTC, lsw1164 commented on src/js/searchVideo.js
> +      const response = await fetch(url);
web api는 여러 컴포넌트에서 필요할 수 있으니 별도 파일을 만들어서 관리하면 어떨까요?

2022-03-19 17:17 UTC, lsw1164 commented on src/js/renderVideo.js
>  class RenderVideo {
RenderVideo에서 너무 많은 책임들을 갖고 있습니다. \
적절한 역할을 만들어서 책임들을 분리해보면 어떨까요?
(물론 지금처럼 작은 규모에서는 적절한 설계일 수 있습니다 👍 
하지만, 연습 차원에서 더 작은 단위로 쪼개보면 좋은 경험이 되겠습니다)

2022-03-21 02:47 UTC, nan-noo commented on src/js/renderVideo.js
>  class RenderVideo {
말씀하신 것처럼 아직 분리가 필요할 정도는 아니다라고 느껴서 분리하지 않았습니다. 그래도 다음 미션에선 분리가 필요해 보이니까 연습해보겠습니다ㅎㅎ
제가 생각하기에 모달 부분과 메인 화면 부분을 분리하면 좋을 것 같은데 어떻게 생각하시나요?

2022-03-21 02:51 UTC, nan-noo commented on src/js/utils/handleElement.js
> +  element.insertAdjacentHTML(position, insertHtmlString);
일단 반복해서 자주 쓰여서 분리해봤는데, 이런 기존에 있는 api를 분리하는 기준이 궁금합니다. 짧게 줄여쓰고 싶거나 기능을 살짝 커스텀하려 할때만 분리하면 될까요??
addEvent 같은 경우도 addEventListener를 줄여쓰는 것 말고는 차이가 없어보여서 질문합니다!ㅎㅎ

2022-03-21 02:53 UTC, nan-noo commented on src/js/searchVideo.js
> +      const response = await fetch(url);
아직은 비디오 가져올때만 사용해서 분리하지 않았는데, api 요청이 많이 필요해지면 분리해서 관리하도록 하겠습니다! 팁 감사합니다:D

2022-03-21 04:53 UTC, nan-noo commented on src/js/saveVideo.js
>      return JSON.parse(localStorage.getItem(VIDEO_ID_LIST_KEY)) || [];
아 이거 처리를 깜박했네요ㅠㅠ
일단은 try catch로 에러가 발생하면 우선 빈 배열을 return 하도록 했습니다. 제대로 된 json 데이터가 저장되지 않았다는 것은 지금 앱에서 json.stringify로 정상적으로 저장한 데이터가 아닌 다른 조작에 의해서 저장된 데이터라고 판단했기 때문입니다. 
워낙 execption 경우가 많아서 케이스마다 처리해주긴 번거로울 것 같습니다. 더 좋은 방법이 있을까요?

2022-03-21 06:22 UTC, nan-noo commented on src/js/renderVideo.js
>    constructor() {
일단 renderVideo를 분리하고 나니, 생성자 함수 내용이 줄긴 했습니다! 제가 저번에 초기화하는 내용은 constructor에서 하는게 좋고, 내용이 길어져도 개행이나 주석 정도로 충분하다는 피드백을 받았습니다. 처음 생성할 때만 사용하는 메서드는 굳이 만들 필요가 없다는 내용이었습니다. 그래서 일단은 주석을 달아봤는데, 어떻게 생각하시나요?

2022-03-21 16:30 UTC, lsw1164 commented on src/js/utils/handleElement.js
> +  element.insertAdjacentHTML(position, insertHtmlString);
> 일단 반복해서 자주 쓰여서 분리해봤는데, 이런 기존에 있는 api를 분리하는 기준이 궁금합니다. 짧게 줄여쓰고 싶거나 기능을 살짝 커스텀하려 할때만 분리하면 될까요?? addEvent 같은 경우도 addEventListener를 줄여쓰는 것 말고는 차이가 없어보여서 질문합니다!ㅎㅎ

**기준이 없습니다**. 다만, 만약 래핑하려고 할 때, 특별히 장점이 한 가지는 있어야 됩니다.

반복되는 패턴의 포맷을 만들고 강제해야 될 때 래핑하면 좋겠네요.

$을 래핑한 것은... jquery 라이브러리의 $함수를 구현한 거로 봤습니다.
jquery 같은 경우 워낙 알려져 있는 라이브러리라 의미를 알고 있는 상태에서 글자수까지 줄어드는 효과가 있습니다. 
이렇게 가독성이 올라간다면 래핑해도 괜찮다 생각합니다. (jquery를 모르는 상태에선 그냥 주관적인 의견이네요. 🤔)

개인적으로 addEvent, insertHtmlToElement 같은 경우는 유효한 차이를 만들었다고 보기 어려웠습니다.

2022-03-21 16:43 UTC, lsw1164 commented on src/js/renderVideo.js
>    constructor() {
constructor 내부에서 여러 가지 일을 하면 할수록 함수로 추출하는 게 좋다고 생각합니다 :)

constructor 내부 로직을 메서드로 추출할 때 단점 
- 굳이 추출해야되나? 라는 의문

constructor 내부 로직을 메서드로 추출하지 않고 여러가지 일을 한 번에 할 때 단점
- 의도를 파악하려면 로직을 모두 확인해야 됨 -> 주석으로 커버 가능
- 주석 관리 (주석의 관리 비용은 코드급이며, 기계가 걸러주지 않는 만큼 잘못된 내용이 남을 여지, 더 오히려 관리가 어려움) 
- 연관성이 없는 많은 로직들이 모두 같은 스코프를 공유함

2022-03-21 16:45 UTC, lsw1164 commented on src/js/saveVideo.js
>      return JSON.parse(localStorage.getItem(VIDEO_ID_LIST_KEY)) || [];
에러 핸들 주체를 어디로 잡냐 문제라서 지금 처리해주신 방법도 괜찮다 생각합니다 👍

2022-03-21 16:46 UTC, lsw1164 commented on src/js/renderVideo.js
>  class RenderVideo {
넵 그렇게 분리해봐도 좋겠네요 👍 
다음 미션에서는 분리하는 것도 연습해보시죠 :)

2022-03-22 13:24 UTC, lsw1164 approved these changes
태태님, 피드백 반영하느라 수고 많으셨습니다! 
더 개선하고 싶은 부분은 잘 기억하셨다가 다음 미션에서 꼭 반영해주세요! 
Approve 하겠습니다!

2022-03-22 13:24 UTC, merged