[2단계 - 나만의 유튜브 강의실] 하리(이아현) 미션 제출합니다.
woowacourse/youtube-classroom pull request #119
Opened 2022-03-18 17:48 UTC by LAH1203

안녕하세요 YB님! 그동안 잘 지내셨나요? 😄

<br>

## 구현 기능 목록

2단계 때는 (미약하지만) 구현 요구사항 외에도 제가 추가적으로 넣은 기능도 있어서 이번엔 따로 구현 기능 목록을 적어볼까 해요! (`docs/README.md`도 참고 부탁드릴게요 :))

- [x] 페이지 방문 시, 기본 메인 화면으로 내가 볼 영상들의 리스트를 보여준다.
- [x] 본 영상, 볼 영상 버튼을 눌러 필터링 할 수 있다.
- [x] 영상 목록은 유저가 사용하는 디바이스의 가로 길이에 따라 반응형으로 동작할 수 있도록 만든다.
- [x] 저장된 영상이 없을 경우, 비어있다는 것을 사용자에게 보여준다.
- [x] 영상 카드의 이모지 버튼을 클릭하여 본 영상으로 체크하거나 저장된 리스트에서 삭제할 수 있다.
- [x] 검색어 입력 시 x 버튼을 누르면 입력한 검색어가 초기화된다.
- [x] 최근 검색어를 최대 3개까지 저장할 수 있으며, 해당 검색어 버튼 클릭 시 검색할 수 있다.
- [x] 모두 체크 또는 모두 삭제 버튼 클릭 시 해당 탭에 있는 모든 영상들을 체크 또는 삭제할 수 있다.

사실 더 넣고 싶은 기능이 많았지만, 피드백을 받는 것이 우선이라고 생각하였기 때문에..! 일단 이 정도로 마무리하였습니다. 중복되는 코드들도 여럿 보여서 걱정되는데, 혹시 조금이라도 신경 쓰이는 부분이 있으면 꼭 알려주세요!

<br>

### ✨[데모페이지](https://lah1203.github.io/javascript-youtube-classroom/)✨ 입니다.

혹시 중간에 API가 다 돼서 요청이 더이상 안되면 코멘트 달아주세요! 확인하는대로 바로 다른 API 키로 변경하도록 하겠습니다 :)

2022-03-20 14:12 UTC, youngbeomrhee requested changes
하리님 안녕하세요 Step2 구현하느라 고생 많으셨습니다
사용성을 위해 많이 고민하고 개선을 위해 노력하신 흔적이 보입니다 
요구사항 외에 추가적으로 사용성을 위해 개선해 주신 점이 인상 깊었습니다

다만 기능상 몇 가지 오류가 보여서 수정요청 드립니다

## 기능상 오류 (필수수정)
- 본 영상에서 다시 한 번 v 체크가 가능. v 체크 후에는 목록에서 사라짐
- width: 500px 이하부터 화면 깨짐
- 볼 영상으로 100개 저장 -> 볼 영상 100개 본 영상으로 상태 변경 => 본 영상에 이미 저장된 목록이 있는 경우 100개를 넘어가는 일부 영상 목록 유실

## 기능상 오류 (선택)
- 최근 검색 클릭 후 스크롤시에 검색어 유실 (필수요구사항이었다면 필수로 수정해야 겠지만 추가로 넣으신 기능과 관련된 오류라 선택적으로 수정하시면 될 것 같습니다)
- 모바일 버젼에서 스크롤 안됨 (크롬 개발자 모드에서 테스트 가능) : 핸드폰에서 열었을 경우에도 스크롤이 안됐다면 필수수정요청 사항이었겠지만 핸드폰에서는 정상동작해서 선택사항으로 남깁니다

기능상 오류를 일으킨 코드 레벨에서의 오류는 아직 시간여유가 있으니 위의 코멘트 참고하셔서 수정해 보시면 좋을 것 같습니다

2022-03-20 14:12 UTC, youngbeomrhee commented on docs/README.md
> +- [x] (추가한 기능) 검색어 입력 시 x 버튼을 누르면 입력한 검색어가 초기화된다.
사용편의성을 위해 세세한 기능까지 고려하셨네요 👏

2022-03-20 14:12 UTC, youngbeomrhee commented on src/css/global.css
> +  --link-hover-color: #00bcd4;
색상과 관련된 값들을 변수로 잘 분리하셨네요 👏

2022-03-20 14:12 UTC, youngbeomrhee commented on src/css/responsive.css
> +    grid-template-columns: repeat(1, 1fr);
grid를 적절히 잘 활용해 주셨네요 👏

2022-03-21 07:44 UTC, LAH1203 commented
## 기능상 오류 (필수수정)
- 본 영상에서 다시 한 번 v 체크가 가능. v 체크 후에는 목록에서 사라짐
  - 음 볼 영상 -> 본 영상으로 간 다음 본 영상 -> 볼 영상이 가능한 것 때문에 달아주신게 맞을까요?
  - 만약 위와 같은 이유였다면 제가 볼 영상 <-> 본 영상 사이에서 상태 변환이 자유롭게 되도록 해서 그런 것 같아요.
  - 일단 혹시나 해서 제가 테스트해본 바로는 볼 영상 <-> 본 영상 사이에서 상태 변환은 잘 되는 것으로 보입니다..!
  - 혹시 제가 짐작한 것과 다른 오류였다면 알려주세요!
  - 그리고 본 영상의 체크 버튼에 색이 있으면 더 좋을 것 같아서 추가해주었습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/119/commits/72b27a3b387d6a0a78a4506a3dad6656668d89fe
- width: 500px 이하부터 화면 깨짐
  - 아마 타이틀과 검색어 입력 부분을 말씀하신 것이겠죠? 저도 그 부분이 문제라고 생각했습니다ㅠㅠ
  - 사실 비율을 고정하고 싶었으나... 현재의 제 능력 밖의 일이었습니다..... 😱
  - 그래서 우선 반응형 부분으로 크기를 조절하는 부분을 추가해주었어요! https://github.com/woowacourse/javascript-youtube-classroom/pull/119/commits/18caffa820817fc389d96f0212b47de266e25ebe
- 볼 영상으로 100개 저장 -> 볼 영상 100개 본 영상으로 상태 변경 => 본 영상에 이미 저장된 목록이 있는 경우 100개를 넘어가는 일부 영상 목록 유실
  - 이 부분은 제가 여러 번 테스트를 해봤는데, 유실되는 현상을 확인을 못 했습니다ㅠㅠㅠ
  - 죄송하지만, 한번만 더 확인 부탁드려도 될까요? 🥲

## 기능상 오류 (선택)
- 최근 검색 클릭 후 스크롤시에 검색어 유실 (필수요구사항이었다면 필수로 수정해야 겠지만 추가로 넣으신 기능과 관련된 오류라 선택적으로 수정하시면 될 것 같습니다)
  - 헉 네 오류 확인했습니다! 알려주셔서 감사합니다 :) 해결했습니다~ 😊 https://github.com/woowacourse/javascript-youtube-classroom/pull/119/commits/ab8fcb9818cb8a842741cefb3d0016007c6b145f
- 모바일 버젼에서 스크롤 안됨 (크롬 개발자 모드에서 테스트 가능) : 핸드폰에서 열었을 경우에도 스크롤이 안됐다면 필수수정요청 사항이었겠지만 핸드폰에서는 정상동작해서 선택사항으로 남깁니다
  - 말씀해주셔서 여러 번 테스트 해봤는데, 스크롤 되지 않는 문제를 확인하지 못했습니다ㅠㅠ
  - 죄송하지만, 이 부분도 다시 확인 부탁드려도 될까요..? 😰

2022-03-21 13:25 UTC, youngbeomrhee approved these changes
하리님 안녕하세요 피드백 반영하느라 고생하셨습니다 
사용성을 위해 많이 고민하신 점이 인상 깊었습니다
남은 과정 수료까지 화이팅 하시고 좋은 결과 있기를 응원하겠습니다
2주간 고생 많으셨습니다 Approve 하도록 하겠습니다

추가로 코멘트 주신 내용에 대한 답변은 아래 남겼습니다 

## 기능상 오류재현
기능상 오류는 재현 시나리오에 대해 좀 더 상세하게 안내해 드릴걸 그랬네요
테스트를 진행하실 때는 성공하는 몇 가지 케이스만 수행하면 에러가 잘 확인되지 않습니다
기능상 최대치, 경계선을 넘나드는 상황으로 만들고 테스트를 수행해야 예상하지 못한 에러를 발견할 수 있습니다
현재는 볼 목록을 100개까지 저장할 수 있으므로 그런 상태를 만든 후에 기존에 피드백 드린 시나리오대로 수행해 보시면 에러를 재현하실 수 있습니다
참고로 스크롤을 통해 검색목록을 100개 이상으로 만들고 아래 스크립트를 활용하면 좀 더 쉽게 저장할 수 있습니다
```
$$('.video-item button').forEach(ele => ele.click())
```
(모바일 버젼에서 스크롤 안됨 -> 이 부분은 다시 해보니 재현이 안되네요 브라우져상의 일시적인 오류였던 것 같습니다 😅)

2022-03-21 13:25 UTC, merged