[2단계 - 나만의 유튜브 강의실] 빅터(이우승) 미션 제출합니다.
woowacourse/youtube-classroom pull request #128
Opened 2022-03-19 03:38 UTC by woose28

안녕하세요 윌터님!
2단계 미션 제출합니다ㅎㅎ

### [데모 페이지](https://woose28.github.io/javascript-youtube-classroom/)

### 구현한 기능 목록
- [x] 저장된 영상이 없다면, 비어있다는 것을 사용자에게 알려준다.
- [x] 영상 카드의 ✅  아이콘을 누르면 `본 영상`으로 상태 값이 변경된다.
- [x] 영상 카드의 🗑️ 아이콘을 누르면 저장된 영상 리스트에서 해당 영상을 제거한다.
  - [x] 삭제 시 사용자에게 정말 삭제할 것인지 확인한다.
- [x] 본 영상, 볼 영상 버튼을 눌러 저장된 영상을 필터링할 수 있다. 
- [x] 유저가 사용하는 디바이스의 가로 길이에 따라 검색 결과의 row 당 column  개수를 변경한다.
  - 1280px 이상: 4개
  - 960px이상~1280px 미만: 3개
  - 600px이상~960px 미만: 2개
  - 600px 미만: 1개

### 2단계에서 달라진 점
- webStorage에 저장하는 데이터 수정
  - 1단계: videoId만 저장
  - 2단계: Video 모듈 인스턴스의 정보 저장(videoId, videoTitle, channelTitle, publishTime, thumbnail, isWatched)

- SAVED_VIDEO 상태 값에 저장되는 데이터 수정
  - 1단계: vidoeId가 담긴 리스트 저장
  - 2단계: Video 모듈 인스턴스가 담긴 리스트 저장

- Video 모듈에 비디오의 시청 여부를 저장하는 `isWatched` 프로퍼티 추가

---

요새 날씨가 점점 추워지더니 오늘은 제가 사는 동네에는 눈까지 왔더라고요🌨
윌터님도 감기 조심하시길 바라며, 이번 2단계 미션 리뷰도 잘 부탁드립니다!

감사합니다 :-)

2022-03-20 15:49 UTC, inwalter99 requested changes
고생하셨어요 빅터 :) 
날씨가 갑자기 추워졌죠ㅜ 감기 조심하세요.
전반적으로 좋은 것 같습니다 :) 한가지 고민거리를 드리고 싶은데 지금 AppBusiness 가 하는 일이 너무 많아지고 있다는 생각이 들었어요. 만약에 지금 서비스에서 기능이 한 두개만 더 추가됐을 때를 상상해보면 어떨까요? AppBusiness 을 분리해보면 좋을 것 같은데, 시간 관계상 실제로 분리는 어려울 것 같고 아이디어만 생각해서 코멘트 달아주시면 좋을 거 같아요!!

2022-03-20 15:49 UTC, yongholeeme commented on cypress/integration/search.spec.js
> +    cy.intercept(API_URL, { fixture: 'searchResultData.json' }).as('requestVideo');
👍

2022-03-20 15:49 UTC, yongholeeme commented on src/js/modules/video.js
> +  #init({ videoId, videoTitle, channelTitle, publishTime, thumbnail, isWatched }) {
constructor 자체가 초기화하는 메서드이기 때문에 init 은 따로 분리안해도 좋을 것 같아요! https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Classes/constructor

2022-03-20 15:49 UTC, yongholeeme commented on src/js/components/SearchModalComponent.js
> +  #initChildrenComponent() {
👍

2022-03-20 15:49 UTC, inwalter99 commented on src/js/business/index.js
> +    });
~getVideo 정도로 이해가 되는 메서드이고, id 는 고유하니 항상 하나의 video 가 리턴될 거 같은데 filter 로 배열을 반환하는 이유가 있을까요?~
아 =ㅁ= 죄송합니다 난독이.. targetVideo 를 제외하고 새로운 배열을 반환하는 거군용..

2022-03-20 15:49 UTC, inwalter99 commented on src/js/business/index.js
> +    });
수정할 필요는 없고, savedVideoList 가 길어졌을 때를 고민해보면 좋을 거 같아요 ;)
하나의 video 를 고치기위해 모든 배열을 순회할 필요가 있을까~?에 대한 생각을..!
map 말고 다른 방식을 써볼까? 아예 자료구조를 바꿔볼까? 등등..

2022-03-21 07:19 UTC, woose28 commented on src/js/modules/video.js
> +  #init({ videoId, videoTitle, channelTitle, publishTime, thumbnail, isWatched }) {
`constructor 자체가  초기화하는 메서드이다.` 명심하겠습니다!

2022-03-21 09:00 UTC, woose28 commented
> 지금 AppBusiness 가 하는 일이 너무 많아지고 있다는 생각이 들었어요. 만약에 지금 서비스에서 기능이 한 두개만 더 추가됐을 때를 상상해보면 어떨까요? AppBusiness 을 분리해보면 좋을 것 같은데, 시간 관계상 실제로 분리는 어려울 것 같고 아이디어만 생각해서 코멘트 달아주시면 좋을 거 같아요!!

동의합니다, 현재 AppBusiness 가 하는 일이 너무 많은 거 같아요..!

현재 구조에서 AppBusiness가 하는 일을 아래와 같이 정리했습니다!
- 검색 모달 on/off 이벤트
- 검색 이벤트(키워드로 검색)
- 무한 스크롤 시 새로운 영상을 불러오는 이벤트
- 비디오 저장 이벤트
- 저장된 비디오 필터 이벤트
- 비디오 시청 이벤트
- 비디오 삭제 이벤트

저는 위의 이벤트를 크게 3가지 구조로 나누면 좋을 거 같습니다!

1. UI 관련 이벤트(AppBusiness)
- 사실 UI 관련된 이벤트는 비즈니스 영역이 아니라 UI영역이라는 생각이 문득들었지만..! 현재 구조에서는 UI 관련 이벤트는 아래 처럼 정리할 수 있을 거 같습니다.
  -  검색 모달 on/off 이벤트
  - 저장된 비디오 필터 이벤트

2. 비디오 검색 관련 이벤트(SearchBusiness)
- 검색 이벤트(키워드로 검색)
- 무한 스크롤 시 새로운 영상을 불러오는 이벤트

3. 비디오 상태 변화 이벤트(VideoStateBusiness)
- 비디오 저장 이벤트
- 비디오 시청 이벤트
- 비디오 삭제 이벤트

이를 도식화한 결과는 아래와 같습니다!

<img width="821" alt="AppBusiness 분리 예시" src="https://user-images.githubusercontent.com/52148907/159229535-9a545477-aeb2-40a5-ad34-cfd8127bd4f0.png">

2022-03-21 09:30 UTC, woose28 commented on src/js/business/index.js
> +    });
코드를 수정해서 반영하려 했으나, 시간을 준수하지 못했습니다🙏🙏

피드백 해주신 부분에 대해서 저는 `자료구조를 바꿔보자`에 초점을 맞춰생각해봤습니다.
그리고 `STATE_STORE_KEY.SAVED_VIDEO 상태 값을 배열이 아니라 객체로 관리해보자!`라는 생각을 했습니다.

객체는  아래의 예시처럼 videoId를 key로 가지고 value로는 Video 모듈을 가지도록 생각했습니다.
```javascript
const state  = {
  ...
  [STATE_STORE_KEY.SAVED_VIDEO]: {
    [videoId]: Video 모듈
  }
  ...
}
```

STATE_STORE_KEY.SAVED_VIDEO에 저장된 값을 객체 형태로 관리한다면 커멘트 남겨주신 부분 코드를 아래처럼 수정할 수 있을 거 같습니다!
```javascript
src/js/business/index.js

updateWatchedState(targetVideoId) {
    const savedVideoBundle = getState(STATE_STORE_KEY.SAVED_VIDEO);

    const targetVideo = savedVideoBundle[targetVideoId];
    targetVideo.toggleWatchState();

    return savedVideoBundle;
  }
```

아직 코드를 구현하지 못해 테스트를 못하고, 주저리주저리 적어서 죄송합니다.

해당 부분이 테스트 완료되면, 커밋은 하지않고 코멘트로 결과를 보고드리겠습니다...!

2022-03-21 14:26 UTC, inwalter99 commented
> 동의합니다, 현재 AppBusiness 가 하는 일이 너무 많은 거 같아요..!
현재 구조에서 AppBusiness가 하는 일을 아래와 같이 정리했습니다!

좋습니다! 사실 Business 라는 말이 좀 어색하게 느껴지긴한데ㅎㅎ 현재 구조에서는 저도 빅터처럼 분리하지 않을까 싶네요!
(FE 특성상 역할을 뭔가 명확하게 분리해 네이밍을 하는 것도 좀 어려움이 있긴 합니다.) 
현재 구조에서 개선을 해보자면(입코딩을 해보자면) 저는 과연 이 비즈니스 로직들은 컴포넌트와 분리시켜야하는 걸까? 라는 고민도 들고 그러면 business 를 각 컴포넌트로 위치시켜볼까 라는 생각도 드네요. 

이런 고민들의 흐름을 잘 나타낸 아티클이 있는데요. 시간날 때나 방학 중에 https://velog.io/@teo/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C%EC%97%90%EC%84%9C-MV-%EC%95%84%ED%82%A4%ED%85%8D%EC%B3%90%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80%EC%9A%94 요 아티클 한 번 읽어보면 좋을 것 같아서 공유드려요 :)

2022-03-21 14:28 UTC, yongholeeme approved these changes
2단계도 너무 고생하셨습니다 빅터님!
마무리에는 코드말고 글과 그림으로 정리해주셔서 감사했습니다!

혹시 제가 놓친 코멘트나 질문있다면 말씀해주세요~!

2022-03-21 14:28 UTC, merged