[1단계 - 나만의 유튜브 강의실] 브콜(오태은) 미션 제출합니다.
woowacourse/youtube-classroom pull request #13
Opened 2021-03-06 03:43 UTC by Tanney-102

안녕하세요! 브콜입니다🥦🥦🥦🥦
저의 페어 티케(@devhyun637)과 함께 미션 진행하였습니다.
설계 측면에서 많이 부족함을 느끼지만 우선 주어진 기능을 충실히 구현하는데 집중했습니다! ㅎㅎ
꿀🍯 같은 조언 많이 많이 부탁드립니다!!

### [데모 페이지(https://beutube.netlify.app/)]

### 고민한 부분 및 해결 방법

1. API key의 은닉화 문제에 대해 고민을 했습니다.
    - 해결
      netlify 배포시 build command에 echo -e 명령어를 포함해 API key를 가지고 있는 파일을 생성하도록 했습니다.

2. iframe이 로드되는 시점이 제각각인 문제가 있었습니다.
    - 해결
      fetch로 가져온 영상들에 대한 iframe이 모두 load되는 시점에 커스텀 이벤트를 dispatch 하도록 했습니다.
      iframe에 srcdoc 속성을 추가해 유튜브 영상이 로드 되기 전에 썸네일이 먼저 보여지도록 했습니다.
    

3. 적절한 html tag를 사용하려고 노력하였습니다.
    - 웹 접근성을 위해 modal에 aria-* 속성을 사용하였습니다.
    - modal 닫기 button에 type="button"을 추가하였습니다.
    - input tag에 requried 속성과 aria-label 속성을 사용하였습니다.
    - 검색 button의 type을 submit으로 바꾸었습니다.
    - 매 section마다 제목이나 aria-label 속성을 추가하였습니다.
    - skeleton UI, 최근 검색어를 list 태그를 사용하여 작성하였습니다. (ul > li)
    - 제목 수준을 뛰어넘지 않고, 순서대로 작성하였습니다.
    - image Tag에 alt 속성을 넣어주었습니다.
    
4. 영상 중에서 재생할 수 없는 영상이 있었습니다. 이 경우 받아온 data에 video id가 포함되지 않아 오류를 유발했습니다.
    - 해결
      video id 가 없는 데이터를 모두 filter 했습니다. 

### 유스케이스를 고려한 기능 목록

1. 유투브 검색을 선택하면 modal 창이 열린다.

2. 사용자는 유투브 검색창에 보고싶은 영상을 입력한다. 

- [x] 2.1. enter를 통해서도 검색이 가능하다. 

3. 유투브 api를 통해서 결과를 가져온다 

- [x] 3.1. 결과가 없을 경우 없다는 이미지를 보여준다. (not-found Img)

- [x] 3.2. 결과가 있을 경우, 10개까지만 보여준다. 

- [x] 3.3. 재생할 수 없는 영상의 경우, 가져오지 않는다.

- [x] 3.4. 스클롤을 내릴때 추가로 영상 10개를 가져온다.

- [x] 3.5. 영상 로딩이 될 때, skeleton을 UI를 보여준다. 

4. 검색 결과에서 맘에 드는 영상을 저장할 수 있다.

- [x] 4.1. 저장을 하면 localStorage에 videoItem을 저장한다.

- [x] 4.2. 저장한 영상은 저장 버튼을 숨긴다.

- [x] 4.3. 저장은 최대 100개까지 할 수 있다. 

- [x] 4.4. 100개 이상을 저장하려고 하면, alert로 경고를 한다. 

- [x] 4.5. 저장한 영상의 개수를 보여준다. (ex. 1/100개)

5. 다시 검색하기를 누르면, 마지막에 검색한 키워드로 검색한 결과를 보여준다.

- [x] 프로그램을 재시작하면 reset해준다. 

- [ ] 검색 결과를 초기 10개만 보여준다.  -> 다음 미션에 구현 예정

6. 최근 검색어를 최대 3개까지 보여준다.

- [x] 6.1. 방금 검색한 단어도 바로 보여준다.

- [x] 6.2. 프로그램을 재시작해도, 최근 검색어의 기록은 남아있다. (ex. localStorage)

### UX를 고려한 기능

- modal을 열면 input에 autofocus가 되도록 구현하였습니다.
- 저장버튼에 마우스 hover를 할 때, 색이 변하는 효과를 추가하였습니다.
- 검색 결과 영상 재생 버튼에 마우스 hover가 될 때, transition, transform 효과를 주었습니다.
- 검색결과 화면에만 scroll이 되도록하여 무엇을 검색하였는지 계속 볼 수 있도록 하였습니다.

### 앞으로 할 일

- 동영상 검색 버튼 위에 마우스를 옮기면 색이 변한다.
- 최근 검색어에 삭제 버튼을 만들어, 누르면 삭제를 한다.
- 입력된 검색어를 한꺼번에 지울 수 있는 버튼이 있다.
- 동영상이 load 될 때마다 skeleton ui를 보여준다.
- 저장 button 라인 맞추기
- 최근 검색어 위에 마우스를 hover하면 색이 변하고, 누르면 검색할 수 있다.
- 최근 검색어의 수를 10글자로 제한한다.
- 저장된 영상의 버튼은 '저장됨'으로 글자를 바꾸고, 버튼을 비활성화 한다.
- 검색 결과 동영상은 List 태그로 보여준다.
- modal 밖을 선택하면 창이 닫힌다.

UX적인 측면을 더 고려해서 추가적인 기능들을 만들고 싶었지만, 일단 필수 구현 기능을 구현하고 이번 리뷰와 다음 단계 미션을 하면서 리팩토링 해나가기로 했습니다. 잘부탁드립니다. 🙂

2021-03-07 10:03 UTC, Vallista requested changes
안녕하세요 브콜님~ 😄 
리뷰어 vallista입니다! 이번 미션 잘 부탁드립니다. 👍 

아무래도 UX/UI 측면에서 사용성이 높은 프로젝트이다보니, 3가지 관점(UX/UI, 프로젝트 설계, 코드) 으로 피드백을 드리려 합니다!

---

UX/UI 피드백입니다.

![우측 비디오는 스켈레톤이 없는 현상](https://user-images.githubusercontent.com/6455767/110227348-de56e700-7f3a-11eb-9947-59a284de71ab.png) 이 있습니다!

1. 우측 비디오가 스켈레톤 없는 현상은 수정해야할 것 같습니다!

2. 검색 후, 실수로 저장할 수도 있을 것 같습니다

![스크린샷 2021-03-07 오전 11 53 37](https://user-images.githubusercontent.com/6455767/110227429-c92e8800-7f3b-11eb-9a24-282d39cce75a.png)
저장을 취소하는 기능도 있으면 좋을 것 같습니다 🙏 

4. 동영상 검색은 `볼 영상`, `본 영상` 버튼과 레벨을 동일하게 하면 유저에게 혼동을 줄 것 같습니다.

![스크린샷 2021-03-07 오전 11 55 58](https://user-images.githubusercontent.com/6455767/110227464-1c083f80-7f3c-11eb-8c15-7029f091f399.png)
동영상 검색은 눌러도 초록색으로 active 변경이 되는 요소가 아니므로, 해당하는 부분은 레이아웃을 다르게 가져가면 좋을 것 같습니다. (돋보기만 보인다던지..)


---

전반적인 피드백입니다.

1. 테스트의 경우 레이아웃 테스트와 기능 테스트가 산재해 있는데, 두 가지를 분리해서 테스트를 작성하면 좋을 것 같습니다.
ex) 최금 검색어에는 중복된 단어가 없다 = 기능 테스트, 최근 검색어는 최대 3개까지 보여준다 = 레이아웃 테스트

2. 전반적으로 Object를 쓰셨는데, Object를 쓰기보다 class로 하여금 객체를 생성해서 관리하는게 더 좋을 것 같습니다!

---

자세한 리뷰는 코드 라인 단위로 피드백 드렸습니다! 👍 👍

2021-03-07 10:03 UTC, Vallista commented on .eslintrc.json
> +    "class-methods-use-this": "off",
use this를 허용하는 이유가 있을까요?

2021-03-07 10:03 UTC, Vallista commented on .eslintrc.json
> +    "max-lens": 80
length 80을 고정한 이유가 있을까요~?

2021-03-07 10:03 UTC, Vallista commented on index.html
> +              id="skeleton-search-results"
skeleton-search-results 라는 이름이 되기 위해 다양한 컨벤션을 시도해보셨을 것 같은데, 일관성 측면이나 협업측면에서 많이 쓰이는 [BEM 방법론](http://getbem.com/naming/) 을 써보는 건 어떨까요?

2021-03-07 10:03 UTC, Vallista commented on index.html
> +              <li class="clip">
```html
<li class="clip">
                <article class="mt-10">
                  <div class="preview-container">
                    <div class="skeleton image"></div>
                  </div>
                  <div class="content-container mt-2">
                    <div class="skeleton line"></div>
                    <div>
                      <div class="skeleton short-line mt-1"></div>
                      <div class="skeleton short-line mt-1"></div>
                      <div class="d-flex justify-end">
                        <div class="skeleton skeleton-btn mt-1"></div>
                      </div>
                    </div>
                  </div>
                </article>
              </li>
```

이 로직은 반복되는 것 같습니다! `container`를 하나 id로 만들어서, for 루프를 돌며 js에서 html을 주입해주는 건 어떨까요?

2021-03-07 10:03 UTC, Vallista commented on package.json
> +    "eslint": "^7.21.0",
dev dependency로 넣은 것은 좋습니다!

2021-03-07 10:03 UTC, Vallista commented on src/css/shared/modules/button.css
> +.save-btn:hover {
css는 도메인 적 성격보다 스타일 적 성격으로 이름을 짓는 것은 어떨까요?

가령, `.save-btn`은 저장버튼만을 위한 클래스인데, 저장 버튼이 프로젝트 단위에 그렇게 많지 않으므로, `.submit-btn`으로 한다던지.. 

도메인으로 한정시키는 것 보다는 기능, 재사용 측면에서 적용하는게 좋아보입니다. 그렇지 않다면 id로 해서 성능 및 직관적인 측면에서 더 좋은 퍼포먼스를 가져가는게 좋아보입니다!

2021-03-07 10:03 UTC, Vallista commented on src/css/ui/modules/modal.css
> +ul {
modal에 ul element 전역에 대한 스타일링 부분이 있으면 안될 것 같습니다! 글로벌 영역에 있어야 할 것 같아요!

2021-03-07 10:03 UTC, Vallista commented on src/css/ui/modules/skeleton-ui.css
> +@keyframes shining {
애니메이션을 도메인 파일 단위로 가져갈 지, 단독 애니메이션 파일로 가져갈지... shining은 전역에서 관리해야 할 것 같은 애니메이션 이름이군요..

2021-03-07 10:03 UTC, Vallista commented on src/js/index.js
> +new SearchEventBinder().bindEvents();
```jsx
const searchEventBinder = new SearchEventBinder()
searchEventBinder.init();
searchEventBinder.bindEvents();
```

형태로 가져가는게 더 좋아보입니다. 이렇게 되면 객체를 사용할 이유가 없어보여요.
class 형태로 캡슐화 해서 사용하는 의미는 여러가지가 있지만 그 중에서도 위의 경우에는 사용처에서 객체를 생성해서 외부로 노출되는 함수를 사용할 수 있게 하고자 사용하는 목적이 큽니다.

그래서 클래스를 사용하여 객체를 생성할 때에는 (비단 클래스 뿐만 아니라 자바스크립트에서 객체를 활용할 때, 모든 언어에서 사용할 때에는) 객체의 생성과 선언이 함께 이루어져야 합니다. 추후에 그 객체로 다른 행동을 할 수도 있기 때문이죠.

2021-03-07 10:03 UTC, Vallista commented on src/js/search/SearchEventBinder.js
> +    const searchKeyword = e.target.elements["search-keyword"].value;
`search-keyword`가 없으면 이 함수는 터질 것 같은데, 예외를 만들어야 하지 않을까요?

2021-03-07 10:03 UTC, Vallista commented on src/js/search/SearchView.js
> +    elements.$keywordHistory.innerHTML = getKeywordHistoryTemplate();
innerHTML보다 [insertAdjacentHTML](https://developer.mozilla.org/ko/docs/Web/API/Element/insertAdjacentHTML) 이 더 좋지 않을까요?

2021-03-07 10:03 UTC, Vallista commented on src/js/state/loadingSearchResults.js
> +const loadingSearchResults = {
class 를 사용하는게 더 좋지않을까요? 아니면, Object.freeze를 사용하는게 더 좋아보입니다!

외부에서 쓰일 때 아무래도 override를 하면 값을 전부 바꿔버릴 수 있다보니, 값을 다룰 때 조심해야할 것 같아요!

2021-03-07 10:03 UTC, Vallista commented on src/js/state/loadingSearchResults.js
> +const loadingSearchResults = {
또한 객체이다보니, 바로 가져다 쓰면 원본 데이터를 사용해야할 때나 여러 군데에서 가져올 때 용이하지 못할 것 같습니다!

2021-03-07 10:03 UTC, Vallista commented on src/js/templates/keywordHistoryTemplate.js
> +export default function getKeywordHistoryTemplate() {
굳이 함수로 가져오지 않아도 될 것 같습니다!

2021-03-07 10:03 UTC, Vallista commented on src/js/templates/videoClipTemplate.js
> +  const [year, month, date] = dateString.split("T")[0].split("-");
date 타입이 맞는지 검증하는 로직이 있으면 좋을 것 같습니다 :)

2021-03-07 10:03 UTC, Vallista commented on src/js/search/SearchController.js
> +    const isBottom = clientHeight + scrollTop >= scrollHeight - 5;
5와 같은 magic number는 전역의 constant로 빼서 관리하는게 좋지 않을까요?

2021-03-07 10:36 UTC, Vallista commented on src/js/state/loadingSearchResults.js
> +const loadingSearchResults = {
다만, Object.freeze를 하면 내부 객체의 상태를 변경할 수 없으니, 이렇게 해야하긴 하겠군요.. Object.create를 통해 객체를 생성해보는 것도 좋겠습니다!

2021-03-10 04:58 UTC, Tanney-102 commented on .eslintrc.json
> +    "class-methods-use-this": "off",
처음 클래스 구조를 잡을 때 빨간줄이 거슬려서 잠깐 꺼두었는데 그래도 까먹어버렸네요ㅜㅜㅜ 수정했습니다 ㅎㅎ
commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/a02b9b62d9204582748184bc1011198b8bd7251c

2021-03-10 04:59 UTC, Tanney-102 commented on .eslintrc.json
> +    "max-lens": 80
화면이 작아 좌우 간격을 제한했습니다!

2021-03-10 05:02 UTC, Tanney-102 commented on index.html
> +              <li class="clip">
넵 controller 생성시 초기화 해주도록 수정했습니다
commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/231cbdfc8715a791176b7630ae0a1a576d766ddb

2021-03-10 05:06 UTC, Tanney-102 commented on src/js/search/SearchView.js
> +    elements.$keywordHistory.innerHTML = getKeywordHistoryTemplate();
이부분은 엘리먼트를 insert 하기보다 새로 업데이트 된 '최근 검색어' 들을 한 번에 업데이트 해주는 것이 좋겠다고 생각했습니다.
화면에 이미 렌더되어 있는 최근 검색어를 클릭할 시 순서가 바뀐다든지 x 아이콘을 눌러 검색어를 삭제한다든지 하는 동작을 포함하고 있어 innerHTML을 사용했습니다.

2021-03-10 05:18 UTC, Tanney-102 commented on src/js/state/loadingSearchResults.js
> +const loadingSearchResults = {
이 부분에 대해 질문하고싶습니다!
사실 저희는 state를 유일한 객체로 만들어 참조하고 싶어 객체리터럴로 만들었습니다.
그럼에도 프로토타입을 통해 '생성'을 해줄 필요가 있는지, 혹은 유일하게 사용하더라도 싱글턴을 구현해 사용하는 것이 좋을지 의견 묻고 싶습니다!

2021-03-10 05:24 UTC, Tanney-102 commented on src/js/templates/keywordHistoryTemplate.js
> +export default function getKeywordHistoryTemplate() {
videoClipTemplate이 분리될 필요가 있다고 느꼈습니다. 그리고 분리하는 과정에서 일관성을 위해 다른 템플릿들도 분리하기로 결정했습니다!

2021-03-10 05:26 UTC, Tanney-102 commented on src/js/templates/videoClipTemplate.js
> +  const [year, month, date] = dateString.split("T")[0].split("-");
Date 객체의 내장메서드를 통해 일관된 형식을 취하고 유효성을 검사할 수 있도록 로직을 추가했습니다!
commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/6501b0332715d2028ccd68bc688eef7548f488ab

2021-03-10 05:27 UTC, Tanney-102 commented on src/js/search/SearchController.js
> +    const isBottom = clientHeight + scrollTop >= scrollHeight - 5;
scroll 이벤트를 최적화하는 과정에서 IntersectionObserver API를 사용하는 방향으로 바뀌어 해당 로직이 사라졌습니다 ㅎㅎ 다음부터는 상수화에 더 신경쓰겠습니다!

2021-03-10 05:32 UTC, Tanney-102 commented on src/css/shared/modules/button.css
> +.save-btn:hover {
- 버튼 종류에 따라 small-btn, round-btn을 추가했습니다.
- 버튼 호버시 색을 바꿔주기 위해 btn-hover-gray-300 과 같은 네이밍을 사용했습니다.

2021-03-10 05:33 UTC, Tanney-102 commented on src/css/ui/modules/modal.css
> +ul {
넵 글로벌 영역으로 옮겨 두었습니다.
commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/d0acc43c8c50f0af9010432a856b711aa322fb38

2021-03-10 05:35 UTC, Tanney-102 commented on src/css/ui/modules/skeleton-ui.css
> +@keyframes shining {
넵 말씀해주신대로 shining은 shared에 있어야 할 것 같은 keyframe 이름인 것 같네요ㅜㅜㅜ
skeleton에 대한 도메인에서만 사용할 목적으로 skeleton-shining이라는 이름을 주었습니다.

2021-03-10 05:40 UTC, Tanney-102 commented on src/js/index.js
> +new SearchEventBinder().bindEvents();
사실 searchEventBinder의 주된 목적은 최초 실행시 각 이벤트에 대해 핸들러를 붙여주는 부분이라 따로 생성한 인스턴스를 할당하지는 않았습니다. 그런데 말씀을 듣고보니 확실히 객체를 객체답게 쓰지 못하고 있는 것 같네요 ㅜㅜ 
그럼 혹시 저희가 의도한 목적의 경우에는 그냥 함수로 구현해 호출하는 것이 맞을까요?

2021-03-10 05:43 UTC, Tanney-102 commented on src/js/search/SearchEventBinder.js
> +    const searchKeyword = e.target.elements["search-keyword"].value;
사실 'search-keyword가 없는 경우'가 잘 상상이 되질 않습니다ㅜㅜ
input valuer가 없는 지에 대해서는 input 태그에 required속성을 넣어 주었고 이미 정적으로 작성된 html 문서에서 엘리먼트를 가져오는 것인데 '없는' 경우에 대해 유효성 검사를 해줄 필요가 있는지 잘 공감이 되지 않습니다.

혹시 이부분에 대해 제가 잘못 이해를 했거나 놓치고 있는 부분이 있다면 조언 부탁드립니다 ㅎㅎ (회초리 기다리고 있겠습니다ㅜ)

2021-03-10 05:53 UTC, Vallista commented on src/js/index.js
> +new SearchEventBinder().bindEvents();
의도하신 경우에는 함수로 추출해서 쓰는게 heap 메모리를 사용하지 않고, stack 메모리에서 (혹은 코드레벨에서) 빠르게 사용될 수 있기 때문에 (다른 언어 등에서도) 차이는 크지 않겠지만 속도적인 측면에서 이득이 있을 수 있는 것 같고, 전체 프로젝트의 클래스 일관성을 사용하시는 목적으로 .init(), .bindEvents() 등을 추가해서 사용하시면 좋을 것 같습니다.

2021-03-10 05:57 UTC, Vallista commented on src/js/search/SearchEventBinder.js
> +    const searchKeyword = e.target.elements["search-keyword"].value;
예를들어, search-keyword가 수정이되어 search-keyword-alpha가 되었다고 가정하면, 함께 이 코드도 수정을 해주어야 할 것 입니다. 만약 정신이 없는 상태에서 html만 수정하고 이 코드를 수정하지 않는다면 어떤일이 벌어질지... (암담)

그렇기 때문에 이러한 휴먼에러를 막기 위해서 최상단에 e.target.elements['search-keyword'] 에 대해서 있는지 없는지 검증하고 console.error등으로 알려주면 좋을 것 같습니다. 

아니라면, 해당 element id나 class를 constant 객체로 가져서 관리를 한다면 해당 예외가 필요없을 수 있겠네요.

```js
export const CONSTANT_CLASSNAMES = Object.freeze({
  ...
  SEARCH_KEYWORD: 'search-keyword'
})
```

2021-03-10 05:57 UTC, Tanney-102 commented
추가로 수정한 사항입니다.
1. 딤드 영역을 클릭하면 모달창이 사라지도록 했습니다.
  - buttondown 이벤트를 받아 모달 안쪽에서 딤드 영역으로 드래그시 모달이 사라지는 문제를 해결했습니다.
  - commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/0e792beac7b8cba35fecc582221470381719826d, https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/3c4822951850f1b72045d37d0b204f27f86e2aea

2. 최근 검색어의 길이를 제한하고(ellipsis) 최근검색어를 누르면 새로 검색, x 아이콘을 누르면 사라지도록 구현했습니다.
  - commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/cb8a2d75040a81feff0952d46a86df112946c8e5, https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/a0d186fc5d4493da5a1099359a8e9fbb27cf7cbd,  https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/fa4a206bd0f58029718cff70866cabd2fe3b23fb

3. skeleton 관련 버그 해결했습니다.
  - commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/260b505c91718f1657e9bb1890fb8abd058b07a0

4. 저장버튼의 기능을 수정했습니다.
  - 저장버튼을 누르면 '저장 취소' 버튼으로 바뀜
  - 저장 취소 버튼을 누르면 다시 저장 버튼으로 바뀌며 저장이 취소됨
  - commint link :  https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/3a9f5af68bdc6ffe6b822837b5ea280fa98e8a2b

5. 동영상 검색 버튼에 대한 레이아웃을 수정했습니다.
  - 이 부분에 대한 피드백을 보고 감탄했습니다 ㅎㅎ 전혀 생각치 못했던 부분인데 덕분에 많이 배웁니다. 감사합니다🥦🥦🥦
  - commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/27e83ebac80f26c008b3d4fead47717fe90d4a89

6. 테스트를 기능과 레이아웃으로 분리했습니다.
  - commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/734b26a06ba2dd333c6534834fe93bc29d5ed24f, https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/a58bb82db275f8a842665d57e38c3b87c7e92c8d

2021-03-10 05:57 UTC, Vallista commented on src/js/search/SearchView.js
> +    elements.$keywordHistory.innerHTML = getKeywordHistoryTemplate();
오! 넵!

2021-03-10 05:58 UTC, Vallista commented on src/js/state/loadingSearchResults.js
> +const loadingSearchResults = {
유일한 객체로 만들어 참조하는 목적이라면 좋은 것 같습니다!

2021-03-10 05:58 UTC, Vallista commented on src/js/templates/keywordHistoryTemplate.js
> +export default function getKeywordHistoryTemplate() {
일관성을 위해 함수로 모두 뺀 것 이군요~ 알겠습니다!

2021-03-10 06:12 UTC, Tanney-102 commented on index.html
> +              id="skeleton-search-results"
BEM 방법론이라는 것이 있었군요!! 도입을 해보는 것이 좋을 것 같긴한데 우선 미션 기한이 있다보니 우선 순위가 높은 기능들 먼저 구현하고 여유가 되면 고려해보겠습니다! ㅎㅎ

2021-03-10 07:18 UTC, Tanney-102 commented on src/js/index.js
> +new SearchEventBinder().bindEvents();
아아 넵 그렇군요 ㅎㅎㅎ 인스턴스를 생성 및 할당해서 사용하는 방식으로 수정했습니다!
commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/a22a481e3bfa200bbcbeeaf40dfc03d4583817f7

2021-03-10 07:30 UTC, Vallista approved these changes
안녕하세요 브콜님~

1단계 미션에 대한 피드백을 해주셔서, 해당 리뷰에 대한 피드백을 진행하였습니다~
상세한 부분은 코드 라인에 피드백을 드렸으니, 해당 하는 부분을 확인하시고 다음 단계 작업을 하시면서 함께 적용하시면 될 것 같습니다 :)

감사합니다!

2021-03-10 07:30 UTC, Vallista commented on src/css/ui/modules/chip.css
> +  justify-content: space-between;
display flex 속성과 관계된 친구이므로 display inline-flex와 비슷한 위치에 놓는게 좋지 않을까요?

2021-03-10 07:30 UTC, Vallista commented on src/js/queries/searchQuery.js
> +  const pageTokenQuery = pageToken && `pageToken=${pageToken}`;
pageToken이 false면 undefind가 떨어지는데, 괜찮을까요?

2021-03-10 07:30 UTC, Vallista commented on src/js/queries/searchQuery.js
> +  return `part=snippet&key=${YOUTUBE_API_KEY}&q=${keyword}&maxResults=${VIDEOS.SEARCH_MAX_RESULT}&${pageTokenQuery}`;
위의 pageTokenQuery가 false인 상황에서 등록하면 

`part=snippet&key=${YOUTUBE_API_KEY}&q=${keyword}&maxResults=${VIDEOS.SEARCH_MAX_RESULT}&false`가 될 것 같습니다.

2021-03-10 07:30 UTC, Vallista commented on src/js/search/SearchController.js
> +export default class SearchController {
전반적으로 class로 잘 짜주셨습니다!

다만, SearchController 내부에서만 쓰이는 메서드와 외부에 노출될 메서드의 정렬 순서, 구분등이 있었으면 좋겠습니다!

2021-03-10 07:30 UTC, Vallista commented on src/js/templates/videoClipTemplate.js
> +function getSrcDocTemplate(item) {
정적인 템플릿을 가져와 쓰는 것 이므로, get은 필요없지 않을까요? method상에서 get은 객체의 데이터에 접근하기위해 사용하는 경우가 많은데, 해당 경우에는 굳이 get 네이밍을 선택할 필요가 없어보입니다!

2021-03-10 07:57 UTC, Tanney-102 commented on src/js/search/SearchEventBinder.js
> +    const searchKeyword = e.target.elements["search-keyword"].value;
와우~! 상수화할 때 Object.freeze를 쓰는 방법이 있었군요!!
2단계때 고려해봐야겠습니다 ㅎㅎ

form 내부의 요소를 가져오는 로직을 dom.js에 함수로 추상화하며 예외처리를 하는 로직까지 추가했습니다 ㅎㅎ
id와 class를 전부 상수화하면 좋겠지만....이것도 대공사가 될 것 같아 우선 순위에서는 뒤로 미루는 것이 좋다고 판단했습니다 ㅎㅎ

commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/b7369700427f4e83b279c23a7f8e96aada009877

2021-03-10 08:02 UTC, Tanney-102 commented on src/css/ui/modules/chip.css
> +  justify-content: space-between;
헐 이렇게 중구난방으로 써놓다니ㅜ 저 원래 이런 사람 아닙니다ㅜㅜㅜㅜㅜㅜ 수정했습니다ㅜ
commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/61cbe29c8d406bb7995fa23f0db836a5d74f9d72

2021-03-10 08:06 UTC, Tanney-102 commented on src/js/queries/searchQuery.js
> +  return `part=snippet&key=${YOUTUBE_API_KEY}&q=${keyword}&maxResults=${VIDEOS.SEARCH_MAX_RESULT}&${pageTokenQuery}`;
생각해보니 pageToken 없는 경우 항상 빈 문자열이 온다는 보장이 없군요! 
안전하게 삼항 연산자로 수정했습니다.
commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/d00f2d6d0bd1176d7ff1c6e51d284a31d2e6f1ab

2021-03-10 08:18 UTC, Tanney-102 commented on src/js/search/SearchController.js
> +export default class SearchController {
내부에서만 사용하는 메서드들은 위쪽에, 외부에 노출되는 메서드들은 관련 있는 것들끼리 정렬하여 아래쪽에 배치하였습니다.

commit link : https://github.com/woowacourse/javascript-youtube-classroom/pull/13/commits/de921b825ffe6e2d6e814852bfc62878bae3874f

2021-03-10 08:33 UTC, Tanney-102 commented on src/js/templates/videoClipTemplate.js
> +function getSrcDocTemplate(item) {
~~Template.js 내부나 ~~View.js에서 각 템플릿들을 가져와 쓰는 것으로 생각해 get~~ 네이밍을 사용했습니다. 이전에도 get prefix를 getter에 쓰는 경우가 많다는 이야기를 들었기에 처음 네이밍을 하던 시점에도 망설이긴 했지만 아무리 생각해도 'get'을 해오는 게 아닌가? 하는 생각이 듭니다. 더 적절한 네이밍이 생각나지 않네요. ㅜㅜ

그리고 그냥 문자열만을 리턴하는 경우라면 상수로 선언할 수도 있겠지만 인자를 받아 동적으로 생성해야하는 경우가 있어 더욱 고민이 됩니다. 

혹시 이렇게 외부에서 template을 만들어 가져오는 게 일반적인 방법이 아닌 것인지, 이렇게 가져오는 경우가 종종 있다면 그 때는 보통 어떻게 네이밍을 하는지 궁금합니다. 참고할만한 것이 있을까요..?

2021-03-13 06:51 UTC, merged