[2단계 - 나만의 유튜브 강의실] 소피아(전소이) 미션 제출합니다.
woowacourse/youtube-classroom pull request #136
Opened 2022-03-19 10:38 UTC by soyi47

작성 중입니다.

2022-03-19 19:09 UTC, lsw1164 requested changes
소피아님, 코드 잘봤습니다 :)

> 1. 테스트에 대하여

cypress open 과 cypress run의 차이는 무엇일까요? 
소피아님과 비슷한 이슈를 겪은 사례를 찾아봤습니다
https://github.com/cypress-io/cypress/issues/5318#issuecomment-540918042

> 2. 구조 변경, 이벤트에 대하여

말씀하신대로 변경한 구조가 더 심플하다고 느꼈습니다. 하지만 View가 유저로부터 이벤트를 받고 랜더링의 역할만 하도록 설계하고 싶으시다면... View와 Manager를 이어줄 무언가가 필요하겠습니다. ㅎㅎ 제 의견은 소피아님이랑 같네요. 지금 구조도 장단점이 있고 다른 구조도 장단점이 있습니다. 정답은 없습니다. 상황에 따라 다른 구조를 택해야겠습니다. 

프로토타입이거나 프로덕션이라도 변경 요청이 별로 없는 부분이라면 확장성을 포기하고 최대한 단순한 구조를 유지할 것입니다. 

프로덕션 레벨이고 변경이 잦은 부분이라면 확장성을 고려해서 복잡해지더라도 유연한 설계를 취할 것입니다.
 
이번 미션을 통해 설계에 대해 여러 시도와 고민을 해보셨을 거 같습니다. 생각하신 설계를 코드로 구현해보고 장단점을 체감하신 거로 충분히 성공적인 미션이라 생각합니다 👍 

> 3. 영상 저장 방식에 대하여

다른 서비스에서는 캐시 데이터를 어떻게 관리하고 있을지 리서치해보면 아이디어를 얻는 데 도움이 될 거 같습니다 :)

2022-03-19 19:09 UTC, lsw1164 commented on cypress/tests/youtubeClassroom.spec.js
> +  const baseURL = 'http://localhost:9000/';
cypress config로 baseUrl 관리할 수 있습니다 :)

https://docs.cypress.io/guides/references/configuration#cypress-json

2022-03-19 19:09 UTC, lsw1164 commented on __tests__/unit/storage.spec.js
> +    expect(JSON.parse(localStorage.getItem('videos')).find((video) => video.id === newVideo.id)).toBeTruthy();
'영상 정보를 저장한다'는 어디에 저장한다는 정보가 없습니다. 
localStorage에서 getItem으로 videos를 가져오는 게 검증 방법으로 적절할까요?

2022-03-19 19:09 UTC, lsw1164 commented on __tests__/unit/storage.spec.js
> +describe('Storage 기능 테스트', () => {
file 이름에 포함된 spec, test 구분 기준이 어떻게 되나요?

2022-03-19 19:09 UTC, lsw1164 commented on cypress/tests/youtubeClassroom.spec.js
> +        expect(alertStub).to.be.called;
alert에 어떤 메세지가 나오는지 검증하려면 어떻게 해야 될까요?

2022-03-19 19:09 UTC, lsw1164 commented on src/js/constants.js
> +}
적절히 상수로 빼셨군요 👍

2022-03-19 19:09 UTC, lsw1164 commented on src/js/View/SearchResultView.js
> +    if ( result === 'SUCCESS' ) {
result 값도 공통적으로 쓰인다면 상수로 빼도 좋을 거 같습니다

2022-03-19 19:09 UTC, lsw1164 commented on src/js/View/SearchResultView.js
> +    $('#modal-container').addEventListener(EVENT.UPDATE_SEARCH_STATE, this.updateOnSearchState);
bindEvents 메서드는 지우셨네요? 개인적으로 함수로 잘 추출했다고 생각했습니다. 
로직을 constructor 내부로 합친 이유가 있나요?

2022-03-19 19:09 UTC, lsw1164 commented on src/js/Storage.js
>  const getData = (key) => JSON.parse(localStorage.getItem(key));
JSON.parse은 Exception이 발생할 수 있습니다. 어떻게 처리하면 좋을까요?

2022-03-19 19:09 UTC, lsw1164 commented on src/js/Manager/SearchVideoManager.js
> +    return fetch(generateFetchURL(this.#keyword, this.#nextPageToken))
web api 호출은 별도 파일로 분리하는 게 어떨까요? api라는 폴더를 만들어서 관리하면 좋을 거 같습니다.

2022-03-19 19:09 UTC, lsw1164 commented on src/js/Manager/SearchVideoManager.js
> +      saved: !!this.storage.findVideoById(item.id.videoId),
bool 형태로 변경해주는군요 👍

2022-03-20 06:51 UTC, soyi47 commented on __tests__/unit/storage.spec.js
> +describe('Storage 기능 테스트', () => {
test로 통일하려고 했는데, cypress가 추가되면서 섞어 쓴 것 같네요. test로 통일하겠습니다.

2022-03-20 06:55 UTC, soyi47 commented on __tests__/unit/storage.spec.js
> +    expect(JSON.parse(localStorage.getItem('videos')).find((video) => video.id === newVideo.id)).toBeTruthy();
storage.saveVideo 자체가 제대로 동작했는지 확인하려면, 직접 localStorage를 확인해야 한다고 생각해 이렇게 작성했습니다. storage.findVideoById를 사용하면, findBideoById에 대한 테스트가 된다고 생각하여 테스트 케이스를 나누었는데요.
1. saveVideo 기능 확인 : storage.saveVideo 후 localStorage에서 데이터 확인 결과가 조건에 맞아야 함
2. findVideoById 기능 확인 : storage.saveVideo 후 findVideoById 결과가 조건에 맞아야 함
storage.saveVideo를 확인하는 다른 검증 방법이 있을까요?

2022-03-20 07:43 UTC, soyi47 commented on src/js/View/SearchResultView.js
> +    $('#modal-container').addEventListener(EVENT.UPDATE_SEARCH_STATE, this.updateOnSearchState);
bindEvents를 함수로 잘 추출했다고 생각하신 이유가 있으실까요?

step2를 시작하면서 보니, 제가 bindEvents 메서드 추출을 해둔 곳도 있고 안 해둔 곳도 있더라고요.

1. 우선 이벤트 핸들러 세팅이 있는 곳은 전부 메서드로 추출하거나, 아니면 constructor에 합치거나, 일관성 있게 둘 중 하나로 통일해야겠다 싶었습니다.
2. 전체적으로 커스텀 이벤트가 줄면서 addEventListener 라인이 많이 줄었고, (view 클래스 내 3줄 이하) 그렇다면 줄바꿈으로 내부에서 문맥을 구분해주면 가독성 면에서도 충분하지 않나 싶어서
3. 메서드로 추출하더라도 재호출될 일은 없어서

위와 같은 이유로, constructor에 합치는 방향으로 통일했습니다.

메서드로 추출하면 constructor 내부의 가독성이 조금 더 좋아지는 면이 있는 것 같아서 추출을 했었는데, 
addEventListener 라인 수가 줄어드니까 constructor 내부에 작성해도 괜찮겠다고 생각한 것이 가장 큰 이유입니다.

2022-03-20 14:59 UTC, lsw1164 commented on src/js/View/SearchResultView.js
> +    $('#modal-container').addEventListener(EVENT.UPDATE_SEARCH_STATE, this.updateOnSearchState);
네, 메서드로 추출하면 의도를 파악하기 쉬워서 잘 추출했다고 생각했습니다. 
메서드의 이름을 잘 지어 놓으면 여러 줄 로직을 써놓은 거보다 의도를 전달하기 쉽습니다.

그럼 constructor에서 무슨 일들을 하는지 더 쉽게 파악하기 좋겠죠.
constructor 내부에서 이벤트 등록하는 일을 하겠다는 의도를 전달하는 게 더 중요하다고 생각했습니다. 
어떤 어떤 객체들에 addEventListener를 하는지는 그 의도 내부에 숨겨진 디테일이죠

함수는 반드시 코드 재사용만을 위해 쓰는 건 아닙니다. 
세부 사항을 숨기면서 의도를 잘 드러내고 싶을 때도 사용합니다.

2022-03-20 19:04 UTC, soyi47 commented on __tests__/unit/storage.spec.js
> +describe('Storage 기능 테스트', () => {
test로 통일하여 수정했습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/99b4af623d2007c0fca1d60b60451093580c0b64

2022-03-20 19:05 UTC, soyi47 commented on cypress/tests/youtubeClassroom.spec.js
> +  const baseURL = 'http://localhost:9000/';
config를 잘 활용하는 게 좋겠네요. 감사합니다. 수정했습니다! https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/c17e5a0103b378c00a394e754fbaef565ddcf2d9

2022-03-20 19:14 UTC, soyi47 commented on cypress/tests/youtubeClassroom.spec.js
> +        expect(alertStub).to.be.called;
`calledWith`를 이용하여 메세지를 확인하도록 수정했습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/9a8bb6f3a331a353b6304eaf7052c38629cbb386

찾아보면서 cy.stub()를 사용하는 다양한 방법들을 훑어볼 수 있었습니다. 😊
https://docs.cypress.io/api/commands/stub#Yields
https://docs.cypress.io/guides/references/assertions#Sinon-Chai

2022-03-20 19:17 UTC, soyi47 commented on src/js/View/SearchResultView.js
> +    if ( result === 'SUCCESS' ) {
상수로 빼서, 메서드 결과로 돌려줄 때 혹은 결과를 확인할 때 사용하도록 수정했습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/c582cb567e4a7f5016e7e38007b9fe03c0303804

2022-03-20 19:35 UTC, soyi47 commented on src/js/Storage.js
>  const getData = (key) => JSON.parse(localStorage.getItem(key));
피드백 덕분에 JSON.parse에서 왜 에러가 생기는 지 간단히 알아볼 수 있었습니다.
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Errors/JSON_bad_parse

변환하기에 유효하지 않은 문자열이 주어지면 에러가 발생한다고 알게 되었습니다.
유효하지 않은 원인을 확인하고 고칠 방법까진 떠오르진 않아서, 저장된 데이터를 불러오는 과정에서 문제가 있었음을 사용자가 알아볼 수 있도록 처리해봤습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/dd48e885d637c303c93ebcdbf633c0bb19a3fce3

1. Storage - 처음 localStorage의 video 정보를 불러오는 과정에서 JSON.parse 에러 발생 시 video 값을 배열이 아닌 문자열 'ERROR'를 저장하도록 했습니다.
2. SaveVideoManager - 저장된 비디오 리스트 view 업데이트를 위한 이벤트를 발행할 때, video 값이 배열인지 확인하여 response 값으로 'SUCCESS', 혹은 'FAIL'을 함께 보냅니다.
3. SavedVideoListView - 저장된 비디오 리스트를 업데이트하기 전에, 받은 response 값을 확인합니다. 'SUCCESS'가 아닌 경우, 저장된 비디오를 가져오는데 실패했다는 내용의 안내 문구를 업데이트합니다.

2022-03-20 19:37 UTC, soyi47 commented on src/js/Manager/SearchVideoManager.js
> +    return fetch(generateFetchURL(this.#keyword, this.#nextPageToken))
'youtubeAPI'라는 파일로 분리했습니다. 
이 로직들은 다른 프로그램에서도 재사용될 수 있을 것 같아서, 파일은 util 폴더 하위에 넣어줬습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/dbe00dfac072fcde9b8cdd979ce642d5e0b76d52

2022-03-21 05:23 UTC, soyi47 commented on src/js/View/SearchResultView.js
> +    $('#modal-container').addEventListener(EVENT.UPDATE_SEARCH_STATE, this.updateOnSearchState);
constructor에서 호출하는 메서드만 보고도 해당 클래스가 어떤 역할을 바로 확인할 수 있도록, 클래스를 작성한 의도와 클래스의 역할을 드러내는 것이 중요하다는 말씀으로 이해했습니다.
메서드로 추출하여 의도를 파악하기 쉽도록 만들 수 있다는 점을 제가 놓친 것 같네요.

말씀을 듣고 보니 이 부분은 수정하는 것이 좋겠다고 생각해 bindEvents 메서드를 다시 추출했습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/52e0d1df6f222a6aa0404436eb4d0b7ab0fcc223
initDOMs 메서드도 함께 추출해주었습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/bf87b45f721b496242a3381b5b093b2f1e87f66d

추출해주니 View가 어떤 역할을 하는지 확실히 잘 드러나는 것 같아 좋네요.  👍

2022-03-21 05:54 UTC, soyi47 commented
안녕하세요, 리트님! 😄

피드백 잘 읽었습니다. 
말씀 주신대로 구조에는 정답이 없고, 각각 여러 장단점이 있으니 여러 상황을 고려해서 설계하도록 신경써보겠습니다. 
다양한 상황에서의 구조 설계 경험이 필요할 것 같은데, 앞으로 미션 진행하면서 계속해서 경험해볼 수 있으리라 생각합니다. 

bindEvent 메서드 추출에 대한 말씀 확인하여 적용하였고,
Storage 기능 검증 방법에 대해 코멘트로 질문 남겨뒀습니다. 확인해주시면 감사하겠습니다. 👍

코멘트 달아주신 부분에 대한 수정 사항은 커밋 링크와 함께 코멘트 달아뒀습니다.

그 외에 수정 사항은 아래에 정리했습니다.

1. 테스트 실패 케이스 수정
테스트가 실패하는 문제에 대한 비슷한 사례 공유 감사합니다. 🙇‍♀️
공유해주신 이슈에서 then 이후 sholud를 체이닝하는 것이 문제가 된다는 내용 확인했습니다. 

    제 코드에서는 then을 사용하지 않아서,,, 정확히 무엇이 문제였는지는 잘 모르겠네요. 😂
아래와 같이 수정을 했더니 지금은 테스트 케이스가 통과합니다.

    기존에는 `within`을 사용하여 search-result-video-list 내부에서 skeleton을 가져오도록 했습니다.
현재는 `within`을 제거하고 `cy.get('.skeleton')...`을 밖으로 옮겼고, `cypress run`에서도 테스트 케이스가 통과합니다.
    ```
    cy.get('#search-result-video-list').within(() => {
        cy.get('.skeleton').should('have.length', 10).and('be.visible');
    });
    ```
    

2. 영상 카드의 저장 버튼과 ✅ , 🗑️ 아이콘 버튼에 대한 테스트 케이스를 추가했습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/0ee11eb7e796b9dcd843a790ab8639496a4e4dfb

3. 위의 테스트 케이스를 작성하면서, 버튼 선택자를 id로 준 것을 발견하고, class로 변경해줬습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/aa164e575f5eeae0487c94033f2c8f040ab63721 https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/a8a43de9a5e8700cbad41c5990c861a3cb851d23

4. 모바일 반응형 추가 구현
데모 페이지를 모바일로 들어가봤더니 UI가 엉망이더군요. 😂
이하 범위도 하면 좋을텐데, 시간 상 width 400px 이상까지 자연스럽도록 css를 추가해줬습니다. https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/b996a7b67d4cad9ce233ccd0785e5b3bb257c447 https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/8f9ec8c0588b58ded396d2937076ce010ebd8813
현재 제 휴대폰에서는 아래와 같은 화면이 나옵니다.

5. 서비스 캐시 관리는 다른 곳의 사례만 간단히 알아봤습니다.
https://toss.tech/article/smart-web-service-cache
HTTP 응답에 캐시 유효 기간을 설정할 수 있네요. 
아직 HTTP 통신에 대해 잘 몰라서, 조금 더 공부해보고 다음에 적용해보겠습니다!

의견 주시면 추가로 적용해보겠습니다.
감사합니다. 좋은 하루 되세요! 😊

2022-03-21 15:59 UTC, lsw1164 commented on __tests__/unit/storage.spec.js
> +    expect(JSON.parse(localStorage.getItem('videos')).find((video) => video.id === newVideo.id)).toBeTruthy();
> storage.saveVideo가 제대로 동작하는지 확인하는 다른 검증 방법이 있을까요?

saveVideo 전에는 findVideoById로 찾을 수 없다가 saveVideo 후에 findVideoById로 찾을 수 있으면  
video가 save 됐는지 알 수 있습니다 :)
그럼 나중에 localStorage를 안쓰도록 내부 구현이 바뀌더라도 테스트를 수정하지 않아도 되겠군요.

2022-03-21 16:11 UTC, lsw1164 commented on src/js/Storage.js
>  const getData = (key) => JSON.parse(localStorage.getItem(key));
> 1. Storage - 처음 localStorage의 video 정보를 불러오는 과정에서 JSON.parse 에러 발생 시 video 값을 배열이 아닌 문자열 'ERROR'를 저장하도록 했습니다.

하나의 Function에서 서로 다른 타입을 반환할 이유가 있을까요?

getLocalStorageVideos라는 네이밍에서 'ERROR'라는 문자열이 반환되는 건 예상하기 어렵습니다.
이럴 때 두 가지 중 하나 선택해 볼 수 있을 거 같습니다.
- 빈 배열을 반환하면서 console error 로그 남기기
- 함수 사용부에서 처리할 수 있도록 커스텀 Error throw

2022-03-21 16:56 UTC, soyi47 commented on src/js/Storage.js
>  const getData = (key) => JSON.parse(localStorage.getItem(key));
이 부분은 계속 고민 중이었는데, 먼저 짚어주셔서 감사합니다!
갑자기 문자열을 반환하는 부분은 저도 아쉬워서 고치고 싶었는데, 
다른 방법이 생각나지 않아 우선 저렇게 작성했습니다..! 😂

가장 처음에는 custom Error를 throw하고 싶었습니다. 데이터가 필요할 때마다 localStorage에서 데이터를 읽어오도록 하고 싶지 않아서, Storage에서 한번 읽어오면 멤버 변수 videos로 읽어온 값을 들고 있고, 이를 외부에서 get으로 읽어서 사용하도록 구현해뒀는데, 그러다보니 custom Error를 Throw하지 못 하게 되더라고요. 그 상황에서 Error 상태임을 남겨두고 싶어 문자열을 사용하게 되었고요..!

https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/3810f11175cda2d16ff6508b7f884523c3810218
제안해주신 첫 번째 방법 빈 배열 반환 + console.error로 로그 남기기를 이용하여 수정해봤습니다. 
또 Storage에 멤버 변수 status를 추가하여, Storage가 초기에 localStorage 데이터를 읽어오는데 성공했는지를 나타내는 문자열 ('SUCCESS' 또는 'FAIL')을 가지고 있도록 했습니다. Manager에서는 이 status 값을 response로 넘기도록 고쳤고, View에서 해당 값을 확인하여 안내 메세지를 사용자에게 보여줍니다.

2022-03-21 17:04 UTC, soyi47 commented on __tests__/unit/storage.spec.js
> +    expect(JSON.parse(localStorage.getItem('videos')).find((video) => video.id === newVideo.id)).toBeTruthy();
아하..!
'테스트 검증이 내부 구현에 의존하지 않도록 작성하면, Storage가 localStorage를 다른 걸로 바꿔 사용하게 되어도 테스트 케이스는 그대로 사용할 수 있도록 할 수 있다.'는 말씀으로 이해했습니다. 맞나요?

제가 너무 기능 자체를 확인하는 것에 집중했던 것 같습니다. 말씀하신대로 수정해봤습니다! https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/f61361fc105b3b7404f6bb418d274200ec75839c

그렇다면 궁금한 점이 하나 생기는데, 테스트 명세에 localStroage라는 표현을 추가하는 것도 별로 좋은 방식은 아닌 건가요? 아니면 지금은 localStorage에 저장하는 역할을 하니까 넣어주는 것이 맞을까요?

2022-03-21 17:58 UTC, lsw1164 commented on __tests__/unit/storage.spec.js
> +    expect(JSON.parse(localStorage.getItem('videos')).find((video) => video.id === newVideo.id)).toBeTruthy();
localStroage로 구현했다는 내용을 외부에 노출할 필요가 없다면 localStroage 라는 표현은 안써도됩니다 :)

2022-03-21 19:04 UTC, soyi47 commented on __tests__/unit/storage.spec.js
> +    expect(JSON.parse(localStorage.getItem('videos')).find((video) => video.id === newVideo.id)).toBeTruthy();
> '영상 정보를 저장한다'는 어디에 저장한다는 정보가 없습니다.
localStorage에서 getItem으로 videos를 가져오는 게 검증 방법으로 적절할까요?

처음에 위 리뷰의 첫 문장이 어디에 저장하는지 명세에 명시해달라는 의미로 이해했어요. 이후 다시 주신 리뷰를 보니, 첫 문장도 내부 구현을 노출하지 않는 게 좋겠다는 말씀이셨던 게 보이네요. 제가 이해가 느렸습니다. 🤣

명세도 다시 수정했습니다! https://github.com/woowacourse/javascript-youtube-classroom/pull/136/commits/32e99af3054bd3221fd61b4fef70536c52edce21

2022-03-22 12:20 UTC, lsw1164 approved these changes
소피아님, 피드백 잘 반영해주셨네요👍
수정 내역도 상세하게 기술해주셔서 이해하는 데 좋았습니다  :) 
Approve 하겠습니다!

2022-03-22 12:20 UTC, merged

2022-03-22 16:34 UTC, soyi47 commented
제 생각을 공유하려고 하다 보니, 너무 길게 적은 건 아닌가 싶어요.. 😂 이해하는데 도움이 되었다니 다행입니다!
꼼꼼한 리뷰 감사합니다! 다음에 기회가 되면 또 뵙겠습니다. 😎

2022-03-22 16:44 UTC, lsw1164 commented on __tests__/unit/storage.spec.js
> +    expect(JSON.parse(localStorage.getItem('videos')).find((video) => video.id === newVideo.id)).toBeTruthy();
아닙니다ㅎ... 여러 생각을 해볼 수 있게(?) 의도적으로 애매하게 말해봤습니다😅