[1단계 - 나만의 유튜브 강의실] 엘라(김현주) 미션 제출합니다
woowacourse/youtube-classroom pull request #14
Opened 2021-03-06 04:00 UTC by HyuuunjuKim

안녕하세요 ㅎ ㅎ 이번에 @jho2301, @GwangYeol-Im 와 `나만의 유투브 강의실` 미션을 진행한 엘라입니다.😁

데모 페이지: https://classroom-mission.firebaseapp.com/

## ✨기능 구현 목록
- [x] 유튜브 검색 모달에서, 검색을 하면 동영상 리스트(10개)를 불러온다.
  - [x] 결과 노출 전까지 skeleton UI를 보여준다.
  - [x] 스크롤 시, 추가로 동영상 리스트 10개를 보여준다.
  - [x] 결과가 없을 경우, 결과 없음 이미지를 보여준다.
- [x] 검색한 영상의 저장 버튼을 누르면 볼 영상 리스트에 추가된다.
  - [x] 이미 저장된 영상은 검색결과에서 저장 버튼이 나타나지 않는다.
  - [x] 저장 가능한 최대 동영상 갯수는 100개이다.
- [x] 검색 모달에 다시 접근했을 때, 가장 마지막에 검색한 키워드로 검색한 결과를 보여준다.
- [x] 최근 검색 키워드를 3개까지 화면상에 검색창 하단에 보여준다.

잘 부탁 드리겠습니다.🐣

2021-03-07 14:18 UTC, HyeonaKwon requested changes
안녕하세요! 유튜브 강의실 미션의 리뷰어인 HyeonaKwon 입니다 :)

우선 전체적인 코드에 대해 살짝 의견을 드리자면,
1. state 는 데이터를 저장하고 관리하는 역할이라고 생각이 드는데요, state 가 viewController 의 함수를 직접 호출하는게 조금 어색해보입니다. 역할을 확실히 정하는건 어떨까요?
2. localStorage 에 접근하는 코드가 흩어져 있는데요, 값이 없을 때의 예외처리와 함께 localStorage 관련한 코드를 모아 한곳에서 관리해보는건 어떨까요?

두번째로 UI, UX 개선점으로는
1. 모달이 너무 화면 위와 아래까지 꽉 차있네요. 마진을 두는건 어떨까요?
2. 동영상 저장을 눌렀을 때 아무런 액션이 없어서 어떻게 되는건지 모르겠어요! 얼럿, 스낵바같은 액션을 추가해보는건 어떨까요?
3. 모달 딤드 영역의 클릭이벤트 처리도 추가되었으면 좋겠어요!

세번째로 질문주신 내용 피드백 드리자면,
1. 저는 가독성을 위해 return 전에 라인을 추가하는 편입니다. 취향이겠지만 라인을 추가하는게 좋을 것 같아요!
2. 개인적인 의견으로는 data- 방법이 더 나아보이는데요! article 자체에 클릭이벤트를 달았어도 나쁘지 않았을 것 같네요!

미션 수행하느라 고생하셨습니다 👍

2021-03-07 14:18 UTC, HyeonaKwon commented on src/js/viewControllers/app.js
> +export { openModal, closeModal, renderSavedVideoList };
왜 파일명이 app.js 여야 하나요??

2021-03-07 14:18 UTC, HyeonaKwon commented on index.html
> +              id="video-search-submit"
id 값은 -button 이 좋지 않을까 싶네요!

2021-03-07 14:18 UTC, HyeonaKwon commented on src/js/handlers/moreVideoLoading.js
> +  this.observe($newLastVideo);
`this.disconnect()` 와 `this.observe()` 는 이 함수가 `intersectionObserver` 내부에서 bind(this) 를 통해서 사용하기 때문에 this.~~() 로 사용한 것으로 추측되는데요! 이렇게 하면 헷갈릴 수 밖에 없어보입니다. handlerMoreVideoLoading 내부만 보면 두 함수가 존재하지 않기 때문에 왜 호출하지? 하는 생각이 들어요!

2021-03-07 14:18 UTC, HyeonaKwon commented on src/js/library/states/latestKeywords.js
> +    localStorage.setItem('latestKeywords', JSON.stringify(this.latestKeywords));
latestKeywords 도 상수화하면 좋곘네요!

2021-03-07 14:18 UTC, HyeonaKwon commented on src/js/library/states/videoInfos.js
> +    const videoInfos = JSON.parse(localStorage.getItem('videoInfos')) ?? [];
21라인의 객체 이름과 겹쳐서 헷갈립니다! 변수명 수정해주세요~

2021-03-08 05:06 UTC, HyuuunjuKim commented
1. state 는 데이터를 저장하고 관리하는 역할이라고 생각이 드는데요, state 가 viewController 의 함수를 직접 호출하는게 조금 어색해보입니다. 역할을 확실히 정하는건 어떨까요?

- 이 질문에 대한 질문이 있습니다😁 저희는  state의 상태가 add되고 set됨에 따라서 view가 같이 반응해서 바뀌는 식으로 코드를 짜보았는데요. 이렇게 하면 불필요한 중복의 코드가 줄어들 수 있다고 생각했습니다. 혹시 리뷰어님께 저희의 의도가 불명확하게 전달됐을까요???😂😂😂

2021-03-08 05:35 UTC, HyuuunjuKim commented on src/js/viewControllers/app.js
> +export { openModal, closeModal, renderSavedVideoList };
컴포넌트 단위로 뷰를 나누어 보았을 때 최상단에 위치하는 컴포넌트가 app이라고 생각했습니다. 약간 메인페이지와 모달을 분리하기 위함이랄까요,,?,,,,,🤨🤨🤨 혹시 추천하시는 다른 네이밍이 있을까요??

2021-03-08 05:42 UTC, HyuuunjuKim commented on index.html
> +              id="video-search-submit"
저희는 form태그 안에 button의 type이 submit이라서, id값에 `-submit`으로 하였는데요! 

![image](https://user-images.githubusercontent.com/43339385/110279390-67921a80-801c-11eb-859c-b55c7dbcaf54.png)

cypress test code 내에서도 submit하는 button을 click하는게 조금 더 명시적일거라고 생각했습니다.

button tag이면 `-button`으로 통일하는게 나을까요??

2021-03-08 08:15 UTC, HyuuunjuKim commented on src/js/handlers/moreVideoLoading.js
> +  this.observe($newLastVideo);
이 부분에서 저희도 많은 얘기를 나누었는데요!!! this로 바인딩을 안해주니, 순환참조가 생겨서 일단 this로 바인딩을 하면서 순환참조를 제거하였습니다. ㅎ ㅎ 그런데 this로 바인딩을 하니 확실히 handlerMoreVideoLoading 내부에 두 함수가 없어서 약간 의문이 생길 수 있는 코드인 것 같네요😂😂😂

그래서 리뷰어님의 피드백을 보고 `src/js/handlers/moreVideoLoading.js`의 일부를 다음과 같이 변경해 보았습니다.
```javascript
const intersectionObserver = this;

intersectionObserver.disconnect();
intersectionObserver.observe($newLastVideo);
```

이런식으로 코드를 가져가는 방향은 어떨까요??🐣🐣🐣

2021-03-08 08:16 UTC, HyuuunjuKim commented on src/js/library/states/latestKeywords.js
> +    localStorage.setItem('latestKeywords', JSON.stringify(this.latestKeywords));
```javascript
const LATEST_KEYWORDS = 'latestKeywords';
const VIDEO_INFOS = 'videoInfos';

export { LATEST_KEYWORDS, VIDEO_INFOS };
```

위처럼 localStorage 내 key 값들을 상수화 시켜주었습니다. 디테일한 지적 감사합니다👍👍👍

2021-03-08 08:18 UTC, HyuuunjuKim commented on src/js/library/states/videoInfos.js
> +    const videoInfos = JSON.parse(localStorage.getItem('videoInfos')) ?? [];
앗 이 부분을 체크하지 못했네요 ㅠ ㅠ 페이지를 reload할 때 기존 정보의 최신화 된 값을 가져오는 코드여서

```javascript
async init() {
  const oldVideoInfos = getLocalStorage(VIDEO_INFOS) ?? [];
  const latestVideoInfos = await updateVideoInfos(oldVideoInfos);

  this.set(latestVideoInfos);
},
```

위처럼 변경하였습니다. 감사합니다😁😁😁

2021-03-08 08:25 UTC, HyuuunjuKim commented
UI, UX 관련해서 주신 피드백을 잠시 뒤로 미루고 다른 피드백에 대해 반영 및 질문을 남겼습니다.🤩

페어들과 2단계까지는 코드를 동일하게 가져가기로 하여서, 현재 페어들과 UI, UX 관련 피드백을 정리하고 있습니다 ㅎ ㅎ 내일즈음에 UI, UX까지 수정하여서 다시 피드백 요청 드리겠습니다. 감사합니다 ❗❗❗

2021-03-10 15:21 UTC, HyeonaKwon commented on src/js/handlers/moreVideoLoading.js
> +  this.observe($newLastVideo);
음 그냥 this 를 변수로 선언한 차이밖에 없어서.. 여전히 어색해보여요😭
아예 intersectionObserver 의 내부함수로 만드는건 어떠세요?

2021-03-10 15:23 UTC, HyeonaKwon commented on src/js/viewControllers/app.js
> +export { openModal, closeModal, renderSavedVideoList };
음 그렇다기보단 app 파일에 있는 함수들은 searchModal 에 있어도 될 것 같은데, app 으로 뺀 이유가 궁금했어요 :)

2021-03-10 15:23 UTC, HyeonaKwon commented on index.html
> +              id="video-search-submit"
-submit 으로 끝나면 submit form 인지 submit button 인지 불분명한 느낌이 드는 것 같아요! -submit-button 은 별로일까요~?

2021-03-10 15:28 UTC, HyeonaKwon commented
>저희는 state의 상태가 add되고 set됨에 따라서 view가 같이 반응해서 바뀌는 식으로 코드를 짜보았는데요. 이렇게 하면 불필요한 중복의 코드가 줄어들 수 있다고 생각했습니다. 이러한 방향으로 코드를 가져가는 것보다는 state는 딱 state 관련 정보만 관리하는 편이 나을까요?😮😮😮 혹시 그렇다면 조금 구체적인 이유가 궁금합니다❗

state 는 말 그대로 상태인데요, 상태를 저장하고 관리하는 역할만 했으면 좋겠어요! 이외의 뷰를 바꾼다거나 로직을 수행하는 것은 state.set() 을 호출한 사용처에서 이후 작업을 진행하면 역할분리가 확실할 것 같습니다 👍

2021-03-11 04:31 UTC, HyuuunjuKim commented on index.html
> +              id="video-search-submit"
아하,,,그럴 수 있겠네요 ㅠ ㅠ submit form이랑 충분히 헷갈릴 수 있을 것 같아요. 그 부분을 캐치하지 못했네요 😂
바로 위 input tag는`-input`이라고 해놓았네요 허허🤣 현아님 피드백대로 id에 `-button`이 들어가도록 수정했고, `submit`이 꼭 안들어가도 `button`이라는 단어만으로 충분한 것 같아서 다음과 같이 수정했습니다 ㅎ ㅎ감사합니다 ❗

```html
<button
  id="video-search-button"
  type="submit"
  class="btn bg-cyan-500"
  name="video-search-button"
>
```

2021-03-11 07:11 UTC, HyuuunjuKim commented on src/js/handlers/moreVideoLoading.js
> +  this.observe($newLastVideo);
허허,,,,원래 하나였던 파일을 두개로 분리하였는데, 뭔가 분리하기에는 조금씩 애매한 부분이 계속 생기는 것 같네요 🤦‍♂️ 고민고민하다가, 현아님 피드백대로 states/intersectionObserver의 내부함수 `moreVideoLoad()`로 추가하였습니다 🥰🥰🥰 

이렇게 이동시키니 개인적으로는 intersectionObserver가 더 많은 비디오 로딩을 해주는 주체(?)가 된 느낌이 들어서 훨씬 좋은 것 같습니다! 혹시 현아님 생각은 어떠신가요?

한번만 더 확인 부탁드리겠습니다.🌻

2021-03-11 08:05 UTC, HyuuunjuKim commented
ㅎ ㅎ 답변 해주셔서 감사합니다🥰 

state는 말 그대로 **상태**이니 상태의 변경사항과 관련된 역할만 내부에 위치시키는게 더 좋은 방향이 될 것 같습니다. 
handler -> state -> view의 흐름 보다는 state <- handler -> view의 흐름으로 가도록 앞으로 의식하면서 코드를 작성해야겠네요!

변경된 코드 확인 부탁드리겠습니다~!!!!

2021-03-11 08:48 UTC, HyeonaKwon approved these changes
넵 좋네요! 아니면 state 에서 callback 인자를 받아서 state 를 변경한 후에 callback 을 실행시켜도 좋을 것 같아요! callback 내용을 state 가 직접 가지고 있는 것은 아니니까요ㅎㅎ
코멘트 남긴 함수명은 2단계에서 고려해주세요! 고생하셨습니다 👍

2021-03-11 08:49 UTC, merged

2021-03-11 08:49 UTC, HyuuunjuKim commented
오잉 `handleMoreVideoLoad()`에서 가져오면서  앞에 handle만 지워버렸네요 ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ 저도 함수 네이밍에서 동사를 앞으로 옮기는거에 아주아주 동의합니다 ㅎㅎㅎ 수정하였습니다~!