[2단계 - 나만의 유튜브 강의실] 콤피(류현승) 미션 제출합니다.
woowacourse/youtube-classroom pull request #141
Opened 2022-03-19 14:22 UTC by compy-ryu

안녕하세요, 로이님...!
고생 많으십니다!

지난 피드백에 이어 이번 단계에서도 잘 부탁드립니다! 🙇‍♂️

### [🚀 데모 페이지](https://compy-ryu.github.io/javascript-youtube-classroom/)

## 지난 단계에서 변경된 부분
### Store 클래스 구조 관련
피드백을 받은 후 1단계 막바지에서 Store 클래스를 추상 클래스로 활용하는 것이 아닌
인스턴스 클래스로 활용하여 리듀서를 외부에서 넣어 사용하려 했습니다. (9a8e710b4449ea285081cf2a89432e444fd3f90f)

하지만 해당 방식으로 사용할 시 async/await의 연이은 반복이 이뤄져
코드 유지보수가 어려워질 것으로 보여 현재와 같이 Store 내부 상태로 리듀서를 가지는 방식으로 구조를 변경하였습니다. (16c2a10a895b4fbaa2ef02e3863ad5c5f9d5b477)

### 상수 관련
* `Object.freeze()`의 경우 로이님의 말씀을 듣고 현재 프로젝트에서는 필요성이 없을 것으로 보여 모두 제거하였습니다.
* 선택자 상수의 경우 테스트 코드에서도 재사용하기 위해 & 많아지는 DOM 조작으로 일단은 유지하였습니다만, 추후 프로젝트의 규모에 따라 주의하여 사용하도록 하겠습니다! _(지난 미션에서 잘못 이해해서 죄송합니다...😂)_

## 이번 단계에서 추가/수정한 기능
### 비즈니스 영역
* [x] 사용자가 저장한 동영상 목록을 처리할 수 있어야한다.
  * [x] 저장한 영상 목록을 가져올 수 있어야한다.
  * [x] 본 영상과 볼 영상을 필터링할 수 있어야한다.
  * [x] 갱신이 필요한 영상을 분류하여 업데이트할 수 있어야한다.
  * [x] 브라우저에 저장된(로컬 스토리지) 동영성 정보들을 관리할 수 있어야 한다.
* API 처리 관련 부분
  * [x] API 비용을 절약하기 위해 & 유튜브 영상 정보가 변경되었을 때를 대응하기 위하여 사용자가 동영상을 저장할 때 동영상 정보와 타임스탬프를 함께 로컬스토리지에 기록하여, 설정된 시간이 지났을 때만 동영상 정보를 갱신하여준다.

### 사용자 인터페이스 영역
* [x] 사용자가 추가한 동영상 목록에서 가장 처음에는 저장된 영상이 없으므로, 비어있는 것을 사용자에게 알려줄 수 있어야한다.
* [x] 이후 페이지를 다시 방문하여도, 메인 화면에서 내가 볼 영상들의 목록을 출력해주어야 한다.
* [x] 사용자가 사용하는 디바이스의 가로 길이에 따라 검색 결과가 반응형으로 표기될 수 있어야 한다.
* [x] 스낵바를 통해 상호작용 결과를 알려준다.
  * [x] 스낵바를 클릭할 시 즉시 닫을 수 있어야 한다.
  * [x] 스낵바는 여러개가 출력될 수 없다. 
* [x] 모달 영역이 사용자의 디바이스의 세로/가로 길이에 따라 정상적으로 노출될 수 있어야 한다.

### E2E 테스트
* [x] 검색 버튼을 클릭하여 검색 화면을 볼 수 있어야한다.
* [x] 검색어를 입력한 후 검색 버튼을 누를 시 검색 결과가 출력되어야 한다.
* [x] 출력된 검색 결과에서 저장 버튼을 누를 시 저장된 동영상 목록에 추가되어야 한다.
* [x] 검색 모달의 바깥 영역을 눌러 검색 화면을 닫을 수 있어야 한다.
* [x] 저장된 동영상 목록에 추가한 동영상을 시청 완료로 누를 시 본 영상으로 변경되어야 한다.
* [x] 메뉴의 본 영상 목록 필터를 눌러 본 영상들을 확인할 수 있어야 한다.
* [x] 저장된 동영상을 삭제할 수 있어야 한다.

![Mar-19-2022 23-04-28](https://user-images.githubusercontent.com/94832610/159124237-2d2a8435-41b9-40e1-97df-a93bdf1ea9e7.gif)

감사합니다!!

2022-03-20 09:53 UTC, roy-jung requested changes
콤피님 안녕하세요, 2단계도 잘 수행해주셨네요. 고생하셨습니다.
스낵바를 적용하신 부분 재밌게 잘 봤어요. 요구사항 외적으로 다양하게 시도하는 모든 행위를 응원합니다! 그밖에도 다양한 기법을 적극적으로 써보고자 노력하신 점이 돋보여 인상적이었습니다.
다만 코멘트 남긴 내용 외에도 몇가지 아쉬운점이 더 있는데, 아래에 리스트업해 보겠습니다.

1. "전체 리스트가 로딩 완료되고 난 뒤에 다시 스크롤을 내리면, 첫 페이지에 대해 다시 요청(pageToken 없이 요청)을 하게 됩니다. 특정 검색어에 대한 전체 페이지 개수는 정해져 있음에도, 무한히 같은 데이터가 반복해서 로드되고 있네요. 이는 심각한 문제이니 반드시 해결해주셨으면 합니다." https://github.com/woowacourse/javascript-youtube-classroom/pull/95#pullrequestreview-907935921
1단계 초반에 말씀드린 것인데, 아직 해결되지 않고 있어요. 이로 인해 같은 영상이 두 번 노출된 경우가 발생합니다. 이에따라 하나는 '저장'버튼이 노출되고 다른 하나는 '저장취소'버튼이 노출되는데 어느쪽을 눌러도 '저장'이 된다거나, 반대로 '저장취소'가 되는 등 예상치 못한 문제상황이 곳곳에서 발견됩니다.

2. 네이밍에 대해 고민을 해주세요. 간결한 용어사용보다 훨씬 중요한 것이 '문맥에 따라 충분히 유추가능한 어휘 사용'입니다. 단어가 길어지더라도 누구든 그 의미를 파악할 수 있도록 보다 친절하게 작성해주시길 부탁드려요.

3. 전체 폴더구조가 정리되지 않은 인상입니다. core, element, share, domain 등의 폴더명은 내부에 어떤 파일들이 있을지 예상되지 않네요.

4. 이 내용은 제가 단골로 드리는 말씀이지만 콤피님께는 한 적이 없는 것 같아요. 클래스의 메소드에 대한 부분입니다. 많은 분들이 기본 내장 메소드인 constructor에서 초기화하는 대신 별도의 메소드로 분리해서 초기화 작업을 진행하시는데, 그렇게 해야만 하는게 아닌데도 불구하고 맹목적으로 어떤 유행처럼 작성하고 있는것은 아닌가 싶어요. 이번 기회에 메소드의 존재가치, 클래스의 목적 등을 한 번 고민해보면 좋겠습니다.

2022-03-20 09:53 UTC, roy-jung commented on src/js/core/Store.js
> +    }
`if (new.target === Store)`로는 안되나요?

2022-03-20 09:53 UTC, roy-jung commented on src/js/display/Element/Snackbar.js
> +const Snackbar = (message, delay = 2500) => {
👍

2022-03-20 09:53 UTC, roy-jung commented on src/js/display/Share/Modal.js
> +    addEventDelegate(this.$container, '*[data-modal]', {
`*[data-modal]` 이 셀렉터는 어떤 의미인가요?

2022-03-20 09:53 UTC, roy-jung commented on src/js/display/Share/Modal.js
> +    const beforeModal = this.$activeModal;
`beforeModal`은 어떤 동작을 하는 변수인가요?

2022-03-20 09:53 UTC, roy-jung commented on src/js/display/YoutubeClassRoom/SaveList.js
> +  #drawList = [];
이 drawList라는건 어떤 의미인가요? 그릴 대상 목록? render와 의미가 겹치는것 아닌가요?

2022-03-20 09:53 UTC, roy-jung commented on src/js/core/Store.js
> +    this.setReducers();
reducer를 여러번 등록하는게 아니니, setReducer의 내용은 각 구체클래스의 constructor에서 실행하는 것으로 충분하지 않을까요? 그럴 경우 addReducer도 굳이 존재하지 않아도 될것 같은데요

2022-03-20 09:53 UTC, roy-jung commented on src/js/display/YoutubeClassRoom/SaveList.js
> +      drawEvent(state);
drawEvent라는건 뭔가요.. 단어의 의미들을 유추하기가 참 어렵습니다 ㅠ

2022-03-20 09:53 UTC, roy-jung commented on src/js/display/YoutubeClassRoom/SaveList.js
> +    YoutubeSaveListStore.addSubscriber(this.render.bind(this));
bind(this)를 쓰는 대신 해당 메소드를 arrow function으로 고치면 불필요한 메모리 낭비를 줄일 수 있습니다.

2022-03-20 09:53 UTC, roy-jung commented on src/js/domain/YoutubeSaveStorage.js
> +    localStorage.setItem(this.#STORAGE_NAME, JSON.stringify([...this.get(), insertItem]));
매번 localstorage에서 데이터를 읽어오는 대신 최초 한 번 읽어온 데이터를 담은 캐시를 활용하는 방안을 고려해보시면 좋을것 같아요.

2022-03-20 09:53 UTC, roy-jung commented on src/js/display/Share/Modal.js
> +
constructor로 충분하지 않을까요?

2022-03-20 09:53 UTC, roy-jung commented on src/js/core/Store.js
Store 클래스의 위치가 core폴더인게 조금 애매해 보여요.
core, '핵심'이라는데, 추상클래스가 정말 핵심이 맞나? 싶고..
차라리 store라는 폴더를 만들어서 abstract.js 라는 파일로 만들고, 나머지 'domain' 폴더 내부의 내용들을 전부 같은 store 폴더로 옮기면 어떨까요?

2022-03-20 09:53 UTC, roy-jung commented on src/js/__tests__/YoutubeSearchStore.test.js
`src/js/__tests__` 폴더와 `test` 폴더로 나뉜 이유는 무언가요? 둘의 역할이 다른가요?

2022-03-20 09:53 UTC, roy-jung commented on src/js/index.js
> +  Modal.enable('#app');
다른 클래스들과 다르게 유독 얘만 처음부터 인스턴스로 만들고 enable 메소드를 호출하게 한 이유가 있을까요?

2022-03-20 09:53 UTC, roy-jung commented on test/app.spec.js
> +    cy.get(SELECTOR.ID.MODAL_CONTAINER).should('not.have.class', 'hide');
클래스가 없는것만으로 보이는지를 장담할수는 없을것 같아요.
`.should('be.visible')` 체크가 추가되면 어떨까요?

2022-03-20 09:53 UTC, roy-jung commented on test/app.spec.js
> +    cy.get(SELECTOR.ID.SNACKBAR).should('include.text', ALERT_MESSAGE.SAVE_LIST_STATE_UPDATE);
snackbar에 해당 텍스트가 출력되었는지를 확인하는 것만으로 '본영상으로 변경됨'을 확신할 수 있나요?

2022-03-21 08:56 UTC, compy-ryu commented on src/js/core/Store.js
> +    }
클래스 자체적으로 비교도 가능했군요...🫢
해당 부분 수정 완료했습니다. 감사합니다!

- 91b6a4791663a62658604d185f2b60029aada791

2022-03-21 08:57 UTC, compy-ryu commented on src/js/display/Element/Snackbar.js
> +const Snackbar = (message, delay = 2500) => {
해당 dataset의 값과 동일한 아이디의 모달을 오픈하는 것이 기능입니다.

네이밍이 너무 축약 되어있는 것 같아, data-open-modal=”선택자"와 같은 방식으로 변경하였습니다!

- a87ab71749a9ebe282a60ec80fcb18aa27242ec3

2022-03-21 08:57 UTC, compy-ryu commented on src/js/display/Share/Modal.js
> +    addEventDelegate(this.$container, '*[data-modal]', {
해당 dataset의 값과 동일한 아이디의 모달을 오픈하는 것이 기능입니다.

네이밍이 너무 축약 되어있는 것 같아, data-open-modal=”선택자"와 같은 방식으로 변경하였습니다!

- a87ab71749a9ebe282a60ec80fcb18aa27242ec3

2022-03-21 08:57 UTC, compy-ryu commented on src/js/display/Share/Modal.js
> +    const beforeModal = this.$activeModal;
직전에 동작하였던/동작 중인 모달이라는 의도를 전달하기 위한 변수였습니다만

this.$activeModal으로도 충분할 것 같아보여, 제거하였습니다!

- a87ab71749a9ebe282a60ec80fcb18aa27242ec3

2022-03-21 08:58 UTC, compy-ryu commented on src/js/display/YoutubeClassRoom/SaveList.js
> +  #drawList = [];
역시 축약에만 신경써 의도가 확실히 불분명한 것 같습니다... 🥲

`renderMethodList` 로 변경하였습니다.

- 063d0cdf39e9558d87c5ce05b928aadc1f2b4ab7

2022-03-21 08:58 UTC, compy-ryu commented on src/js/core/Store.js
> +    this.setReducers();
원래 의도는 코드가 실행되는 영역을 보기 쉽게 나누어주기 위해서였습니다.

하지만 로이님 말씀대로... 해당 추상 클래스를 사용하는 클래스들은 생성자를 쓰지 않고 있고

한번만 실행하여도 되니 생성 영역에서 처리해주어도 의도 전달에는 문제가 없어보여 생성자 영역에서 처리해주는 것이 맞는 것 같습니다!

- 53289029d0b848b8a8ef1affdae670bbfac6144b

2022-03-21 08:58 UTC, compy-ryu commented on src/js/display/YoutubeClassRoom/SaveList.js
> +      drawEvent(state);
바꾸어준 `renderMethodList` 에 맞추어, `renderMethod` 으로 모두 통일성 있게 변경하였습니다..!

- 063d0cdf39e9558d87c5ce05b928aadc1f2b4ab7

2022-03-21 08:58 UTC, compy-ryu commented on src/js/display/YoutubeClassRoom/SaveList.js
> +    YoutubeSaveListStore.addSubscriber(this.render.bind(this));
엇, 지난번 피드백에서 말씀해주셨는데... 놓쳤네요...

죄송합니다... 😭.. 관련 부분 모두 변경 완료하였습니다!

- 1488652221cd7d861ef6124b20170a7634e6f8dc

2022-03-21 13:47 UTC, roy-jung commented on src/js/display/Share/Modal.js
> +    addEventDelegate(this.$container, '*[data-modal]', {
앞에 *은 꼭 필요한가요?

2022-03-21 13:49 UTC, roy-jung commented on src/js/domain/YoutubeSaveListStore.js
> +    };
👍

2022-03-21 13:51 UTC, roy-jung commented on src/js/domain/YoutubeSaveStorage.js
> +    localStorage.setItem(this.#STORAGE_NAME, JSON.stringify(updateItems));
👍

2022-03-21 13:56 UTC, roy-jung approved these changes
콤피님 고생하셨습니다. 피드백 반영해주신것 확인했고, 리팩토링으로 코드가 보다 간결해진 것 같아 덩달아 뿌듯하네요. 승인 및 머지하겠습니다.

2022-03-21 13:56 UTC, merged

2022-03-21 15:03 UTC, compy-ryu commented on src/js/display/Share/Modal.js
> +    addEventDelegate(this.$container, '*[data-modal]', {
모든 영역에 적용하려면 지금까지 붙여야 하는 줄 알았습니다.. 😱

죄송합니다...!! 수정 완료하였습니다!!

2022-03-21 15:04 UTC, compy-ryu commented on src/js/domain/YoutubeSaveStorage.js
> +    localStorage.setItem(this.#STORAGE_NAME, JSON.stringify([...this.get(), insertItem]));
해당 부분 클래스 상태로 가지도록 하여, 로컬스토리지를 처음 한번만 로드하도록 개선해보았습니다!

- a51e5f7ed4cf9688c623675855b6de140d9dfff9

2022-03-21 15:04 UTC, compy-ryu commented on src/js/display/Share/Modal.js
> +
사실상 이벤트 처리 밖에 없는데.. 확실히 괜히 나눈 것 같습니다....

다른 클래스에서도 이렇게 정리 했으니, 여기에서도 당연히 이렇게 작성해주는 것이 좋겠지란 생각으로 무심결에 접근한 것 같습니다.

로이님이 알려주신 방법대로 처리할 주제가 하나 밖에 없다면 생성자에서 한번에 처리할 수 있도록 주의하도록 하겠습니다!

- a87ab71749a9ebe282a60ec80fcb18aa27242ec3

2022-03-21 15:04 UTC, compy-ryu commented on src/js/core/Store.js
피드백 감사합니다.. 추상 클래스는 다른 곳에서 많이 쓰이고, 전체적인 기능의 템플릿 같은 개념이라고 생각하여 core에 배치하였었습니다.

하지만, 프로젝트의 규모가 커지면 이런식의 배치는 확실히 혼동될 것 같아보이네요.. 🥲

로이님의 피드백처럼 이후 해당 추상 클래스를 함께 사용하는 클래스들과 함께 배치하는 쪽으로 할 수 있도록 하겠습니다! 감사합니다!

- 0dcca2eae5b6be967a729d767fb54743aacfa9fe

2022-03-21 15:05 UTC, compy-ryu commented on src/js/__tests__/YoutubeSearchStore.test.js
Jest와 Cypress의 폴더를 나눈 것이였습니다..
이 부분은 제가 신경 쓰지 못하였습니다.. 죄송합니다..

Jest는 보통 유닛 테스트에 이용되니, 각 클래스들의 파일들과 함께 위치하도록 변경하였습니다.
- a06e6b9e5fd64a0932ef335fcbb3bb73c39e80ab

2022-03-21 15:05 UTC, compy-ryu commented on src/js/index.js
> +  Modal.enable('#app');
모달 클래스의 경우 document 전체에서 적용이 되기에 특별히 표현하고, Modal을 비활성화 하는 케이스도 고려하여 구현하고 싶었습니다.
하지만 단순하게 보았을 때 디렉터리로도 충분히 표현되고 있다 생각되었고, 비활성화 되는 케이스는 아직 필요하지 않는 “야그니"인 것 같아...

이전으로 다시 되돌렸습니다...!
* a87ab71749a9ebe282a60ec80fcb18aa27242ec3

2022-03-21 15:05 UTC, compy-ryu commented on test/app.spec.js
> +    cy.get(SELECTOR.ID.MODAL_CONTAINER).should('not.have.class', 'hide');
스타일 시트 수정으로도 버그가 발생될 수는 것도 고려해야겠군요.. 🫢
많이 배워갑니다!!.. 감사합니다 🙇‍♂️

- 6fa5406bb0d192add96da9df691a6d1ce61c15df

2022-03-21 15:06 UTC, compy-ryu commented on test/app.spec.js
> +    cy.get(SELECTOR.ID.SNACKBAR).should('include.text', ALERT_MESSAGE.SAVE_LIST_STATE_UPDATE);
아뇨.. 확신할 수 없습니다... 🥲

그리하여 사용자가 버튼을 클릭하였을 때 해당 엘리먼트가 있는 지 없는지.
상태가 변경 되었는지 확인하는 쪽으로 변경하였으며
이후 작업을 통해 추가한 영상을 확인하는 쪽으로 설명을 수정하였습니다!!

- 6fa5406bb0d192add96da9df691a6d1ce61c15df

2022-03-21 15:07 UTC, compy-ryu commented
> "전체 리스트가 로딩 완료되고 난 뒤에 다시 스크롤을 내리면, 첫 페이지에 대해 다시 요청(pageToken 없이 요청)을 하게 됩니다. 특정 검색어에 대한 전체 페이지 개수는 정해져 있음에도, 무한히 같은 데이터가 반복해서 로드되고 있네요. 이는 심각한 문제이니 반드시 해결해주셨으면 합니다." [[#95 (review)](https://github.com/woowacourse/javascript-youtube-classroom/pull/95#pullrequestreview-907935921)](https://github.com/woowacourse/javascript-youtube-classroom/pull/95#pullrequestreview-907935921)1단계 초반에 말씀드린 것인데, 아직 해결되지 않고 있어요. 이로 인해 같은 영상이 두 번 노출된 경우가 발생합니다. 이에따라 하나는 '저장'버튼이 노출되고 다른 하나는 '저장취소'버튼이 노출되는데 어느쪽을 눌러도 '저장'이 된다거나, 반대로 '저장취소'가 되는 등 예상치 못한 문제상황이 곳곳에서 발견됩니다.
> 

이전 1단계에서 API를 통해 넘어오는 총 동영상의 갯수로 체크해준 후 초과될 시 더 이상 API 요청을 하지 않도록 처리하였으나
갯수가 일정하지 않다보니, 마지막 한 페이지가 또 불러와지는 버그가 있었네요... 🤯
nextPageToken 값으로 마지막 페이지를 체크하는 식으로 수정하였습니다!
- 42ebae203ffad62ed2cfc4d85b081ede1acc9ff2

<br>

> 네이밍에 대해 고민을 해주세요. 간결한 용어사용보다 훨씬 중요한 것이 '문맥에 따라 충분히 유추가능한 어휘 사용'입니다. 단어가 길어지더라도 누구든 그 의미를 파악할 수 있도록 보다 친절하게 작성해주시길 부탁드려요.
> 

네이밍이 길어지면 코드 라인의 너비도 늘어나게 되어 가독성을 해치는 것으로 생각해
이정도면 괜찮겠지..? 하며 축약하고, 간결하게 쓰려고 한 것 같습니다...

다음 미션부터는 축약보다는 의도 전달을 위주로 시도하겠습니다!!

> 전체 폴더구조가 정리되지 않은 인상입니다. core, element, share, domain 등의 폴더명은 내부에 어떤 파일들이 있을지 예상되지 않네요.

디렉터리 구조를 어떻게 잡아야할 지가 가장 어려운 것 같습니다..
보통 도메인/UI > 담당 영역/페이지 > 기능 이런 우선 순위로 디렉터리를 지정했었습니다만

core의 경우는 추상 클래스만 있기에는 프로젝트 규모에 따라 혼동이 확실히 생길 것 같으며

스낵바의 경우 사용 방식이 다르기에 element로 나누었었습니다...
하지만 영역으로 생각해보았을 때 share와 element는 결국 동일한 뜻이 될 것으로 보여 다시 합쳐주었습니다!

<br>

> 이 내용은 제가 단골로 드리는 말씀이지만 콤피님께는 한 적이 없는 것 같아요. 클래스의 메소드에 대한 부분입니다. 많은 분들이 기본 내장 메소드인 constructor에서 초기화하는 대신 별도의 메소드로 분리해서 초기화 작업을 진행하시는데, 그렇게 해야만 하는게 아닌데도 불구하고 맹목적으로 어떤 유행처럼 작성하고 있는것은 아닌가 싶어요. 이번 기회에 메소드의 존재가치, 클래스의 목적 등을 한 번 고민해보면 좋겠습니다.
> 

이전 미션들에서부터 MVC패턴의 View에서 다시 시작 할떄를 고려하여 초기화를 생각하고 습관적으로 구현해온 것 같습니다...
조심하도록 하겠습니다...!

2022-03-21 15:12 UTC, compy-ryu commented
안녕하세요! 로이님!!
이번 피드백도 자세하게 도움주셔서 정말 정말 감사합니다!

특히 이번 미션에서 로이님 피드백을 듣고 많은 고민을 하게 되었는데요...🥲
첫번째로 추상 클래스를 사용에 대해 진지하게 다시 고민해보고, 공부해보아야 할 것 같았습니다.

추상 클래스를 활용하면서 디버깅이 매우 어려워짐을 느꼇고
처음부터 추상 클래스를 사용하다보니, 막상 사용하지 않는 작은 영역까지 사용하지 않는 메서드들까지 추가하고, 사용하지 않는 영역까지 호출하게 되어 오히려 코드 가독성을 해치는 것까지 경험했습니다..

또 성능 관련 부분에서는 지금까지 뭐가 좋고 나쁘다! / 이정도는 괜찮겠지? 까지만 생각하고 막연히 생각해왔었는데..
근본적으로 처음부터 다시 생각해보아야 할 것 같습니다..

배우거나, 검색 해보았을 때는 이렇게 한다고 하니 의심도 없이 내 프로젝트에서도 조심해서 나쁠꺼 없겠지? 란 생각으로
너무 과하게 해석한 경향이 있었고 하나씩 쌓아오다보니 무심결에 계속 지나친 것 같습니다..

지금과 같은 작은 프로젝트에서는 괜찮겠지만, 추후 프로젝트 규모가 커졌을 때를 고려하여 조심하도록 하겠습니다..!

이외로 말씀해주신 네이밍과 디렉터리 부분도 다음 미션을 통해 정했더라도 다시 한번 더 고민해보고, 사용해보도록 하겠습니다!!
아! 추가로, 로이님이 말씀하신 것처럼 앞으로 더 다양한 시도(?) 많이 해볼 수 있도록 하겠습니다 😁

부족한 코드 보아주시느라 정말 고생하셨습니다!
감사합니다! 👍