[2단계 - 나만의 유튜브 강의실] 위니(김예지) 미션 제출합니다.
woowacourse/youtube-classroom pull request #150
Opened 2022-03-20 10:16 UTC by rladpwl0512

안녕하세요, 위니 2단계 미션 제출합니다. 
중간 중간 막히는 부분이 생겨서 제출이 많이 늦어졌네요... 정말 죄송합니다 😅  

## 데모페이지 
[위니's 나만의 유튜브 강의실](https://rladpwl0512.github.io/javascript-youtube-classroom/)
*API key 초과될 시, 확인이 편할 수 있도록 dummy data를 할당했습니다. 
필요할 경우 알려주시면 바로 다른키로 변경하도록 하겠습니다. 

## step2 테스트 (Cypress E2E)
![스크린샷 2022-03-20 오후 7 14 36](https://user-images.githubusercontent.com/52344833/159157659-57be8f09-aaf7-4eff-ab6a-b2f2f368effb.png)

## 배운 점 
작성 중

2022-03-21 11:29 UTC, wmakerjun requested changes
위니 😆 
어려운 2단계 기능 구현하느라 너무너무 고생했어요~! 데모 페이지에 접속해보니 ui도 신경쓴 점이 돋보였습니다 ㅎㅎ
코드를 보다보니 공통적으로 반복되는 부분들이 있거 그 부분 중심으로 리뷰를 남겼어요. 아래 3가지가 신경쓰는데는 엄청 많은 시간이 드는건 아니지만 위니의 코드를 한단계 업그레이드하는데는 큰 힘이 되어줄 것 같아요~! 💪🏻 

### 1. 네이밍
네이밍의 일관성을 유지하기 위해 노력해보면 좋을 것 같아요. 저도 늘 네이밍은 굉장히 어려운 문제인데요. 좋은 네이밍을 작성하기 이전에 일관성만 잘 유지되도 훨씬 코드가 깔끔해지는것 같더라구요. 그래서 `대문자 또는 소문자로 시작하는 네이밍`, `동사-명사`와 같은 규칙을 정해서 일관되게 코드를 작성하면 더 좋을 것 같아요

### 2. 메서드 분리
우리가 프리코스에서 의식적으로 계속 연습했던 한 함수 또는 메서드가 15라인이 넘어가지 않게끔 역할을 나누어보면 좋을 것 같아요. 고민할 부분에 Controller가 커지는것 같다고 했는데 Controller가 커지는 것보다, Controller가 가지는 메서드들이 커지지 않게 분리해준다면 더 읽기 좋은 코드가 될 것 같아요. 특히 한 메서드에서 `try~catch`구문이 2번이상 반복되는 경우 해당 메서드의 내용을 이해하는데 시간이 많이 걸리더라구요~!

### 3. for문은 꼭 필요한 경우에만
Array.map이나 Array.forEach와 같은 내장 객체의 메서드로 구현할 수 있는 부분들이 for문으로 작성되어 있는 경우가 있는것 같아요. for문의 경우 휴먼 에러(사람의 실수)가 발생하기 쉽고, 읽는 사람도 조건을 이해하는데 시간이 많이 걸리는 경우도 있는것 같아요. 자바스크립트에서 제공해주는 유용한 메서드들을 더 잘 활용해서 더 읽기 좋은 코드를 만들어보는건 어떨까요~? 💪🏻

2022-03-21 11:29 UTC, wmakerjun commented on cypress/integration/video.spec.js
> +    cy.get('#saw-list').children().should('have.length', 1);
dom selector가 `동사-명사`인 경우도 있고, `명사-동사`인 경우도 있는것 같아요. 네이밍의 규칙을 만들어본다면 다른 사람과 협업할 때도 일관된 네이밍을 할 수 있을것 같아요 😄

2022-03-21 11:29 UTC, wmakerjun commented on cypress/integration/video.spec.js
> +  cy.visit('http://localhost:9000/');
visit하는 url의 경우 따로 상수로 관리하는건 어떨까요~? 테스트가 많아질수록 점차 describe별로 visit하는 로직이 많아질 수 있을것 같아요 😄

2022-03-21 11:29 UTC, wmakerjun commented on src/js/Controller.js
>      this.SearchCloseView = new SearchCloseView();
`searchInputView`, `searchResultView`와는 다르게 `SearchCloseView`는 대문자로 시작하는 이유가 있을까요~?

2022-03-21 11:29 UTC, wmakerjun commented on src/js/Controller.js
>      } catch (error) {
`error`를 사용하고 있는 곳이 없는것 같아요~!

2022-03-21 11:29 UTC, wmakerjun commented on src/js/models/VideoModel.js
> +    }
for문의 경우 변수 선언, 조건문, 증감의 연산까지 한 줄에 여러 로직이 들어가기 때문에 휴먼 에러가 발생할 확률이 높은데요. 혹시 이 부분을 Array의 메서드를 이용해서 구현해보면 어떨까요~?

2022-03-21 11:29 UTC, wmakerjun commented on src/js/models/VideoModel.js
>    IsIncludedSavedItem(newItem) {
혹시 이 메서드가 대문자로 시작하는 이유가 있을까요~?

2022-03-21 11:29 UTC, wmakerjun commented on src/js/models/VideoModel.js
> +      return error;
return된 error를 사용하고 있는 곳이 혹시 있을까요~?

2022-03-21 11:29 UTC, wmakerjun commented on src/js/views/AppView.js
> +    if (target.className === 'user-delete-button') {
`target`에 다른 class가 추가로 있다면 이 로직은 실패할 수 밖에 없을 것 같아요. [classList](https://developer.mozilla.org/ko/docs/Web/API/Element/classList)를 사용해서 변경에 취약하지 않게 구현해봐도 좋을 것 같아요 😄 
```suggestion
    if (target.classList.contains("user-delete-button")) {
```

2022-03-21 11:44 UTC, wmakerjun commented on src/js/models/VideoModel.js
> +      const REDIRECT_SERVER_HOST = 'https://thirsty-ritchie-0c8419.netlify.app/';
이런 url을 따로 관리하는 파일 또는 객체가 있으면 어떨까요~? 매번 url을 메서드 내부에서 선언하는건 관리하기가 어려울것 같아요

2022-03-21 11:44 UTC, wmakerjun commented on src/js/views/AppView.js
>  }
메서드가 길어서 어떤 과정이 벌어지는지 모두 읽어야 알 수 있을것 같은데요. 메서드를 분리해보면 어떨까요~?

2022-03-22 17:10 UTC, rladpwl0512 commented on cypress/integration/video.spec.js
> +    cy.get('#saw-list').children().should('have.length', 1);
피드백 듣고 보니 제가 정말 네이밍을 일관성 없게 지었네요 😅 네이밍을 일관되게 작성해보겠습니다!

2022-03-22 17:12 UTC, rladpwl0512 commented on cypress/integration/video.spec.js
> +  cy.visit('http://localhost:9000/');
오...! describe가 많아지면서 visit하는 로직이 많아지면 링크를 일일이 적어주는게 번거로울 수 있겠네요. 
말씀대로 상수로 관리해보도록 하겠습니다 👍

2022-03-22 17:12 UTC, rladpwl0512 commented on src/js/Controller.js
>      this.SearchCloseView = new SearchCloseView();
이 부분은 제가 실수했네요 😅 말씀해주신 것처럼 네이밍에 일관성을 가져가도록 하겠습니다!

2022-03-22 17:15 UTC, rladpwl0512 commented on src/js/Controller.js
>      } catch (error) {
error를 사용하는 곳이 없을 때는 어떻게 해야할지 찾아보고 적용해보겠습니다! 🤔

2022-03-22 17:15 UTC, rladpwl0512 commented on src/js/models/VideoModel.js
> +    }
for문은 항상 쓰지 말아야지 하는데, 계속 습관적으로 사용하게 되네요 😅 말씀해주신대로 Array 메서드를 사용해서 리팩터링 해보도록 하겠습니다! 

---
해결1: [1d35809](https://github.com/woowacourse/javascript-youtube-classroom/pull/150/commits/1d35809acecc27f991c647922d8fd2cbc763ad1b)
some문을 활용하여, if문 조건에 해당하는 경우 즉시 반복문을 빠져나오도록 리팩터링 했습니다! 

해결2: [ca5767e](https://github.com/woowacourse/javascript-youtube-classroom/pull/150/commits/ca5767e619a5c70676d8b6e10d58c9f2b300ae84)
피드백 주신 부분 뿐 아니라, for of문을 some문으로 변경해보았습니다. 사실 구문의 길이는 비슷한 것 같은데, 이 경우 굳이 변경해 줄 필요가 없는지 고민입니다.

2022-03-22 17:16 UTC, rladpwl0512 commented on src/js/models/VideoModel.js
>    IsIncludedSavedItem(newItem) {
이 부분도 제가 실수했습니다! 수정해주도록 하겠습니다 😅

2022-03-22 17:26 UTC, rladpwl0512 commented on src/js/models/VideoModel.js
> +      return error;
사용하지 않는 error를 의미없이 리턴해주고 있네요. 이부분도 수정하도록 하겠습니다! 

(fetch를 했는데 제대로 응답이 되지 않을 때, 응답 에러 상황에 따라 사용자들에게 적절한 메시지를 출력할 수 있도록 리팩터링 해보면 좋겠네요!🤔)

2022-03-22 17:27 UTC, rladpwl0512 commented on src/js/views/AppView.js
> +    if (target.className === 'user-delete-button') {
오오 이부분은 생각하지 못했어요! 다른 class가 생겨도 에러가 생기지 않도록, classList로 바꿔서 구현해보도록 하겠습니다. 감사합니다 👍

2022-03-22 17:29 UTC, rladpwl0512 commented on src/js/models/VideoModel.js
> +      const REDIRECT_SERVER_HOST = 'https://thirsty-ritchie-0c8419.netlify.app/';
항상 api 초과되면 url을 변경하면서 번거롭다고 생각했는데, 말씀대로 관리하면 더 효율적일 것 같아요! 링크도 따로 관리해보도록 하겠습니다~ 

---
해결: [33e3389](https://github.com/woowacourse/javascript-youtube-classroom/pull/150/commits/33e33898471ec6545544c7fd8b3692ee0d9d5f0e)
api 주소를 관리하는 SERVER 객체를 만들었습니다 😊

2022-03-22 17:30 UTC, rladpwl0512 commented on src/js/views/AppView.js
>  }
메서드가 많이 기네요 😅 분리해서 가독성 좋은 코드를 만들어보겠습니다!

2022-03-23 05:05 UTC, rladpwl0512 commented
준 안녕하세요~ 꼼꼼하게 리뷰해주셔서 정말 감사합니다 🙏🏻 정말 다양한것들을 배웠어요! 
리뷰 반영했고, 댓글로 해당 리뷰에 대한 커밋 링크 남겼습니다. 더해서 질문까지 남긴 부분도 있으니 확인 부탁드릴게요 :) 

이번 피드백으로 가장 많이 느낀 것은 '네이밍을 일관적이게 가져가야한다'는 것입니다. 네이밍을 나름 생각하면서 지었는데, ```동사-명사``` 혹은 ```명사-동사```와 같이 순서로의 일관성은 생각하지 못했던 것 같습니다. 
네이밍 부분이 꽤 많아서 아직 다 고치지 못했지만, 미션 진행하면서 남는 시간에 중간 중간 계속 변경하도록 하겠습니다. 다 고치고 리뷰 요청 드리면 너무 늦은 새벽일까봐 일단 요청드립니다! 
잘 부탁 드립니다 😌

2022-03-29 08:25 UTC, wmakerjun commented
@rladpwl0512 
너무너무 고생 많으셨스빈다 위니 ㅎㅎ
'네이밍을 일관되게 가져가기'에 공감을 많이 해주었는데요. 개발자의 네이밍은 정말 계속해서 고민하게 되는 부분인데요. 나만의 네이밍 규칙 사전을 만들어보고, 그 규칙들을 지켜보는 연습을 해보는것도 좋아요. 저도 개발할 때 네이밍을 위한 규칙을 정의하지 않으면 실수를 많이 하게 되더라구요. 물론 나중에 팀과 함께 일하게 되면 팀원들과 합의하고 규칙을 정하는 연습도 필요하지만, 위니 스스로도 좋은 네이밍은 무엇일지, 좋은 네이밍을 위해선 어떤 전략이 필요할지 한번 고민해봐도 좋을 것 같아요! 막연하다면 슬랙에서 다른 크루들과도 이야기 나눠보구요! ㅎㅎ

이번 미션 너무너무 고생 많았습니다!

2022-03-29 08:25 UTC, merged