[1단계 - 나만의 유튜브 강의실] 카일(임광열) 미션 제출합니다
woowacourse/youtube-classroom pull request #16
Opened 2021-03-06 04:08 UTC by GwangYeol-Im

-

2021-03-07 10:41 UTC, Vallista requested changes
안녕하세요 카일님! 리뷰어 vallista입니다!
이번 미션에서 잘 부탁드립니다!

UX/UI 측면에서 사용성이 높은 프로젝트이다보니, 3가지 관점(UX/UI, 프로젝트 설계, 코드) 으로 피드백을 드리려 합니다!

---

첫 번째로 UX/UI 피드백입니다.

1. 각각의 애니메이션이 끝난 후, 각각의 비디오가 출력된다면 현재 레이아웃이 별로 이질감이 없지만, 전체가 끝난 후 로딩이 출력되는 부분인데, 그렇다면 스켈레톤 애니메이션이 전체 로딩 애니메이션으로 보이는게 더 좋지 않을까요?

![스켈레톤 애니메이션이 동일하게 움직이는 것](https://user-images.githubusercontent.com/6455767/110236550-b9ce2f80-7f79-11eb-8eaf-8b0eca20c674.png)

현재의 애니메이션에서,

![스크린샷 2021-03-07 오전 11 51 20](https://user-images.githubusercontent.com/6455767/110227395-781e9400-7f3b-11eb-818f-5f44535ddbf4.png)

이러한 형태로, 모든 카테고리에 대해서 일관적으로 로딩되는 애니메이션이 있다면 더 직관적일 것 같습니다 👍 

2. 검색 후, 실수로 저장할 수도 있을 것 같습니다

![스크린샷 2021-03-07 오후 7 20 19](https://user-images.githubusercontent.com/6455767/110236624-2ba67900-7f7a-11eb-8797-c9a8fbde25fb.png)

저장을 취소하는 기능도 있으면 좋을 것 같습니다 🙏 

3. 동영상 검색은 `볼 영상`, `본 영상` 버튼과 레벨을 동일하게 하면 유저에게 혼동을 줄 것 같습니다.

![스크린샷 2021-03-07 오후 7 20 38](https://user-images.githubusercontent.com/6455767/110236631-36610e00-7f7a-11eb-8352-214927608d7d.png)

동영상 검색은 눌러도 초록색으로 active 변경이 되는 요소가 아니므로, 해당하는 부분은 레이아웃을 다르게 가져가면 좋을 것 같습니다. (돋보기만 보인다던지..)

4. 검색 다이어로그는 상하단 패딩이 있었으면 좋겠습니다. 없다보니 이미지가 짤려보이는 것 같아요.. ㅠ

---

전반적인 피드백 입니다.

1. 전반적인 코드가 굉장히 깔끔해서 따로 터치할만한 부분은 많이 없었습니다!

2. Object를 사용하여 만든 이유가 있을까요~? class를 통해서 객체를 나누면 더 좋을 것 같습니다!

3. 나머지 상세한 부분은 코드 라인에 리뷰를 남겼습니다!

감사합니다!

2021-03-07 10:41 UTC, Vallista commented on src/js/library/DOMelements.js
> +const dom = {
Object.freeze로 고정을 하면 좋을 것 같습니다 :)

2021-03-07 10:41 UTC, Vallista commented on src/js/init.js
> +function initState() {
this binding을 이용해 무언가를 할 생각이 따로 없다면, arrow function으로 가는게 더 좋지 않을까요? 호이스팅이나 다른 부분에 대해서도 딱히 사용이 되는 것 같아보이지는 않습니다!

2021-03-07 10:41 UTC, Vallista commented on package.json
> +  "version": "1.0.0",
아직 완성된 메이저 버전이 아니므로 0.0.1로 가져가는 건 어떨까요?

2021-03-07 10:41 UTC, Vallista commented on src/js/handlers/latestKeywordSearch.js
> +import { search } from '../viewController.js';
요 친구만 따로 파일을 땐 이유가 있을까요?
latestKeywordSearch.js 보단 좀 더 유틸적으로 사용할 수 있는 이름으로 선정 한 후, 이러한 비슷한 로직을 관리하는 형태로 가져가는게 좋지않을까요?

```
export function handleLatestKeywordSearch...
...
```

형태로 default로 사용하기보다 export로 사용하는게 더 좋지않을까요~?

2021-03-07 10:41 UTC, Vallista commented on src/js/library/searchAPI.js
> +function fetchSearchResult(keyword, nextPageToken = '') {
프로젝트에서 async - await를 사용하니, async - await로 변경하고 than-catch를 try-catch로 바꾸는게 어떨까요?

2021-03-07 10:41 UTC, Vallista commented on src/js/library/templates/notFound.js
> +function createNotFoundTemplate() {
굳이 함수로 가져가야 할 이유가 있을까요~?

2021-03-07 10:41 UTC, Vallista commented on src/js/library/utils/date.js
> +function formatDate(dateString) {
dateString이 제대로 된 값이 아닌경우에 대한 예외가 있으면 좋을 것 같습니다!

2021-03-07 12:57 UTC, GwangYeol-Im reviewed
@Vallista 리뷰 잘보았습니다. 다른 부분은 모두 이해가 되었는데 arrow function 을 사용하는 부분이 잘 와닿지 않아서 해당 코멘트에 대한 추가 설명 한번만 부탁드릴게요 ㅎㅎ 😲

2021-03-07 12:57 UTC, GwangYeol-Im commented on src/js/init.js
> +function initState() {
웬만하면 arrow function은 해당 용도에 적합하다고 생각할 때만 (e.g. callback etc) 쓰려고 하는데요, 혹시 이 부분에서 그걸 추천해주시는 이유가 따로 있을까요? 😀

2021-03-07 12:57 UTC, GwangYeol-Im commented on src/js/library/utils/date.js
> +function formatDate(dateString) {
좋은 지적 감사드립니다. 해당 부분은 불완전한 string이 들어올 가능성을 확인 후에 좀 더 보완하도록 하겠습니다 :)

2021-03-07 12:57 UTC, GwangYeol-Im commented on src/js/library/templates/notFound.js
> +function createNotFoundTemplate() {
그렇네요.. 다시 보니 동적으로 렌더해주는 값도 없으니 html에서 관리 되어도 상관없는 아이네요 ㅎㅎ 지적 감사드립니다 ~

2021-03-08 07:01 UTC, GwangYeol-Im commented on src/js/library/DOMelements.js
> +const dom = {
DOM 요소를 viewController 의 각 구조에 맞게 따로 선언해주어 해당 상수 객체는 사라졌습니다. 나중에 객체를 상수로 만들 일이 있을 때 유용히 쓰도록 하겠습니다 :)

2021-03-08 07:36 UTC, GwangYeol-Im commented on src/js/handlers/latestKeywordSearch.js
> +import { search } from '../viewController.js';
저희는 유저의 행동을 처리하는 이벤트 핸들러를 구분할 수 있다고 생각했고, 그 중에서 최근 검색어를 누르는 유저의 행동도 하나의 단위가 될 수 있다고 보았습니다. 그러한 결과로 이러한 파일 분리가 적합하다고 생각이 들었습니다. 그리고 핸들러 단위로 파일을 관리하는 게 좋을 것 같아 default 를 쓰는 게 더 의미적으로 맞을 것 같다고 생각했는데 추천해주신 방법에 대해 좀 더 자세히 설명 부탁드려도 될까요?

2021-03-08 07:36 UTC, GwangYeol-Im commented on src/js/library/searchAPI.js
> +function fetchSearchResult(keyword, nextPageToken = '') {
<img width="454" alt="Screen Shot 2021-03-08 at 4 23 52 PM" src="https://user-images.githubusercontent.com/57053577/110288002-b3e45700-802a-11eb-96fe-cd5a446939cf.png">

말씀해주신 대로 고쳐보았는데 일관성은 유지할 수 있지만 함수의 길이가 길어지고 가독성 적인 면에서 이점이 있는지 와닿지는 않은 것 같습니다 😅 웬만하면 일관성 유지하는 쪽을 고수하는 것이 더 좋은 방법일까요?

2021-03-09 04:30 UTC, GwangYeol-Im commented
현재 리뷰주신 부분과 다른 페어의 리뷰를 모두 살펴보고 리팩토링 작업을 거쳤습니다. UI UX 부분은 2단계 때 같이 다룰 예정이라 참고하시고 코멘트 주시면 감사하겠습니다 !!

2021-03-10 07:32 UTC, Vallista commented on src/js/init.js
> +function initState() {
혹시나 모를 추후 this binding의 이슈라던가. 그러한 일이 있을 때 문제가 있을 수 있으므로, 저는 기본적으로 arrow function을 선호하는 편이긴 한데요! 카일님의 스타일이라면 상관없을 것 같습니다!

2021-03-10 07:33 UTC, Vallista commented on src/js/handlers/latestKeywordSearch.js
> +import { search } from '../viewController.js';
음.. 그러면 핸들러가 엄청 많아지는 경우, 파일이 다수가 되므로 추후 프로젝트 매니징을 하는 데 있어서 오히려 복잡해질 수 있을 것 같습니다~ 행동이라는 도메인을 작게 분리하는 것 보다, 객체를 만들고 그 안에서 행동을 관리하는게 더 좋아보이는데, 어떻게 생각하시나요?

2021-03-10 07:37 UTC, Vallista commented on src/js/library/searchAPI.js
> +function fetchSearchResult(keyword, nextPageToken = '') {
```js
try {
   return (
     await fetch(`${YOUTUBE_BASE_URL}/search?${query}`);
   ).json()
} catch (e) {
   console.error(e)
   return e
}
```

형태로 사용하는게 맞아보입니다~ try 에서 에러가 났다면 외부의 data.json은 없을테니까요!
가독성 측면에서는 이게 더 이점이 있는지, promise 방법이 이점이 있는지는 개인차가 있을 것 같구요! (둘 다 코드가 짧아서 문제는 없어보입니다)

제가 생각하기에는 async await로 일관적인 형태를 가져가는게 좋아보입니다.  이유는 프로젝트 상에서 async-await를 더 많이 사용하고 있고, es6 스펙이기 때문입니다. 어차피 둘 다 promise객체를 반환하므로...

2021-03-10 07:46 UTC, Vallista approved these changes
안녕하세요 카일님!
리뷰에 달아놓으신 코맨트 부분 피드백을 다시 드렸구요!

또한 전반적으로 리뷰가 잘 적용되었고 코드도 깔끔해서 1단계는 이정도로 하고, 2단계를 진행하시면 될 것 같습니다!

빠르게 적용해주셔서 감사합니다!

2021-03-11 10:40 UTC, GwangYeol-Im commented on src/js/handlers/latestKeywordSearch.js
> +import { search } from '../viewController.js';
프로젝트의 규모가 커질수록 그런 방향으로 가는 게 더 관리가 용이할 수 있음을 느끼고 있는 것 같습니다 ! 좋은 의견 감사드립니다!!

2021-03-11 10:42 UTC, GwangYeol-Im commented
@Vallista 안녕하세요! 다른 미션을 같이 수행하느라 코멘트와 피드백을 지금 확인했네요 ㅎㅎ 다시 피드백 주신 부분 바탕으로 2단계 진행해보도록하겠습니다~ 확인 뒤 머지 부탁드릴게요 !!

2021-03-13 10:15 UTC, merged