[1단계 - 나만의 유튜브 강의실] 신세한탄(신세희) 미션 제출합니다.
woowacourse/youtube-classroom pull request #19
Opened 2021-03-06 15:30 UTC by shinsehantan

안녕하세요 리뷰어님 :)
콜린@2SOOY과 함께 이번 미션을 진행하게 된 신세한탄입니다.

아직 데모페이지를 만들지 못해서
주요 기능 실행 결과 gif를 첨부드리는 점 양해 부탁드립니다.

![youtubeClassRoomStep1](https://user-images.githubusercontent.com/67591151/110211253-1dece700-7ed9-11eb-98ca-62d439748848.gif)

---
### 👩🏻‍💻 step1에서 구현한 기능

- [x] 유튜브 검색 API를 통해서, 내가 추가로 보고 싶은 영상들을 검색할 수 있다.
  - [x] 검색 시 엔터키를 눌렀을 때와 마우스로 검색 버튼을 눌렀을 때 검색 동작이 이루어진다.
- [x] 로딩컴포넌트: 데이터를 불러오는 중일 때, 현재 데이터를 불러오는 중임을 skeleton UI로 보여준다.
- [x] 검색 결과가 없는 경우 결과 없음 이미지를 추가하여, 사용자에게 메시지를 보여준다.
  - [x] 검색 결과 없음 이미지는 `src/images/status/not_found.png` 경로에 있다.
- [x] 최초 검색결과는 10개까지만 보여준다. 더 많은 데이터는 스크롤을 내릴 때 추가로 불러온다.
  - [x] 검색 결과 화면에서 유저가 브라우저 스크롤 바를 끝까지 이동시켰을 경우, 그다음 10개 아이템을 추가로 api요청하여 불러온다.
- [x] 내가 검색한 영상들의 json 데이터를 `저장`할 수 있다. (실제 저장이 아닌 영상 id를 Web Storage에 저장). 단 이미 저장된 경우는 저장 버튼이 보이지 않게 한다.
- [x] 저장 가능한 최대 동영상의 갯수는 100개이다.
- [x] 검색 모달에 다시 접근했을 때 가장 마지막에 검색한 키워드로 검색한 결과를 보여준다.
- [x] 최근 검색 키워드를 3개까지 화면상에 검색창 하단에 보여준다.
---

그럼 리뷰어님의 피드백 기다리겠습니다.
감사합니다 🧚🏼‍♀️🧚

2021-03-10 09:21 UTC, Vallista requested changes
안녕하세요 신세한탄님~ 리뷰어 vallista입니다!
이번 미션 잘 부탁드립니다. 👍 

아무래도 UX/UI 측면에서 사용성이 높은 프로젝트이다보니, 3가지 관점(UX/UI, 프로젝트 설계, 코드) 으로 피드백을 드리려 합니다!

---

UX/UI 피드백입니다.

1. 스켈레톤 애니메이션이 너무 빨리 꺼지는 것 같습니다! 사용자가 인지할 시간을 주고, 좀 널널히 종료되었으면 좋겠어요!

2. 검색 후, 실수로 저장할 수도 있을 것 같습니다 저장을 취소하는 기능도 있으면 좋을 것 같습니다 🙏 

3. 동영상 검색은 `볼 영상`, `본 영상` 버튼과 레벨을 동일하게 하면 유저에게 혼동을 줄 것 같습니다.

동영상 검색은 눌러도 초록색으로 active 변경이 되는 요소가 아니므로, 해당하는 부분은 레이아웃을 다르게 가져가면 좋을 것 같습니다. (돋보기만 보인다던지..)

4. 스켈레톤 애니메이션 후 동영상 프리뷰나 이런 이미지 데이터가 프리뷰 이미지 로드가 되어있는 형태로 조금 더 부드럽게 개발이 되었으면 좋겠습니다!

---

전반적인 피드백입니다.

1. 테스트를 도메인 단위로 나눈 것은 센스있는 작업인 것 같습니다! 👍 

2. css를 BEM 적용을 시도하신 것 같아 좋았습니다! 👍 

3. try-catch가 적절하게 활용되고 있지는 않아보입니다! 가장 큰 장점인, 에러가 나와도 런타임은 돌아갈 수 있게 return 을 줘서 해당 값에 따라 에러 알럿을 띄워주면 좋을 것 같습니다.

4. 전반적으로 함수에대한 예외처리가 조금 부족한 것 같습니다! 공통으로 쓰이는 함수 혹은 추출된 함수의 param에 대한 예외처리를 해주시면 더 좋을 것 같습니다!

5. classname, id는 많이 쓰이는 것 같으므로 상수로 관리하면 좋을 것 같습니다!

6. class를 사용하면서 내부 메서드에 대한 공개 범위의 구분, 정렬이 있었으면 좋겠습니다!

---

코드에 대한 피드백은 상세 라인에 적어두었습니다!
빠르게 작업하여 제출해주셨는데 ㅠㅠ 제가 늦게봐서 죄송합니다!!!

1단계 정말 수고 많으셨고 피드백 주시면 바로 보겠습니다!
죄송하고 감사합니다 ㅠㅠ

2021-03-10 09:21 UTC, Vallista commented on .prettierrc
> +  "singleQuote": false,
singleQuote를 false로 한 이유가 있을까요~?

2021-03-10 09:21 UTC, Vallista commented on src/js/components/MenuSection.js
> +    this.$target = $(".menu-section");
classname이나 id는 전역 상수로 관리하는 건 어떨까요?

2021-03-10 09:21 UTC, Vallista commented on src/js/utils/localStorage.js
> +    console.error(err);
로컬 스토리지를 읽을때 에러가 난다면 return조차 안해주는데, 에러는 나되, 사용자는 계속 사용할 수 있어야 하지 않을까요~?

2021-03-10 09:21 UTC, Vallista commented on src/js/utils/localStorage.js
> +    console.error(err);
catch error 상황에서 return이 있었으면 좋겠습니다!

2021-03-10 09:21 UTC, Vallista commented on src/js/utils/localStorage.js
> +export const getLocalStorage = (key, defaultValue) => {
key나 defaultValue 등이 존재하지 않을경우에 대한 예외가 있으면 좋을 것 같습니다. 또한 key의 경우에는 전역 상수로 관리하면 좋겠네요!

2021-03-10 09:21 UTC, Vallista commented on src/js/utils/api.js
> +  const res = await fetch(url, option);
try-catch로 감싸서 안전하게 만들면 좋을 것 같습니다!

2021-03-10 09:21 UTC, Vallista commented on src/js/utils/api.js
> +export const api = {
사용을 할 때, `{ api }`로 가져온 다음, api.searchVideo를 할 것 같은데, 이렇게 가져오지말고 export default api로 선언한 다음, API.searchVideo를 하는게 좋지 않을까요? 괜히 한번 더 래핑된 느낌이 들어서요!

아니면 각각의 메소드가 export로 나와있는 것도 좋겠습니다

2021-03-10 09:21 UTC, Vallista commented on src/js/components/SearchModal.js
> +class SearchModal {
class를 사용하여 표현한 것은 좋았습니다!
다만, 내부에 쓰이는 함수와 외부에 쓰이는 함수를 정렬하는 것과 구분이 되어있으면 좋을 것 같습니다!

2021-03-10 12:41 UTC, shinsehantan commented on src/js/components/SearchModal.js
> +class SearchModal {
SearchModal 내의 모든 메서드는 내부에서만 사용된다고 생각하는데
모든 메서드명에 언더바를 붙여서 구분해야 할까요?

App에서 아래처럼 사용하는 경우에도 외부에서 쓰인다고 판단해야하는지 궁금합니다.🤔

```js
  openModal() {
    this.searchModal.showModal();
  }
```

2021-03-11 15:15 UTC, shinsehantan commented on .prettierrc
> +  "singleQuote": false,
이전에 사용하던 형식을 그대로 가져와서 사용했고, 별다른 이유는 없었습니다.🙃

2021-03-11 15:15 UTC, shinsehantan commented on src/js/components/MenuSection.js
> +    this.$target = $(".menu-section");
c80bd9e 상수로 처리했습니다 :)

2021-03-11 15:15 UTC, shinsehantan commented on src/js/utils/localStorage.js
> +    console.error(err);
98b2567 defaultValue를 리턴하도록 수정했습니다.😊

2021-03-11 15:15 UTC, shinsehantan commented on src/js/utils/localStorage.js
> +export const getLocalStorage = (key, defaultValue) => {
08bd6cd key나 defaultValue가 존재하지 않을 경우에 대비해 디폴트 파라미터를 설정했습니다.

2021-03-11 15:16 UTC, shinsehantan commented on src/js/utils/api.js
> +  const res = await fetch(url, option);
98b2567 네 추가했습니다.😊

2021-03-11 15:16 UTC, shinsehantan commented on src/js/utils/api.js
> +export const api = {
98b2567 export default 방식으로 변경했습니다!

2021-03-13 11:00 UTC, Vallista commented on src/js/components/SearchModal.js
> +class SearchModal {
구분하면 좋을 것 같습니다! 왜냐하면, 외부에서 내부 함수를 사용하지마! 라는 의미가 있기 때문입니다!

외부에서 사용되는 함수라면 외부에서 쓰이는 메소드로 취급하면 될 것 같습니다!

2021-03-13 11:26 UTC, Vallista approved these changes
코드 리뷰 반영된 것 확인하였습니다!

빠르게 적용해주셔서 감사합니다!

2021-03-13 11:26 UTC, merged