[1단계 - 나만의 유튜브 강의실] 크리스(이송원) 미션 제출합니다.
woowacourse/youtube-classroom pull request #22
Opened 2021-03-08 07:03 UTC by swon3210

### 🎯 step1 검색 기능

- [x] 검색 모달에서 검색어를 바탕으로 영상을 검색하여 그 결과를 보여준다.
  - 검색 시 엔터키를 눌렀을 때와 마우스로 검색 버튼을 눌렀을 때 검색 동작이 이루어진다.
  - 데이터를 불러오는 중일 때, 현재 데이터를 불러오는 중임을 UI로 보여준다.
- [x] 검색 모달에 다시 접근했을 때 이전에 검색한 결과를 보여준다.
- [x] 검색 결과가 없는 경우 결과 없음 이미지를 추가하여, 사용자에게 메시지를 보여준다.
- [x] 최초 검색결과는 10개까지만 보여준다. 더 많은 데이터는 스크롤을 내릴 때 추가로 불러온다.
  - 검색 결과 화면에서 유저가 브라우저 스크롤 바를 끝까지 이동시켰을 경우에 새 데이터를 불러온다.
- [x] 검색한 영상들 중 특정 영상 데이터를 저장 버튼을 눌러 저장할 수 있다.
  - 이미 저장된 경우는 저장 버튼이 보이지 않는다.
- [x] 최근 검색한 3가지 검색 키워드를 볼 수 있다.

- 🔧 예외
  - [x] 저장 가능한 최대 동영상의 갯수는 100개여야한다.
  - [x] 빈 검색어를 입력할 경우 검색이 이루어지지 않는다.
  - [x] 이전과 같은 검색어를 입력할 경우 검색이 이루어지지 않는다.

<br>

### 프로젝트 컨벤션

- 이 프로젝트는 MVC 패턴을 따른다.
- prefix
  - view 에서 render 는 요소의 내부 요소를 조작함을 의미
  - view 에서 show 는 요소의 style.display 값을 조작함을 의미

### 디렉터리 구조도

```
📦src
 ┣ 📂apis
 ┃ ┗ 📜youtube.js
 ┣ 📂controller
 ┃ ┣ 📜controller.js
 ┃ ┗ 📜controllerUtil.js
 ┣ 📂storage
 ┃ ┣ 📜localStorage.js
 ┃ ┣ 📜prevSearchResult.js
 ┃ ┣ 📜searchQuery.js
 ┃ ┗ 📜videoToWatch.js
 ┣ 📂utils
 ┃ ┗ 📜querySelector.js
 ┣ 📂view
 ┃ ┣ 📜templates.js
 ┃ ┣ 📜view.js
 ┃ ┗ 📜viewUtil.js
 ┣ 📜constants.js
 ┣ 📜elements.js
 ┗ 📜index.js
```

### 노력한 점

- view 가 직접적으로 element 의 클래스를 조작하는 것이 아니라 viewUtil 을 통해서만 뷰를 조작할 수 있도록 만들었습니다.
- controller 가 비대해지는 것을 막고자 controller 의 큰 동작들이 controllerUtil 객체를 통해 수행되도록 만들었습니다.

- 휘발성이 있는 상태와 영구적인 상태를 분리하였습니다. 휘발성이 있는 어플리케이션 상태는 model 로, 그렇지 않은 상태는 storage 로 분리하였습니다(현재 필요한 어플리케이션 상태는 모두 storage 의 상태 뿐이라고 판단하여 model 은 만들어져 있지 않은 상태입니다.)

### 궁금한 점

- UI 변경이 많이 일어나는 어플리케이션 특성 때문에 다른 많은 페어들은 이 어플리케이션을 옵저버 패턴에 따라 만든 것으로 알고 있습니다. 그런데 저희는 모델의 상태변경 메서드와 그 상태를 화면에 반영하는 view 메서드를 같이 실행하는 모듈함수를 따로 두면 굳이 그럴 필요가 없다고 판단했습니다. 혹시 이런 단순한 방법으로는 커버할 수 없는 옵저버 패턴만의 강점이 있는지가 궁금합니다.

- 상태값으로 가지고 있는 배열을 바탕으로 UI 요소를 화면상에 나타낼 때, 요소들이 배열 순서의 반대 순서로 요소들이 나열되어야 하는 이슈가 있었습니다. 화면이 상태를 온전히 반영해야 하기 때문에 해당 배열을 역순으로 정렬시킨 다음 화면에 그 순서대로 요소를 보여줘야 한다는 의견과, 요소를 역순으로 보여줘야 하는 디자인적인 필요가 있을 뿐이므로 상태를 변경하지 말고 CSS를 통해 그냥 화면에서는 배열의 역순으로 요소가 나열되게 해야 한다는 의견이 있었는데, 어느 쪽이 맞는 의견이라고 볼수  있는지가 궁금합니다.

2021-03-08 16:52 UTC, wow9144 requested changes
controller 의 큰 동작들이 controllerUtil 객체를 통해 수행되도록 하셨다고 하셨는데, 비대해지는 것을 막고자 분리를 시도하신 점에는 좋은 점수를 드리고 싶습니다!
다만 `큰 동작` 이 과연 무엇이고, 크기는 어떤 기준으로 정할 수 있고 알 수 있는가 하는 의문이 들었습니다.
제가 나중에 투입된 동료 개발자의 느낌으로 코드를 읽어갔는데, 제가 어떤 기능을 넣어야 한다고 가정하면 controller에 넣어야 할지 controllerUtil에 넣어야 할지 알 수 없을것 같았습니다.
큰 동작이라는 애매한 표현보다는 `비즈니스 로직`이 위치한 `서비스` 라는 개념을 도입하시면 개선하는데 좀 도움이 되시지 않을까 싶습니다.

궁금한 점에 대한 답변
1. 모델의 상태변경과 그 상태 변경에 따라 뷰를 갱신시키는 일은 굉장히 번거롭게 신경을 써야 하는 작업입니다. 간단한 정도의 상태 변경과 뷰는 괜찮지만 어플리케이션이 복잡해지면 복잡해질수록 헬로 가게 됩니다. :) 
그럴 때 상태가 변경되면 뷰가 알아서 갱신되도록 만들어 놓으면 중간에서 신경 쓸 필요가 없으니 작성해야 하는 코드도 줄고, 신경을 덜 써도 되니 편해집니다. 
그런 장점이 있기에 view 를 다룰때 특히 옵저버 패턴, pub/sub 패턴이 유용하게 쓰입니다.
복잡성의 문제가 가장 큰 것 같습니다.

2. 무조건 무엇이 맞다기 보다는 경우에 따라서 다를 것 같습니다. 
js 에서 데이터 배열을 가지고 있고 이걸 화면에 뿌리는 상황이라면 저는 데이터를 역순으로 하여 그대로 뿌릴 것 같습니다. 그렇지 않고 데이터가 js에 없이 정적인 html 로 굳어져 있는 페이지뿐이라면 css 로만 해결 하려고 할 것 같습니다. 

그 외 내용은 세부 코멘트를 확인해주세요!

2021-03-08 16:52 UTC, wow9144 commented on src/apis/youtube.js
> +        pageToken ? `&pageToken=${pageToken}` : ''
pageToken 3항식을 여기에 넣기보다는 위의 query 객체를 만드는 단계에서 결정하도록 하고 여기는 parseQuery만 두면 좋을 것 같습니다.

2021-03-08 16:52 UTC, wow9144 commented on src/view/viewUtil.js
> +  showElement($element) {
처음에 이걸 먼저 만드시고 코드를 전개해가다보니 showElementBySelector 가 만들어지고 결국 현재는 showElement는 안쓰고  showElementBySelector 쓰고 있는 것 같습니다.

저는 이 2개의 메서드가 중복으로 보입니다. :)

내부에서 파라미터에 할당된 값이 엘리먼트인지 string 인지 구분하여 적절하게 반응하도록 하여 사용자가 showElement를 써야 하는지  showElementBySelector 를 써야하는지 구분하지 않고 쓸 수 있게끔 해주면 더 좋지 않을까 싶습니다.

2021-03-08 16:52 UTC, wow9144 commented on src/constants.js
> +  SEARCH_BUTTON: 'search-button',
'#search-button' 으로 하지 않고 'search-button'으로 한뒤에 이걸 사용 하는 쪽에서 매번 #을 붙여주는것이 어떤 효용성을 가지는지 잘모르겠습니다.
더군다나 이 객체의 이름은 SELECTOR_ID 이므로 모든 프로퍼티는 id 셀렉터로 쓰일 문자열 일것으로 이름에서 충분히 의도가 전달이 되기 때문에 문자열 자체에 #을 포함하는게 더 낫지 싶습니다.

2021-03-08 16:52 UTC, wow9144 commented on src/storage/prevSearchResult.js
> +const prevSearchResult = {
prevSearchResult.js
searchQuery.js
videoToWatch.js
이 파일들 내부에서 데이터를 저장하고 가져오기 위해 localStorage를 사용하고 있을뿐이기 때문에 src/storage 밑에 위치해 있어야 하는 파일로 보기는 어려운것 같습니다.
예를 들어 제이쿼리를 `사용`하는 파일이 jQuery 폴더에 들어있는 셈입니다.
이 파일들의 역할과 책임을 기준으로 어떤 공통점이 있는가를 생각하셔서 적절히 추상화하여 폴더를 만들고 이동 시키면 좋을 것 같습니다.

2021-03-08 16:52 UTC, wow9144 commented on src/storage/localStorage.js
> +export function setLocalStorageItem(key, item) {
localStorage API 에 직접 접근 하지 않고 이곳을 통해서만 하도록 하겠다고 의도하셔서 이 파일을 만드셨다면 굉장히 잘 하신 것 입니다.
(그러나 실제로 다른 코드를 본 결과 이 곳을 통해서만 접근하지는 않고 여기저기서 window의 localStorage에 직접 접근하네요 -0-;)
이런 네이티브 혹은 특정 라이브러리 API를 여기저기서 접근하게 되면 이 API 가 변경되거나 다른 좋은 라이브러리를 도입해서 쓴다거나 하게 되면 모든 코드를 다 고쳐야 하지만, 이렇게 랩핑해서 사용하는 포인트를 한군데로 몰아놓으면 이 내부의 구현만 바꾸면 되므로 관리가 쉬워집니다.

2021-03-08 16:52 UTC, wow9144 commented on src/view/view.js
> +const view = {
view 객체를 조금 나눠보시는것을 제안 드리고 싶습니다.
화면의 모든 것을 여기서 조작하려고 하기 때문에 여기가 쉽게 비대 해집니다.
view 를 하나의 페이지 개념으로 보시기 보다는(혹시 그렇게 생각하셨다면) 여러개의 view가 모여 하나의 큰 view page를 이룬다 같은 느낌으로 접근해보시면 좋지 않을까 싶습니다.
관련있는것은 모으고, 관련 없는것은 분리하는 방식으로 가시면 됩니다.

2021-03-14 11:40 UTC, swon3210 commented on src/apis/youtube.js
> +        pageToken ? `&pageToken=${pageToken}` : ''
앗 그렇군요. 반영했습니다!

2021-03-14 11:40 UTC, swon3210 commented on src/view/viewUtil.js
> +  showElement($element) {
정확히 짚어주셨네요. showElement 는 이미 초기에 HTML 상에 렌더링 된 요소를 제어할 때 쓰이고 showElementBySelector 는 동적으로 렌더링된 요소를 제어할 때 쓰기 위해 저렇게 나눴었는데, 의도에 맞게 적절하게 사용되도록 변경했습니다.

showElement 는 파라미터로 $element를,
showElementBySelector 는 파라미터로 selectorString 을 받도록 변경하였습니다.

말씀해주신대로 하니 해당 메서드들을 이해하기 훨씬 수월해지네요 :)

2021-03-14 11:40 UTC, swon3210 commented on src/constants.js
> +  SEARCH_BUTTON: 'search-button',
이 부분에 대해서는 처음에는 저도 리뷰어님과 같은 의견이었으나, 저는 HTML 템플릿 string 상에 class 나 id 를 부여하는 아래와 같은 코드에서 # 이나 . 이 없는 편이 더 좋을 수 있겠다는 페어의 의견을 받아들였었습니다. 저는 아래와 같은 경우처럼 만일 기존의 SELECTOR 문자열에 # 이나 . 이 붙어있다면 해당 문자열을 .substr(1) 등을 통해 빼는 것 보다는 그때 그때 붙이는 편이 더 간편할 것이라고 생각이 들었는데, 리뷰어님께서는 그래도 # 과 . 가 붙은 편이 더 낫다고 생각하시는지 궁금합니다.

2021-03-14 11:40 UTC, swon3210 commented on src/storage/prevSearchResult.js
> +const prevSearchResult = {
리뷰어님 말씀을 듣고 나니 분명 어색한 부분이라는 것이 느껴지는군요... 말씀해주신 대로, 이름을 바꾸되, 이 파일들의 내용을 바탕으로 만들어지는 객체들은 model 과 유사하지만 따로 상태를 만들지 않고 바로 storage 에 접근하는 차이점이 있기 때문에 storageModel 이라는 폴더에 묶었습니다. 또한 추상화를 위해 클래스를 도입해서

BasicStorage -> PrevSearchResult

BaiscStorage -> ArrayStorage -> VideoStorage

의 상속 구조를 통해 추상화를 시도했습니다.

prevSearchResult
searchQuery
videoToWatch(-> watchingVideo 로 이름 변경됨)

는 store.js 라는 파일에서 일괄적으로 export 되도록 변경하였습니다.

2021-03-14 11:40 UTC, swon3210 commented on src/storage/localStorage.js
> +export function setLocalStorageItem(key, item) {
setLocalStorageItem 과 같은 함수들은 분명 말씀하신 의도대로 사용하기 위해서 만든 것이었는데, 저희가 실수로 바로 window 의 localStorage 에 직접 접근해서 코드를 짜고 있었습니다. 다음엔 이런 착오 없도록 PR 날리기 전 같은 실수를 하지는 않았는지 체크하겠습니다! 막연히 한곳에서 쓰는게 좋지 않을까 싶어서 작성한 코드였는데 상세한 이유 알려주셔서 감사드립니다!

2021-03-14 11:40 UTC, swon3210 commented on src/view/view.js
> +const view = {
말씀하신 사항대로 분리를 해보았는데, 확실히 코드가 더 명확해지고 깔끔해지는걸 느낄 수 있었습니다. 단순히 분리하기 보다는 여기서도 클래스 상속을 활용해서

BasicView -> ModalView : 모달의 내용과 관련된 view
BasicView -> LayoutlView : alert, confirm 과 같은 webAPI 혹은 snackbar 등의 이용자에게 시각적 피드백을 주기 위한 view
BasicView -> VideoView : 비디오 컨텐츠에 관련한 view

이런 식으로 분리 및 구체화 하였습니다.

2021-03-14 11:44 UTC, swon3210 reviewed
리뷰가 이루어지고 시간이 꽤나 많이 지났음에도 이제서야 리뷰를 반영해서 죄송합니다. 솔직하게 털어놓자면 미션을 시간안에 할 수 있을지가 확실치 않아 페어와 미리 2단계를 조금씩 진행하다보니 늦어버렸습니다. 앞으로는 코드 리뷰에 더욱 진지하게 임하도록 하겠습니다.

2021-03-14 13:08 UTC, swon3210 commented
리뷰어님의 조언대로 controller 에서 model 의 상태값을 조작하는 비즈니스 로직을 service 로 분리하여보았습니다. 그런데 이때 궁금증이 생기는데요, service 를 생성하면 모델에 대한 접근은 controller 가 아니라 service 에서만 해야하게 되는 것인가요?

2021-03-17 14:31 UTC, wow9144 commented
비즈니스 로직을 서비스로 분리했다고 하더라도 컨트롤러에서 모델을 직접 접근 해도 괜찮습니다.
컨트롤러가 모델을 직접 알지 못하도록 레이어를 철저히 구분하면 모델을 변경하는 쪽을 알기 쉬우나 때론 불필요하게 한 단계 서비스를 거쳐서 가야하는 불편함이 있을 수 있습니다.
트레이드 오프가 있는 부분이니 지금 단계에서는 느끼는대로 해보시고, 느끼는대로 변경해보시는게 좋습니다 :)

2021-03-17 15:23 UTC, wow9144 approved these changes
크게 걸리는 내용 없이 읽어내려 갈 수 있었습니다. :)
대부분의 경우 상속 보다는 합성이 나은 선택일 가능성이 크니 상속과 합성을 비교하는 글을 찾아 보시면 설계에 도움이 되실 것 같습니다.

2021-03-17 15:23 UTC, wow9144 commented on src/constants.js
> +  SEARCH_BUTTON: 'search-button',
아 템플릿에서 쓰시려고 그랬었군요. 
템플릿에서 쓰면 빼줘야 하니까 그렇게 하셨다고 하니 그럼 이해가 됩니다.
사용하는쪽에서 빼냐 넣냐의 선택을 해야 하는 시점에서 더 편할거 같아서 선택을 하셨다면 그렇게 하셔도 괜찮을 것 같습니다 :)

2021-03-17 15:23 UTC, wow9144 commented on src/controller/modalController.js
> +    modalView.hideSearchResultIntersector();
컨트롤러가 제왕처럼 너무 세세하게 컨트롤하려고 하는것 같습니다.
이렇게 되면 수정이 일어났을 때 한곳을 수정하는게 아니라 2곳 이상을 수정하게끔 됩니다.

비유를 하자면, 
택시에서 손님이 `인천공항으로 가주세요`만 하면 되는데, 
```
좌회전 해주세요.
우회전 해주세요.
x번 고속도로 타주세요.
다리 지나 직진해주세요.
```
라고 세세히 컨트롤하려고 하면 정작 목적지가 인천공항인지는 알 수 없는 것과 같습니다.

좌회전을 할지 우회전을 할지 고속도로를 탈지 말지는 오롯이 택시기사의 판단에 맡기든 네비에 의존하는 택시기사에게 맡기든 하는것이 좋고 손님과 기사의 커뮤니케이션은 `인천공항`이 좋다는 것입니다.
인천공항으로 가는길이 바뀌면 택시기사의 운전만 바뀌면 되는데, 손님이 세세하게 컨트롤 하려고 하면 택시기사측과 손님측 모두 바뀌어야 합니다.

단일 책임 원칙을 위해 메서드를 작게 하다보니 외부에서 그 작은 메서드를 일일이 호출하게끔 되지 않았나 싶은데, 자신의 메서드 여러개를 호출해서 하나의 책임을 하는 메서드 하나만 컨트롤러가 의존하게끔 하면 코드를 읽기가 더 쉬워질 것 입니다.

2021-03-17 15:24 UTC, merged

2021-04-15 12:48 UTC, swon3210 commented
# [MVC] View 영역 코드 작성- 2
## view 메서드를 view 유틸 함수를 통해 더 간결하게 작성하기
- view 메서드에서 직접 Element 의 클래스나 스타일을 변경하기보다는 중간 유틸 함수를 두는 것이 유지 보수에도, 코드를 간결하고 명시적으로 만드는 것에 더 도움을 줄 수 있다.

2021-04-15 12:50 UTC, swon3210 commented
# [MVC] 컨트롤러 함수 작성- 3
## 컨트롤러 메서드 내부에 너무 많은 동작이 수행되지 않기
- 컨트롤러 메서드는 그 역할이 직관적으로 파악될 수 있도록 입력을 받아, 그 입력을 주요 핸들링 함수에 전달하는 식으로 짜는 것이 좋다.
- 컨트롤러 메서드 하나가 제왕처럼 여러 일을 다 도맡아 하기 보다는 많은 모듈 함수들을 한꺼번에 수행하는 여러 함수들을 실행하는 것이 코드를 더 빠르고 쉽게 이해하게 만들 수 있다.