[2단계 - 나만의 유튜브 강의실] 브랜[서지환] 미션 제출합니다.
woowacourse/youtube-classroom pull request #28
Opened 2021-03-11 04:48 UTC by seojihwan

안녕하세요~ 양성민님 2단계 미션 제출합니다!!
[데모 링크](https://seojihwan.github.io/javascript-youtube-classroom/)

![youtube_step_2](https://user-images.githubusercontent.com/52202474/110732894-5d645c00-8268-11eb-8f68-d8272f224c9f.gif)
### step2 기능 구현 목록
- [X] 가장 처음에는 저장된 영상이 없으므로, 비어있다는 것을 사용자에게 알려주는 상태를 보여준다.
- [X] 이후 페이지를 방문했을 때 기본 메인 화면은 내가 볼 영상들의 리스트를 보여준다.
- [X] 영상 카드의 이모지 버튼을 클릭하여 아래와 같은 상태 변경이 가능해야 한다.
  - [X] ✅ 본 영상으로 체크
  - [X] 🗑️ 버튼으로 저장된 리스트에서 삭제할 수 있습니다. (삭제 시 사용자에게 정말 삭제할 것인지 물어봅니다.)
- [X] 사용자가 버튼을 클릭했을 때 해당 행위가 정상적으로 동작하거나, 실패하였음을 snackbar를 통해 보여준다.
- [X] 본 영상, 볼 영상 버튼을 눌러 필터링 할 수 있다.

### 궁금한 점

#### 정적element vs 동적element
2단계까지 미션을 진행하면서 동적인 HTMLElement들만 새로 수정해주고 나머지 정적인 HTMLElement들은 HTML파일 내에 태그로 작성해준 후 display:none 스타일을 통해 숨겨주는 방식을 사용하였습니다.
display:none 속성을 갖을 수 있는 classname을 추가하거나 제거하는 방법을 통해 쉽게 구현할 수 있었던 것 같습니다. 
추후에 기능이 더 많아지고 여러 페이지를 구현해야 한다고 생각 할 때 이런 정적인 방식이 한계가 있다고 생각되는데 이에 대한 양성민님의 생각이 궁금합니다~

#### 이벤트에 의존하는 동작 방식, 로컬 스토리지에 대한 읽기 쓰기 반복
버튼을 클릭했을 때, 유튜브를 검색했을 때 등등 이벤트가 발생했을 때에만 코드가 동작하므로 코드의 중복이 발생합니다.
(ex: 초기에 로컬스토리지의 정보를 가져와서 `클립을 메인화면에 렌더링 하는 과정`, 동영상을 저장했을 때 `해당 클립을 메인화면에 렌더링 하는 과정`)
또한 로컬스토리지의 읽기 쓰기는 해당 키에 대한 value를 덮어 씌우는 방식이기 때문에 데이터가 많아지면 효율성이 좋지 않다고 생각합니다. 

따라서 다음과 같은 방향을 생각해 보았는데 양성민님의 생각이 궁금합니다!
초기에 로컬스토리지에서 데이터를 가져오면 앱은 해당 데이터들을 객체로 관리한다.
beforeunload이벤트, 주기적인 일정 간격(ex 5분)을 통해 데이터들을 로컬스토리지에 저장한다.

2021-03-13 06:57 UTC, ysm0622 requested changes
> 해당 클립 데이터에 대한 접근 방식

> 클립의 저장 버튼을 누르면 해당 클립에 저장된 data속성을 통해 해당 클립의 인덱스 값을 얻을 수 있습니다. 인덱스를 이용하여 저장되어 있던 클립 배열의 원소를 찾아낼 수 있게됩니다. 하지만 동영상을 삭제하고 추가해주는 과정에서 인덱스가 중복될 수 있기 때문에 인덱스를 업데이트할 필요성이 있습니다. 이러한 문제를 피하기 위해 동영상 삭제버튼을 눌렀을 때 동영상은 숨겨지기만 하고, 브라우저를 새로고침 했을 때 동영상이 삭제되게 구현하였습니다. 서니 & 도비 페어는 객체로 클립들을 저장하고 id를 통해 접근하는 방식을 사용하였습니다. 하지만 순서가 보장되지 않는 문제점이 있었고 비디오의 저장 시점에 대한 데이터를 추가하여 초기 브라우저 접속시에 동영상들이 순서에 맞게 정렬되도록 구현하였습니다. 저는 서니 & 도비 페어의 방식이 훌륭하다고 생각합니다. 혹시 위 두 방법 이외의 다른 방법도 있는 것일까요? 발생할 수 있는 문제점이나 개선방향을 알려주시면 반영할 수 있도록 노력하겠습니다! 양성민님의 생각이 궁금합니다~

- 배열의 인덱스를 key로 사용하는 것은 배열의 순서가 바뀌거나 원소가 추가,삭제 될수 있는 경우에는 유효하지 않습니다. 배열의 순서가 바뀌고 원소가 추가, 삭제되더라도 원소가 유니크하게 가질수있는 ID같은 값을 사용하는게 일반적입니다.
- 비디오 저장시점을 추가해서 정렬하는 방식이 더 적절한것같아요.

> 2단계까지 미션을 진행하면서 동적인 HTMLElement들만 새로 수정해주고 나머지 정적인 HTMLElement들은 HTML파일 내에 태그로 작성해준 후 display:none 스타일을 통해 숨겨주는 방식을 사용하였습니다. display:none 속성을 갖을 수 있는 classname을 추가하거나 제거하는 방법을 통해 쉽게 구현할 수 있었던 것 같습니다. 추후에 기능이 더 많아지고 여러 페이지를 구현해야 한다고 생각 할 때 이런 정적인 방식이 한계가 있다고 생각되는데 이에 대한 양성민님의 생각이 궁금합니다~

- 맞습니다. 초기렌더링에 유저가 아직 보지도 않을 DOM을 미리 파싱해서 그려야하는 것, 자바스크립트에서 이미 그려진 DOM에 접근해야하기 때문에 자바스크립트에서 초기 HTML DOM tree에 의존성이 생기는 문제 등이 있을 것 같네요.
- 장점도 있고 단점도 있지만, 지금 규모의 어플리케이션에서는 크게 문제있진 않은 것같습니다.

> 버튼을 클릭했을 때, 유튜브를 검색했을 때 등등 이벤트가 발생했을 때에만 코드가 동작하므로 코드의 중복이 발생합니다. (ex: 초기에 로컬스토리지의 정보를 가져와서 클립을 메인화면에 렌더링 하는 과정, 동영상을 저장했을 때 해당 클립을 메인화면에 렌더링 하는 과정) 또한 로컬스토리지의 읽기 쓰기는 해당 키에 대한 value를 덮어 씌우는 방식이기 때문에 데이터가 많아지면 효율성이 좋지 않다고 생각합니다. 따라서 다음과 같은 방향을 생각해 보았는데 양성민님의 생각이 궁금합니다! 초기에 로컬스토리지에서 데이터를 가져오면 앱은 해당 데이터들을 객체로 관리한다. beforeunload이벤트, 주기적인 일정 간격(ex 5분)을 통해 데이터들을 로컬스토리지에 저장한다.

- 질문을 잘 이해하지못했는데요, "로컬스토리지의 읽기 쓰기는 해당 키에 대한 value를 덮어 씌우는 방식이기 때문에 데이터가 많아지면 효율성이 좋지 않다고 생각합니다." 라고 하셨는데,
- "beforeunload이벤트, 주기적인 일정 간격(ex 5분)을 통해 데이터들을 로컬스토리지에 저장한다." 라고하면 이벤트가 발생했을 때 뿐만아니라 더 자주 localstorage에 쓰기작업을 하게되는 것 아닌가요?

2021-03-13 06:57 UTC, ysm-dev commented on src/js/handler/main/onButtonContainer.js
> +};
이 actions라는 객체는 어떤 객체고 이 key값들 이름의 의미는 무엇인가요..? className같아보이진 않는데..

2021-03-13 06:57 UTC, ysm-dev commented on src/js/handler/main/onButtonContainer.js
> +};
optional chaining에 대해 알아보세요 
또 IE 같은 구형 브라우저에서는 이 문법을 어떻게 사용할 수 있는지 알아보세요 👍

2021-03-13 06:57 UTC, ysm-dev commented on src/js/handler/window/onWindowInput.js
> +  actions[key] && actions[key]();
여기도 optional chaining을 쓸 수 있겠네요 👍

2021-03-13 06:57 UTC, ysm-dev commented on src/js/utils/constant.js
> +    CHECK_UNWACTHED_CLIP: '☑️ 선택하신 클립을 볼 영상으로 이동시켰습니다 ☑️',
UI에서 두 메시지가 바뀌어서 나오는거같아요 !

2021-03-13 14:39 UTC, seojihwan commented on src/js/handler/main/onButtonContainer.js
> +};
옵셔널 체이닝으로 간결하고 명확한 의미를 전달할 수 있겠네요 5822c469b6822ce0047d9b12c57c961a7b375273

구형 브라우저에서는 syntax error가 발생하기 때문에 트랜스 파일러를 이용하여 syntax를 변형 시켜준다면 사용 가능할 것 같아요
babel을 이용한다면 ie 6을 대상으로는 다음과 같이 코드의 변형이 이루어지네요

```js
const a = {b:1}

a?.b
```

```js
var a = {
  b: 1
};
a === null || a === void 0 ? void 0 : a.b;
```

2021-03-13 14:40 UTC, seojihwan commented on src/js/utils/constant.js
> +    CHECK_UNWACTHED_CLIP: '☑️ 선택하신 클립을 볼 영상으로 이동시켰습니다 ☑️',
메시지가 반대로 나오는 걸 놓쳣군요 ㅜ
추가로 스낵바가 여러번 호출될 때 자연스럽게 나타날 수 있도록 로직을 변경하였습니다~ 16f646e

2021-03-13 14:47 UTC, seojihwan commented
3단계를 진행하면서 id로 비디오 데이터에 접근할 수 있도록 수정해 보겠습니다!!

마지막 로컬스토리지에 대한 질문에 대해서 제 생각은 다음과 같습니다!
객체로써 앱의 모든 데이터를 들고 있는 상황에서 브라우저가 onload이벤트가 발생했을 때 로컬스토리지의 데이터를 가져오고, beforeunload이벤트가 발생햇을 때 (추가로 비정상 종료를 고려하여 5분 간격으로 데이터를 로컬스토리지에 저장)에만 저장하는 방식을 생각해 보았습니다.

지금 구현한 방식은 클립 저장버튼을 누를때 마다, 볼 영상, 본 영상으로 클립을 체크할 때 마다 로컬스토리지의 읽기 쓰기가 일어나는데 이부분을 줄여보고 싶었습니다!

2021-03-13 14:48 UTC, seojihwan commented on src/js/handler/main/onButtonContainer.js
> +};
명확하지 않은 것 같아서 조건문으로 변경해 보았습니다! 
ccd69d3101830398f768a0024f4d3ddfe4decc8d

2021-03-13 15:42 UTC, ysm0622 commented
@seojihwan 아하! 질문을 이제 이해했습니다.
좋은 접근입니다만 실제 앱이 데이터를 메모리에 들고있는 부분과, 로컬스토리지의 정보를 나눠서 관리해야한다는 점에서
관리포인트가 늘어나기때문에, (두 데이터의 정합성을 관리해야하는 필요성이 생김: Single Source of truth) 그 부분이 성능적으로 얻는 이득보다 큰지는 잘 모르겠네요!
저라면 localStorage에 저장한 영상의 id나 key값만 저장해둘것같은데, 그렇다면 localStorage에 쓰고 읽을때 오버헤드가 그렇게 클것같지도 않고요.!
하지만 좋은 접근과 발상입니다! 👍

2021-03-15 07:31 UTC, seojihwan commented
사용 목적에 따라 상태로 관리할 것인가 로컬스토리지로 구분하는게 좋겟네요!
앱의 규모가 크지 않기 때문에 로컬스토리지로 관리하는 것에 큰 문제가 없을 것 같네요
앱의 규모가 크더라도 말씀해주신 것처럼 id나 key값 들만 관리한다면 용도에 맞게 활용할 수 있을것 같아요

2021-03-16 03:20 UTC, ysm0622 approved these changes
2단계까지 고생하셨습니다! 👏👏👏

다음단계에서 봬요!

2021-03-16 03:20 UTC, merged