[2단계 - 나만의 유투브 강의실] 인치(한창희) 미션 제출합니다
woowacourse/youtube-classroom pull request #37
Opened 2021-03-13 10:08 UTC by hchayan

안녕하세요 리뷰어님 인치입니다! 2단계 풀 리퀘스트 보냅니다...! 😁
1단계 코드 리뷰를 받고 정말 많은 생각을 했었습니다 😭😭

구현을 하면서 궁금한 점들이 많아지고, 찾아봐도 명확한 답들이 없는 것들이 많다 보니
그러다가 그것들에 대한 해답을 얻고 싶어, 해답을 얻고자 하는 방향으로 자꾸 물어본 것 같습니다.
문제에 대해 생각해보고 고민하는 과정을 중점으로 진행해보고자 합니다. 감사합니다!
 
## [데모페이지](https://elated-bohr-c6f011.netlify.app/)

## 🧾 파일 구조

```
📦js
 ┣ 📂api
 ┃ ┗ 📜youtubeAPI.js
 ┣ 📂components
 ┣ 📂constants
 ┃ ┗ 📜constant.js
 ┣ 📂controller
 ┃ ┣ 📜modal.js
 ┃ ┣ 📜saved.js
 ┃ ┗ 📜search.js
 ┣ 📂model
 ┃ ┣ 📜storage.js
 ┃ ┗ 📜youtube.js
 ┣ 📂templates
 ┃ ┗ 📜video-template.js
 ┣ 📂utils
 ┃ ┗ 📜util.js
 ┣ 📂view
 ┃ ┣ 📜saved.js
 ┃ ┣ 📜search.js
 ┃ ┗ 📜snackbar.js
 ┗ 📜index.js
```
<br>

## ✔ 로또 Lv3 구현 목록

- [x] 가장 처음에는 저장된 영상이 없음으로, 비어있다는 것을 사용자에게 알려주는 상태를 보여준다.
- [x] 이후 페이지를 방문했을 때 기본 메인 화면은 내가 **볼 영상**들의 리스트를 보여준다.
- [x] 영상 카드의 이모지 버튼을 클릭하여 아래와 같은 상태 변경이 가능해야 한다.
  - [x] ✅ 본 영상으로 체크
  - [x] 🗑️ 버튼으로 저장된 리스트에서 삭제할 수 있습니다. (삭제 시 사용자에게 정말 삭제할 것인지 물어봅니다.)
- [x] 사용자가 버튼을 클릭했을 때 해당 행위가 정상적으로 동작하거나, 실패하였음을 `snackbar`를 통해 보여준다.
- [x] 본 영상, 볼 영상 버튼을 눌러 필터링 할 수 있다.

<br>

## 🎯 구현 목록 세부 정보

### 🚩 1. 페이지 방문시 저장된 비디오 불러오기

<img src="https://user-images.githubusercontent.com/11311739/111026153-38204b00-842c-11eb-8fc4-86c6e981e740.gif" alt="페이지 방문" style="zoom: 67%;" />

![image-20210313181430026](https://user-images.githubusercontent.com/11311739/111026154-3ce4ff00-842c-11eb-85e0-13b2c42e53b4.png)

<br>

### 🚩 2. 저장된 비디오의 '본 영상' 버튼 체크 기능

![본 영상버튼](https://user-images.githubusercontent.com/11311739/111026166-4bcbb180-842c-11eb-9d64-ef075092ef04.gif)
![image-20210313181748022](https://user-images.githubusercontent.com/11311739/111026169-4e2e0b80-842c-11eb-859c-1280b82698c0.png)

<br>

### 🚩 3. 저장된 비디오 제거 기능

![삭제버튼](https://user-images.githubusercontent.com/11311739/111026307-f512a780-842c-11eb-9d6a-bc6126437b6b.gif)
![image-20210313182009253](https://user-images.githubusercontent.com/11311739/111026316-fe9c0f80-842c-11eb-83f2-92e073352865.png)

<br>

### 🚩 4. 본/볼 영상 필터링 과정

<img src="https://user-images.githubusercontent.com/11311739/111026346-15dafd00-842d-11eb-8b42-e872a43f932a.gif" alt="페이지 방문" style="zoom: 67%;" />

![image-20210313182040139](https://user-images.githubusercontent.com/11311739/111026350-196e8400-842d-11eb-9b2d-083079c1e985.png)

<br>

## 💡 시도한 부분

1. 기능 구현을 마무리하고 리팩토링을 한 후, 다시 코드를 봤는데 여전히 어수선한 느낌이 있었습니다.
   또, 코드를 한눈에 파악하는데 어려움이 있었고, 고민 중에 전에 공부했던 **시퀀스 다이어그램** 방식을 이용해
   기능별 플로우차트를 그려보았습니다.

   확실히 그려보니 제가 만든 기능의 흐름을 한눈에 파악할 수 있었고, 
   미처 알아차리지 못했던 **중복되는 내용**과 **비슷한 기능의 순서가 다른 처리 과정** 을 파악하는데 많은 도움이 됐습니다.
   - **관련 커밋** : [cf11e2b](https://github.com/woowacourse/javascript-youtube-classroom/commit/cf11e2ba5990c8382d532578edcbc22d9e81308e) [820879e](https://github.com/woowacourse/javascript-youtube-classroom/commit/820879e9fe021d5c2ec5a20bd97240513a2b4355)
   - **[개선 전 플로우차트 보기](https://www.notion.so/Lv2-7e26a1ae03ae495eb567d306a27b0c51)**
  
<br>

2. 최근에 읽은 아티클에서 DOM 자체가 reflow되고 repaint되는 과정에서, 
   DOM 트리에서 변화되는 요소의 하위 DOM 요소들 전부 repaint 된다는 점을 인지했습니다.

   그런 부분에서, 저의 코드에서 template 자체가 **DOM을 조작하는 `innerHTML` 방식**으로 삽입되고 있어,
   이러한 비용을 줄어보고자, template 내부에 동적으로 삽입되는 요소가 적은경우
   template 대신 해당 부분에 `span` 태그와 `id`를 달아 적은 범위에서만 **DOM을 조작했습니다**
   - 관련 커밋 : [1f21dd1](https://github.com/woowacourse/javascript-youtube-classroom/commit/1f21dd16ab63858c1310acc294303014c9d5c6d0)

2021-03-13 10:14 UTC, hchayan commented on src/js/index.js
> +);
의존성 주입 방식을 사용하기 위해 위와 같이 사용했습니다.

2021-03-13 10:15 UTC, hchayan commented on src/js/controller/search.js
> +    if (isScrollUnfinished(scrollArgs, event.target.scrollTop)) return;
구조분해 할당을 한 값을 다시 새로운 변수로 받아, 파라미터 하나로 필요한곳에 전달해줬습니다.

2021-03-13 10:24 UTC, hchayan commented on src/js/model/storage.js
> +    this.#savedVideo.forEach(info => {
저장된 비디오의 정보를 가지고 있는 `this.#savedVideo()` 메서드를 조작하는 model의 메서드들이 실행될떄마다
getItem을 해 무결성을 지켜주려는 시도가 있었지만, 
매번 getItem과 JSON.parse를 수행하는 비용의 고려와 함께, 
아직은 무결성이 깨질만한 위협이 있는 부분이 없다고 판단해 사용하지 않았습니다.

2021-03-13 10:29 UTC, hchayan commented on src/js/api/youtubeAPI.js
> +      .catch(error => {
에러 처리에 대한 고민은 현재 진행형입니다 ㅠㅠ
많은 글들을 찾아보곤 있는데 앞서 작성중이라고 말씀해주신 에러에 관한 아티클을 기대하고 있습니다! 😄

2021-03-13 14:32 UTC, JaeYeopHan requested changes
수고하셨습니다! 코멘트 남겼어요~

---

> 또, 코드를 한눈에 파악하는데 어려움이 있었고, 고민 중에 전에 공부했던 시퀀스 다이어그램 방식을 이용해
기능별 플로우차트를 그려보았습니다.

좋은 시도네요! 이런 차트 없이도 directory 구조만으로 이해가 되면 더욱 좋겠네요!

2021-03-13 14:32 UTC, JaeYeopHan commented on index.html
> +              <button id="towatch-videos-button" class="btn mx-1">
type="button"?

2021-03-13 14:32 UTC, JaeYeopHan commented on index.html
> +            <button id="search-youtube-button" class="btn bg-cyan-500">
위 input은 type=search가 어울릴 것 같네요 ㅎㅎ

2021-03-13 14:32 UTC, JaeYeopHan commented on index.html
> +          <img
`alt` attribute에 대해 알아보면 좋을 것 같아요!

2021-03-13 14:32 UTC, JaeYeopHan commented on src/css/ui/modules/snackbar.css
> +  visibility: visible !important; /* Show the snackbar */
이거 전부 다 똑같던데, 다 같이 사용하는 css 인건가요?

2021-03-13 14:32 UTC, JaeYeopHan commented on src/js/api/youtubeAPI.js
> +    value && urlSearch.set(key, value);
value가 0일 경우에는 의도한대로 동작하지 않을 것 같은데, 맞나요?

2021-03-13 14:32 UTC, JaeYeopHan commented on src/js/api/youtubeAPI.js
> +      .catch(error => {
고민 자체도 👍 이고 어떤 고민인지도 궁금하네요!

2021-03-13 14:32 UTC, JaeYeopHan commented on src/js/api/youtubeAPI.js
> +    return fetch(youtubeSearchURL({ query, nextPageToken, max }))
async-await도 추천합니당

2021-03-13 14:32 UTC, JaeYeopHan commented on src/js/controller/modal.js
> +        event.target.closest(SELECTOR.MODAL_CLOSE)
이게 무슨 조건인가요?
모달 dimmed 클릭 시, 모달을 닫도록 해주는 것이 의도라면 event delegation, target, currentTarget을 활용해봐도 좋을 것 같아요~

2021-03-13 14:32 UTC, JaeYeopHan commented on src/js/controller/search.js
> +    if (isScrollUnfinished(scrollArgs, event.target.scrollTop)) return;
1. 이 코드만 특이하게 설명이 있는 이유가 있나요???
1-1. 설명이 필요하다고 생각하셨다면 왜 일지도? 고민해보면 좋을 것 같네요 ㅎㅎ
2. `isScrollUnfinished` 내부에서 다른 값이 필요하게 되었을 때, fetchVideo 부분과 내부 두 군데를 수정해줘야 하는데 구조 분해 할당 방식은 `isScrollUnfinished` 내부에서 진행하는 것도 괜찮지 않을까요?

2021-03-13 14:32 UTC, JaeYeopHan commented on src/js/index.js
> +);
파라미터로 전달하게 되면 순서에 의존하게 되는데요, object로 전달해보는 것도 한 번 고려하면 좋을 것 같네요!

2021-03-13 14:32 UTC, JaeYeopHan commented on src/js/templates/video-template.js
> +            <span class="watched ${
span보단 button이 어울리지 않을까요?

2021-03-13 14:32 UTC, JaeYeopHan commented on src/js/templates/video-template.js
> +            <button class="btn js-save-button ${save ? CLASS.INVISIBLE : ''}"
`type="button"`??

2021-03-13 14:32 UTC, JaeYeopHan commented on src/js/templates/video-template.js
> +                    target="_blank"
a tag에 target="_blank" property를 줘서 새 창으로 띄울 때 고려해야하는 이슈가 있는데 찾아보면 좋을 것 같아요! (hint: noopener)

2021-03-14 04:47 UTC, hchayan commented on src/js/controller/search.js
> +    if (isScrollUnfinished(scrollArgs, event.target.scrollTop)) return;
네 단순히 전달해주고 받아오는 파라미터의 개수에만 집중 하다보니 위와 같은 형태로 구현하게 된 것 같습니다.
`isScrollUInfinished`에 document를 통째로 전달해주되, 
`isScrollUInfinished` 내부에서 받아올 때 구조 분해 할당 방식으로 받아오는 형태로 변경했습니다!

2021-03-14 04:54 UTC, hchayan commented on src/js/api/youtubeAPI.js
> +      .catch(error => {
위와 같이 **fetch한 데이터를 가져오거나 입력 값에 대한 검증**과 같은 주요 기능에서는 에러 처리를 하는 것이 맞지만,
설명하기도 애매한 간단한 기능들(모델에서 데이터를 가지고 있는 변수에 push, pop 등등..)  까지 
에러 처리를 해주는게 맞나 싶은 생각이 구현을 하며 종종 고민되는 부분 인 것 같습니다.

해주자니 코드가 매번 에러처리해주느라 가독성이 약해지는거 같고, 불필요해보이는 에러 처리들도 있는것 같아,
이러한 처리에 대한 기준에 대해 많이 알아보고 있습니다! 😊

2021-03-14 05:13 UTC, hchayan commented on src/css/ui/modules/snackbar.css
> +  visibility: visible !important; /* Show the snackbar */
네 snackbar에 대한 우테코내 강좌에서 나와있던 예제입니다!

2021-03-14 05:21 UTC, hchayan commented on src/js/api/youtubeAPI.js
> +    value && urlSearch.set(key, value);
처음에 형태를 잡을땐 그랬지만, max result라는 숫자 속성도 추가되면서 해당부분의 고려를 미처 못한것같습니다.
value가 null이거나 undefined의 형태일때만 예외 처리하는 방식으로 개선하겠습니다.

2021-03-14 05:23 UTC, hchayan commented on src/js/api/youtubeAPI.js
> +    return fetch(youtubeSearchURL({ query, nextPageToken, max }))
이번에 프라미스 제대로 한번 써보고 싶어서 fetch과정을 프라미스로만 구현해봤습니다 ㅎㅎㅎㅎㅎㅎ 😁

2021-03-14 05:36 UTC, hchayan commented on src/js/controller/modal.js
> +        event.target.closest(SELECTOR.MODAL_CLOSE)
더 간단한 방법으로 구현해보겠습니다!

2021-03-14 05:40 UTC, hchayan commented on src/js/templates/video-template.js
> +            <span class="watched ${
이 부분때문에 cypress에서 테스트할때 `{force: true}` 를 일일히 붙여줬는데, 훨씬 좋은거같습니다!

2021-03-14 05:45 UTC, hchayan commented on src/js/templates/video-template.js
> +                    target="_blank"
말슴해주신내용을 찾아보다가
`nofollow`, `noreferror`, `noopener` 속성에 대해 새롭게 알게 되었습니다!

아직은, 어떤 것을 위한 속성들인지정도만 알았지만, 
웹페이지가 열리는 과정을 포함해서 좀 더 알아봐야 이 속성들의 필요성에 대해 확실히 인지할 수 있을거 같습니다!

2021-03-14 06:12 UTC, hchayan commented
## 주요 개선 내용
### 1. 의존성 주입 방식으로 controller에 model과 view object 형태로 전달 구현 ([리뷰링크](https://github.com/woowacourse/javascript-youtube-classroom/pull/37#discussion_r593757661))
순서 의존성이 개선되었고, 받아오는 파라미터의 개수도 줄일 수 일 수 있어서 model과 view를 관리하는데 용이해졌습니다!

- 관련 커밋 : 7871cab

<br>

### 2. 구조 분해할당 방식에 대한 잘못된 방향의 고민 개선 ([리뷰링크](https://github.com/woowacourse/javascript-youtube-classroom/pull/37#discussion_r593757017))
   - 관련 커밋 : 8d3f799

   1. **처음 작성한 코드의 형태**

       ```js
       // 기존 
       const $wrapper = document.querySelector("...")
       testFunction($wrapper);

       ----
       export const testFounction = (document) => {
        console.log(document.a, document.b, document.c)
       }
       ```

   2. **개선했던 코드의 형태 (잘못된 개선 (이번 리뷰))**

       ```js
       // 단순히 전달해주는 파라미터만 고려하다 나온 형태입니다.
       const {a, b, c} = document.querySelector("...")
       const args = {a, b, c}
       testFunction(args);

       ----
       export const testFounction = (args) => {  // 내부에서 필요한 args 정보다 달라주면 두군데에서 수정해야된다.
        console.log(args.a, args.b, args.c)
       }
       ```

   3. **이번 최종 개선 코드 형태**

       ```js
       // 이번 개선
       const $wrapper = document.querySelector("...")
       testFunction($wrapper);

       ----
       export const testFounction = ({a, b, c}) => {   // 올바른 구조 분해 할당 사용법
        console.log(a, b, c)
       }
       ```

<br>

### 3. modal 창 외부클릭 닫기 구현 방식 개선
   ```js
    window.addEventListener('click', ({ target }) => {
         if (target === this.#$modal || this.#modalClose.contains(target)) {
           this.#onModalClose();
         }
       });
   ```

2021-03-14 06:52 UTC, JaeYeopHan commented on src/js/controller/modal.js
> +        event.target.closest(SELECTOR.MODAL_CLOSE)
제 의도랑은 살짝 달랐지만 구현엔 여러가지 방법이 있으니 나중에 다른 방법으로도 시도해볼 수 있을 것 같아요~

2021-03-14 06:53 UTC, JaeYeopHan approved these changes
고생하셨습니다! 👏 👏 👏

2021-03-14 06:53 UTC, merged