[2단계 - 나만의 유튜브 강의실] 그루밍(강민경) 미션 제출합니다.
woowacourse/youtube-classroom pull request #44
Opened 2021-03-14 05:02 UTC by ddongule

안녕하세요! 리뷰어님! 그루밍입니다~!!! 🍎🍎 
2단계 미션도 인치(@hchayan)와 함께 구현했습니다!
미션 리뷰 요청 드립니다! ~~ 🐾

## 💻 나만의 유튜브 강의실 미션 2 요약
### 1. 구현한 기능 및 테스트
- [x] 가장 처음에는 저장된 영상이 없으므로, **비어있다는 것을 사용자에게 알려주는 상태**를 보여준다.
- [x] 이후 페이지를 방문했을 때 **기본 메인 화면은 내가 볼 영상들의 리스트**를 보여준다.
- [x] 영상 카드의 이모지 버튼을 클릭하여 아래와 같은 **상태 변경이 가능**해야 한다.
    - [x] ✅ 본 영상으로 체크
    - [x] 🗑️ 버튼으로 저장된 리스트에서 삭제할 수 있다. (삭제 시 사용자에게 정말 삭제할 것인지 물어봅니다.)
- [x] 사용자가 버튼을 클릭했을 때 해당 행위가 정상적으로 동작하거나, 실패하였음을 **snackbar**를 통해 보여준다.
- [x] 본 영상, 볼 영상 버튼을 눌러 **필터링** 할 수 있다.
### 2. 폴더 구조
```
├── api
│   └── youtubeAPI.js
├── constants
│   └── constant.js
├── controller
│   ├── modal.js
│   ├── saved.js
│   └── search.js
├── index.js
├── model
│   ├── storage.js
│   └── youtube.js
├── templates
│   └── video-template.js
├── utils
│   └── util.js
└── view
    ├── saved.js
    ├── search.js
    └── snackbar.js
```

### 📝 느낀점
- 1단계 느낀 점에도 작성했듯이, MVC 패턴을 활용해 미션을 구현해 만능 함수를 남발하지 않게 되어 기쁩니다. 다만 이 미션에 왜 MVC 패턴이 필요했는지 이 패턴을 활용해 미션을 구현함으로서 장단점은 무엇이 있을지에 대해서는 아직 고민 진행 중 입니다.
- (**반성**) 저는 뭔가 완성되고나면 어떤 한 부분을 다시 뜯어고치는 것을 두려워했던 것 같습니다. (아마.. 이거 건드리면 다른게 잘못되지 않을까?라는 것에 대한 두려움이었던 것 같습니다.) 하지만 이번에 리팩토링을 단단히 하면서 다시 기능 하나하나씩 살펴보고, 기능이 잘 돌아가더라도 개선할 부분을 찾아 해결하면서 이런 두려움을 조금씩 없앨 수 있었습니다. 또, 각 함수의 의존도를 낮추는 고민을 통해 이걸 건드리면 다른게 잘못되지 않을까 라는 고민을 조금 덜 수 있었습니다! 

### 🤔 궁금한 점
- `src/js/index.js`에서 parameter가 기본적으로 2개 이상, 많게는 5개까지 들어가고 있습니다. 이렇게 parameter가 많이 들어가는 것이 좋지 않다고 생각해 개선하고 싶습니다. model은 model대로 묶고, view는 view대로 묶는 방법을 고민해보긴 했지만, 더 복잡해 질 것 같아서 아래와 같이 만들었습니다. 혹시 더 좋은 방법이 있다면 조금 힌트를 주실 수 있을까요?
  ```javascript
  const searchController = new SearchController(
    youtubeModel,
    storageModel,
    searchView,
    savedView,
    snackBarView
  );
  const savedController = new SavedController(
    storageModel,
    savedView,
    snackBarView
  );
  const modalController = new ModalController(storageModel, searchView);
  ```
  - `src/js/api/youtubeAPI.js` 에서 video를 fetch하는 코드에서 error를 catch하는 부분이 뭔가 어색하다고 느껴집니다. 이렇게 내부에서 `alert`를 `return`하는 방식이 괜찮은 방식인지 여쭙고 싶습니다! 
  - 또, 수업을 들으면서 이 부분을 다른 API를 사용할 때 재사용할 수 있도록 추상화시킬 수 있다는 것을 배웠습니다. 이번 미션에서는 유튜브 API 말고는 다른 API를 사용하지 않을 것이라고 판단해 더 추상화는 진행하지 않았는데요, 확장성을 고려해 이런 부분도 추상화를 시켜주는 편이 나을까요? 

    ---
    (저번에 리뷰어님께서 다른 크루의 PR에 남겨주신 `추상화, 함수분리, 중복 제거의 tradeoff`에 대한 [동영상](https://www.notion.so/Model-View-Side-Effect-322fc77d2b80429fa7593a4768b3fc3b#d20638e831d940b594baeed477bf20b4)을 보았는데.. 되게 신선하면서도 저도 저렇게 만들고 있지는 않은가 하면서 반성도 많이 했습니다. 감사합니다!🥺)
  -  그리고 혹시 요 `api` 함수에 대해 다른 개선점이 있다면 알려주시면 개선해보도록 하겠습니다!

2021-03-15 16:58 UTC, ysm0622 requested changes
> (반성) 저는 뭔가 완성되고나면 어떤 한 부분을 다시 뜯어고치는 것을 두려워했던 것 같습니다. (아마.. 이거 건드리면 다른게 잘못되지 않을까?라는 것에 대한 두려움이었던 것 같습니다.) 하지만 이번에 리팩토링을 단단히 하면서 다시 기능 하나하나씩 살펴보고, 기능이 잘 돌아가더라도 개선할 부분을 찾아 해결하면서 이런 두려움을 조금씩 없앨 수 있었습니다. 또, 각 함수의 의존도를 낮추는 고민을 통해 이걸 건드리면 다른게 잘못되지 않을까 라는 고민을 조금 덜 수 있었습니다!

- 좋은 고민이네요! 고민과 관련된 좋은 강의하나를 소개해드릴게요.
- 인프런에 유인동님의 [함수형프로그래밍](https://www.inflearn.com/course/%ED%95%A8%EC%88%98%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D#) 강의를 한번 들어보시면 고민과 관련된 고민을 해결할 수 있을 것 같네요!
- 좀 길긴하지만 정말 추천하는 강의입니다 👍 

🤔 궁금한 점

> src/js/index.js에서 parameter가 기본적으로 2개 이상, 많게는 5개까지 들어가고 있습니다. 이렇게 parameter가 많이 들어가는 것이 좋지 않다고 생각해 개선하고 싶습니다. model은 model대로 묶고, view는 view대로 묶는 방법을 고민해보긴 했지만, 더 복잡해 질 것 같아서 아래와 같이 만들었습니다. 혹시 더 좋은 방법이 있다면 조금 힌트를 주실 수 있을까요?

- 왜 파라미터가 많아지는게 좋지 않다고 생각하셨나요? 그리고 파라미터가 왜 많이 들어가게 될수밖에 없었나요? 파라미터로 넘기지 않고 해결할 순 없을까요?

> src/js/api/youtubeAPI.js 에서 video를 fetch하는 코드에서 error를 catch하는 부분이 뭔가 어색하다고 느껴집니다. 이렇게 내부에서 alert를 return하는 방식이 괜찮은 방식인지 여쭙고 싶습니다!

- 어떤부분이 어색하다고 느껴지셨나요?

> 또, 수업을 들으면서 이 부분을 다른 API를 사용할 때 재사용할 수 있도록 추상화시킬 수 있다는 것을 배웠습니다. 이번 미션에서는 유튜브 API 말고는 다른 API를 사용하지 않을 것이라고 판단해 더 추상화는 진행하지 않았는데요, 확장성을 고려해 이런 부분도 추상화를 시켜주는 편이 나을까요?

- 필요할때 추상화를 하면 좋을것같아요. 👍 연습삼아 해보는것도 좋습니다.

2021-03-15 16:58 UTC, ysm-dev commented on src/js/api/youtubeAPI.js
> +  return URL.DUMMY_SEARCH + urlSearch.toString();
URLSearchParams 객체의 constructor 파라미터로 객체를 넣으면 됩니다. 👍

2021-03-15 16:58 UTC, ysm-dev commented on src/js/api/youtubeAPI.js
> +          `데이터 불러오기 실패! : 에러코드 - ${error.message} \n다시 검색해주세요!`
"API 요청"과 "API 요청 실패에 대한 에러처리" 두 로직을 분리하는게 좋을것같아요 👍

2021-03-15 16:58 UTC, ysm-dev commented on src/js/controller/saved.js
> +    handleVideosLoad($$(SELECTOR.VIDEO_IFRAME));
어떤 handle@@ 함수는 파라미터로 DOM을 넘기고 어떤  handle은 파라미터를 안받고 함수 안에서 $로 select하는데 어떠한 기준인가요? 👀

2021-03-15 16:58 UTC, ysm0622 commented on src/js/model/youtube.js
> +      };
함수로 분리해도 좋을것같아요. 👍

2021-03-15 16:58 UTC, ysm0622 commented on src/js/utils/util.js
> +  return [];
alert보다는 throw new Error로 에러를 뱉어주는게 더 자연스러울것같아요.

2021-03-15 16:58 UTC, ysm0622 commented on src/js/utils/util.js
>  };
이건 왜 필요한가요?

2021-03-20 06:11 UTC, ddongule commented on src/js/api/youtubeAPI.js
> +  return URL.DUMMY_SEARCH + urlSearch.toString();
오 헉 이렇게도 가능한지 몰랐습니다 그렇게도 작동을 할 수 있군요!!! 
앞으로 어떤 새로운 내용에 대해 공부할 때에 더 자세히 알아보고 사용해야겠습니다ㅠㅠ
감사합니다!! 🤭🤭🤭 말씀주신대로 변경했습니다!!

2021-03-20 06:55 UTC, ddongule commented on src/js/utils/util.js
> +  return [];
아아 말씀주신 `throw new Error`가 `alert`보다는 확실히 자연스럽네요! 
기능 구현에 힘쓰다보니 이런 오류 처리에 대해서는 깊게 고민해보지 않았던 것 같습니다. 앞으로는 더 자연스러운 흐름으로 코드를 구현할 수 있도록 하겠습니다! 감사합니다 😆

2021-03-20 07:08 UTC, ddongule commented on src/js/controller/saved.js
> +    handleVideosLoad($$(SELECTOR.VIDEO_IFRAME));
`handle-*` 네이밍은 이벤트가 발생했을 때, 어떤 것이 호출될지를 의미한다고 알고있습니다! 
음.. 미션을 구현할 때에 이것 외에 어떠한 명확한 기준을 가지고 `handle-*` 함수를 만들지는 않았던 것 같습니다.ㅠㅠ!!
target이 필요한 경우에만 DOM을 넘겨주고, 그렇지 않은 경우(`handleVideoButtons`, `handleFilteredVideos`)처럼 처음 DOM이 그려질 때 이벤트를 달아줄 때에는 인자 없이 함수를 만들었습니다. 하지만 인자가 없더라도 안에 내부에서 event를 받아 어떤 내용이 호출될지에 대한 로직을 수행하기 때문에 `handle-*` 이름을 붙였던 것 같습니다!!
 
```javascript
  #handleVideoButtons() {
    $(SELECTOR.SAVED_VIDEO_WRAPPER).addEventListener('click', ({ target }) => {
      if (
        target.classList.contains(CLASS.WATCHED) ||
        target.classList.contains(CLASS.LIKE)
      ) {
        this.#toggleVideoButtons(target);
      }

      if (target.classList.contains(CLASS.DELETE)) {
        this.#deleteVideo(target);
      }
    });
  }

```

2021-03-20 07:20 UTC, ddongule commented on src/js/model/youtube.js
> +      };
오 이렇게 api를 이용해 fetch해오는 내용이 다른 곳에 따로 쓰이지 않다보니.. 구현만 해놓고 더 보기좋게 만들 생각을미처 하지 못하고 있었습니다! 말씀주신대로 return하는 내용을 함수로 분리하니 훨씬 더 깔끔해지고 보기도 쉬워졌습니다! 앞으로도 꼼꼼히 신경써야겠네요! 감사합니다!😆😆 

```javascript
  getVideoInfosBySearch = async ({
    query,
    max = SEARCH.FETCH_VIDEO_LENGTH,
  }) => {
    const nextPageToken = this.#nextPageToken;
    const json = await api.fetchVideoItems({ query, nextPageToken, max });

    this.#nextPageToken = json.nextPageToken;
    this.#videoInfos = this.getVideoInfos(json.items);
  };

```

2021-03-20 08:34 UTC, ddongule commented on src/js/api/youtubeAPI.js
> +          `데이터 불러오기 실패! : 에러코드 - ${error.message} \n다시 검색해주세요!`
아아 이부분도 말씀주신대로 조금 더 명확히 기능을 구분하는게 좋을 것 같군요!
success했을 때와 fail했을 때의 로직을 분리해 api 함수를 조금 더 가볍게 만들었습니다! 감사합니다 😎😎!!

2021-03-20 09:12 UTC, ddongule commented on src/js/utils/util.js
>  };
이 내용은 String을 DOM으로 만들어주는 내용입니다! 
innerHTML의 성능보다 DOM parser를 쓰는게 성능면에서 조금 더 나은 것으로 알고있어서.. innerHTML을 피하려고 string을 DOM으로 만들어주고, 그 만들어준 내용을 붙이는 방식을 선택했습니다. 🥺!!
혹시 더 나은 방향이 있다면 조언해주실 내용이 있으실까요?! 호홋 ㅠㅅㅠ

2021-03-20 13:26 UTC, ysm0622 commented
푸시하셨나요?

2021-03-20 13:28 UTC, ysm0622 commented on src/js/utils/util.js
>  };
제가 잘못알고있을 수도 있지만, 제 생각엔 성능차이가 없을것 같다고 생각되는데요, 관련 레퍼런스가있을까요?

2021-03-21 03:28 UTC, ddongule commented
헉헉 제가 step3이랑 같이 진행하고 있다보니 cherry-pick으로 push해놨는데 push된 줄 알고 있었는데 반영이 안됐나봅니다ㅠㅠ!! 오류 해결해서 올려놓아보겠습니다 ㅠㅠ!!

2021-03-21 04:00 UTC, ddongule commented on src/js/utils/util.js
>  };
innerHTML과 parser를 사용하는게 모두 string을 parse하는 친구들이다보니 말씀주신대로 성능에 대한 비교는 찾기가 어렵네요ㅠㅠ..! innerHTML은 성능이 안좋다라는 말을 듣고 그럼 다른 애들을 사용하면 innerHTML보다는 낫겠지?! 라고 생각한 부분이 있었나봅니다..😔😔 ㅠㅠ 
createElement를 해서 appendChild하는 것과 같다고 착각하고 있었나봅니다ㅠㅠ DOM을 다루는 메서드들에 대해 조금 더 정리해보는 시간을 가져야겠다고 느꼈습니다! 이번 기회에 정확히 짚고 넘어가겠습니다 감사합니다!!🥺🥺

2021-03-21 14:49 UTC, ysm0622 commented on src/js/api/youtubeAPI.js
> +  const urlSearch = new URLSearchParams(queries).toString();
일반적으로 queryString 이나 queryParameters, queryParam 이라는 변수명을 많이 사용합니다 👍 

다음단계에서 수정하시죠! 고생하셨어요!

2021-03-21 14:49 UTC, ysm0622 approved these changes

2021-03-21 14:49 UTC, merged

2021-03-21 22:38 UTC, ddongule commented on src/js/api/youtubeAPI.js
> +  const urlSearch = new URLSearchParams(queries).toString();
아아 헉 그렇군요! 수정해서 반영하겠습니다! 감사합니다 🤩