[2단계 - 나만의 유튜브 강의실] 카일(임광열) 미션 제출합니다.
woowacourse/youtube-classroom pull request #45
Opened 2021-03-14 05:15 UTC by GwangYeol-Im

### Demo
- [데모 페이지](https://gwangyeol-im.github.io/javascript-youtube-classroom/)

### 🎯🎯 step2 강의실 관리 기능
- 가장 처음에는 저장된 영상이 없음으로, 비어있다는 것을 사용자에게 알려주는 상태를 보여준다.
-  이후 페이지를 방문했을 때 기본 메인 화면은 내가 볼 영상들의 리스트를 보여준다.
-  영상 카드의 이모지 버튼을 클릭하여 아래와 같은 상태 변경이 가능해야 한다.
    - ✅ 본 영상으로 체크
    - 🗑️ 버튼으로 저장된 리스트에서 삭제할 수 있습니다. (삭제 시 사용자에게 정말 삭제할 것인지 물어봅니다.)
- 사용자가 버튼을 클릭했을 때 해당 행위가 정상적으로 동작하거나, 실패하였음을 snackbar를 통해 보여준다.
- 본 영상, 볼 영상 버튼을 눌러 필터링 할 수 있다.

현재 메인 페이지 부분의 '볼 영상' 버튼과 '본 영상' 버튼을 토글로 판단하고 처리해놓았는데, 새로운 타입이 추가될 때마다 이런 식의 처리는 더 복잡한 로직을 생성할 여지가 있을 것 같습니다. 하지만 아직 이 부분의 타입 처리 관련해서 고민 중이라 해당 부분은 TODO 로 남겨 놓고 완료된 기능을 바탕으로 PR을 올리게 되었습니다 ! 이 점 감안하여 주시고 리뷰 주시면 감사하겠습니다 :)

2021-03-17 16:29 UTC, Vallista requested changes
안녕하세요! 카일님!
리뷰가 늦어져서 죄송합니다 ㅠㅠ 현재 프로젝트를 3개 진행하고 있어 프로젝트 마무리 기간이 맞물려 정신이 하나도 없네요 ㅠ
나중에 혹시 뵙게되면, 밥이라도 한끼... 대접하겠습니다... 흑

또한 이러한 상황에서 지속적인 모니터링이 쉽지 않아 피드백이 지연되고 리뷰 받으시는 분들 입장에서는 답답하셨을 것 같아요!
그래서, 앞으로는 리뷰 일정을 명확하게 전달드리도록 하겠습니다! 다음 리뷰를 금주 일요일 (3/21) 전에 올려주시면 일요일에 일괄 피드백을 드리도록 하겠습니다.. ㅠ

코드 리뷰는 이전과 동일하게 UX/UI, 전반적인 코드를 확인하도록 하겠습니다!

---

첫 번째로 UX/UI 쪽 피드백입니다.

1. 검색 내 팝업의 저장, 저장취소의 버튼 위치가 레이아웃마다 다른 부분이 있어서 UI적으로 좋지 못합니다! 동일한 위치가 아니게 될 경우 클릭에 오차가 있을 수 있어 보입니다!

![스크린샷 2021-03-18 오전 12 34 53](https://user-images.githubusercontent.com/6455767/111498353-38e71300-8785-11eb-82a6-31ba2ddb5ba0.png)

2. 볼 영상에서 동영상 하단의 버튼 위치가 각 동영상 마다 상이합니다!

![스크린샷 2021-03-18 오전 1 01 19](https://user-images.githubusercontent.com/6455767/111498649-78156400-8785-11eb-941a-df007a307172.png)

3. 저장 취소를 했음에도 저장 버튼으로 돌아오지 않습니다!

4. 1단계에서 피드백 드린 부분에서 검색 버튼에 대한 변경을 해주셨는데요! 해당 부분은 레이아웃에 대한 차별점을 두어야 할 것 같습니다! 테스트만 없애서는 조금 부족한 느낌이네요! (해당 부분은 코드 라인에 피드백 해두었습니다!)

![스크린샷 2021-03-18 오전 1 05 31](https://user-images.githubusercontent.com/6455767/111499205-0be73000-8786-11eb-911a-f0607c25c778.png)

---

두 번째로 전반적인 코드 피드백입니다!

1. constant로 정의된 메시지를 export 형태로 한번에 정의를 하셨는데요! 해당 부분은 정의된 메시지마다 export를 각각 붙여주는게 더 좋지않을까요? 메시지가 길어짐에 따라 두 번 메시지를 사용하게되면 코드가 비대해질 것 같아보입니다!

2. 각각의 메서드가 바로 param을 받아 적용하는 로직들이 있는데, 이렇게 되면 혹시나 해당 param이 없을 경우 함수가 작동이 되지 않을 것 같습니다! 각각의 메서드에 맞는 예외처리가 필요해보입니다!

3. [...this.value] 형태를 많이 사용하셨는데, 두 가지의 배열을 합치는 작업이 아니라면, this.value.map, filter 등으로 사용해도 문제가 없어보입니다!

4. keyframes는 한 파일에 정리해두는 건 어떨까요? 현재 snackbar에 있는 이름이 광범위하게 쓰일 법한 이름이여서, 모아두는 건 좋아보입니다.

5. showSnackBar에 clearTimeout이나 heap 형태로 배열을 만들어 이벤트를 관리하지 않는다면 스낵바 이벤트에 버그가 있을 것 같습니다! 관련해서 코드 라인에 답변 달아두었습니다!

6. ({ target }) 형태로 추출해서 쓰는 이유가 있을까요? 굳이 한 개의 데이터를 가져와 쓸 것이라면, parameter 하나로 넘겨도 괜찮을 것 같습니다 :)

7. 그 외에 상세한 부분은 코드 라인에 리뷰로 달아두었습니다!

---

2단계 미션도 수고 많으셨습니다!
코드 리뷰 부분 확인 부탁드립니다!

2021-03-17 16:29 UTC, Vallista commented on README.md
> +- [x] 동영상 검색 버튼 레이아웃 수정
검색의 스타일이 기존 본 영상, 볼 영상과 여전히 비슷하여 조금 햇갈릴 여지가 있을 것 같습니다!

[브콜님이 구분해두신 레이아웃](https://beutube.netlify.app/) 처럼 원형으로 구별을 주는건 어떨까요?

2021-03-17 16:29 UTC, Vallista commented on index.html
> +              <button id="search-button" class="btn mx-1">🔍</button>
위치상으로 구분하는 건 어떨까요? 볼 영상과 본 영상은 왼쪽에 있고, 검색은 오른쪽에 있다던지.. 레이아웃 형태가 다르다던지..

2021-03-17 16:29 UTC, Vallista commented on index.html
> +      <div id="snack-bar" class="snack-bar"></div>
class도 같이 있는 이유가 있을까요?

2021-03-17 16:29 UTC, Vallista commented on index.html
> +        <div id="modal-inner" class="modal-inner p-8">
modal-inner는 사용되지 않는 것 같은데, id와 class modal-inner가 같이 제공되는 이유가 있을까요?

2021-03-17 16:29 UTC, Vallista commented on src/css/ui/modules/snackbar.css
> +.snack-bar {
id에 스타일을 같이 먹이면 되지 않을까요?

2021-03-17 16:29 UTC, Vallista commented on src/css/ui/modules/snackbar.css
> +@-webkit-keyframes fadein {
fade-in
fade-out

등으로 네이밍을 구분하는 건 어떨까요? 아니면 camel case나.
추후 ease-out등의 이벤트가 나오면 

fadeeaseout이 되는데 보기 어렵지 않을까요?!

2021-03-17 16:29 UTC, Vallista commented on src/js/handlers/modeChange.js
> +function handleModeChange({ target }) {
{ target } 으로 object 묶어준 이유가 있을까요?

2021-03-17 16:29 UTC, Vallista commented on src/js/states/videoInfos.js
> +    const newVideoInfos = [...this.value].filter(
...this.value로 하는 이유가 있을까요!? 새로운객체를 만들기 위함인가요?!

2021-03-17 16:29 UTC, Vallista commented on src/js/states/videoInfos.js
>    set(newVideoInfos) {
어떤것에 대한 set을 하는지 조금 더 명확하게 함수명을 지으면 좋을 것 같습니다!

2021-03-17 16:29 UTC, Vallista commented on src/js/states/videoInfos.js
> +    const newVideoInfos = [...this.value].filter(
filter를 사용하면 새로운 객체가 만들어지므로 해당 부분은 this.value로 쓰면 안될까요?

2021-03-17 16:29 UTC, Vallista commented on src/js/viewControllers/app.js
> +  setTimeout(() => {
setTimeout을 사용하니, clearTimeout으로 이전에 있던 setTimeout에 대한 객체를 초기화 해주어야 할 것 같습니다!
이렇게 되면 이후에 snackbar의 애니메이션에 무언가 문제가 생길 것 같습니다!

snackbar를 호출 할 때 마다, 3초.. 3초.. 3초.. 후 이벤트가 발생하니 새로운 이벤트가 실행되도 3초가 되면 해당 이벤트가 시작하고 3초가 아닌, 이전에 눌렀던 3초 이벤트에 의해서 영향이 있을 것 같습니다!

2021-03-17 16:29 UTC, Vallista commented on src/js/states/videoInfos.js
> +    const newVideoInfos = [...this.value].map(videoInfo =>
여기도 ...this.value를 하는 목적이 없어보입니다!

2021-03-17 16:29 UTC, Vallista commented on src/js/templates/videoList.js
> +function createVideoSnippetTemplate({ id, snippet }, buttonListTemplate) {
buttonListTemplate이라고 정의해놓기보다, 범용적으로 사용할 수 있도록 이름을 명명하는 건 어떨까요?

2021-04-01 09:39 UTC, GwangYeol-Im commented on src/css/ui/modules/snackbar.css
> +.snack-bar {
수정했습니다 !

2021-04-01 09:41 UTC, GwangYeol-Im commented on index.html
> +        <div id="modal-inner" class="modal-inner p-8">
snack-bar 와 같은 맥락이긴 한데, 개인적으로 선택자를 부여하는 기준은 이렇습니다.

- id: 하나의 엘리먼트를 DOM 요소로 셀렉팅해올 때
- class: css 처리
- js prefix class (e.g. `js-class-name`): 여러개의 엘리먼트를 DOM 요소로 셀렉팅해올 때

혹시 리뷰어 님께서는 어떤 기준으로 선택자를 부여하시나요?

2021-04-01 09:42 UTC, GwangYeol-Im commented on index.html
> +      <div id="snack-bar" class="snack-bar"></div>
해당 부분 삭제 했습니다 ㅎㅎ

2021-04-01 09:42 UTC, GwangYeol-Im commented on index.html
> +              <button id="search-button" class="btn mx-1">🔍</button>
동의합니다! 레이아웃 수정했습니다~

2021-04-01 09:43 UTC, GwangYeol-Im commented on src/css/ui/modules/snackbar.css
> +@-webkit-keyframes fadein {
맞습니다. 이때 체력관리를 못해서 그런지 확실히 제정신이 아니었나보네요.. 기초적인 실수라고 생각합니다 ㅠㅠ

2021-04-01 11:06 UTC, igy95 commented on src/js/handlers/modeChange.js
> +function handleModeChange({ target }) {
해당 함수는 이벤트 리스너의 핸들러 함수로써, 이벤트 객체를 받아 해당 target을 바로 사용하기 위함이었습니다. (분해 할당)
이 프로젝트에서는 핸들러를 따로 분리해주는 시도를 했는데, 아무래도 함수 전후반에 걸쳐 논리의 흐름을 따라가기 어려워보이네요. 다음에 구조를 잡을 때는 해당 사항도 고려해 보겠습니다.

2021-04-01 11:06 UTC, igy95 commented on src/js/states/videoInfos.js
> +    const newVideoInfos = [...this.value].filter(
`set` 으로 선언한 자료 구조를 배열 메소드로 가공하기 위해 타입을 바꿔줄 필요가 있었는데 그 시점이 잘못되었다고 생각합니다. 여기서 고쳐보려고 했지만, 의미없는 중간 변수만 생성할 것 같아 다음부터는 배열로 자료구조를 초기화하기로 하였습니다!

2021-04-01 11:06 UTC, igy95 commented on src/js/states/videoInfos.js
>    set(newVideoInfos) {
들어오는 매개변수가 `set` 함수의 뒤에 들어오기 때문에 해당 이름만으로 명시적일 수 있다고 생각했습니다.
사용하는 시점에서도 `something.set(newSomething)` 으로 괜찮다고 생각했고 state 객체의 특성상 다른 것을 `set` 할 가능성은 없다고 생각했습니다.

2021-04-01 11:06 UTC, igy95 commented on src/js/templates/videoList.js
> +function createVideoSnippetTemplate({ id, snippet }, buttonListTemplate) {
`buttonList` 라는 말이 특정한 것에 귀속되지 않아 보이는데 혹시 추천해주실만한 네이밍이 있을까요~?

2021-04-01 11:06 UTC, igy95 commented on src/js/viewControllers/app.js
> +  setTimeout(() => {
좋은 지적입니다. 해당 부분은 수정하겠습니다 :)

2021-04-06 01:23 UTC, GwangYeol-Im commented on src/js/states/videoInfos.js
> +    const newVideoInfos = [...this.value].filter(
다시 코드를 살펴본 결과, 임시방편으로 중간 변수를 넣어주게 되었습니다 :)

2021-04-06 06:21 UTC, Vallista commented on index.html
> +        <div id="modal-inner" class="modal-inner p-8">
저도 비슷한 형태로 가져오긴 합니다만! 전역적으로 modal-inner 는 하나밖에 없으므로 여기서는 id하나만 쓰여도 괜찮다고 생각합니다 :)

2021-04-06 06:22 UTC, Vallista commented on src/js/states/videoInfos.js
>    set(newVideoInfos) {
set이 하나만 있는 상황에서는 괜찮을 수 있는데 추후 사이즈가 커지면 함수 명 변경이 일어나게 되니, 사용처에서 수정을 해주게 되겠군요..
저는 함수를 최초 사용할 때 사용처에서는 변경할 필요 없이, 함수 구현체에서만 수정을 해주면 된다는 장점을 가장 크게 이용했으면 좋겠습니다 :)

2021-04-06 06:23 UTC, Vallista commented on src/js/templates/videoList.js
> +function createVideoSnippetTemplate({ id, snippet }, buttonListTemplate) {
createVideoSnippetTemplate 함수의 parameter로 buttonListTemplate을 받는게 조금 이상해서요!
videoSnippet과 buttonList는 무슨 상관이 있고... 왜 template을 받야하는지.. 흠

2021-04-06 06:24 UTC, Vallista commented on src/js/templates/videoList.js
> +function createVideoSnippetTemplate({ id, snippet }, buttonListTemplate) {
아니면 조금 normalize하게 접근해서 오히려 template이 낫지않을지.. (param이니 어떤 template이 들어와도 소화할 수 있어야 하니까요!)

2021-04-06 06:26 UTC, Vallista approved these changes
전반적으로 코드리뷰 사항을 잘 적용해주셔서 감사합니다 👍 
다른 부분은 딱히 피드백 드릴만한 부분이 없네요!

수고하셨습니다!

2021-04-06 06:26 UTC, merged

2021-04-06 09:19 UTC, GwangYeol-Im commented on src/js/states/videoInfos.js
>    set(newVideoInfos) {
@Vallista 동의합니다 ! 해당 리뷰 주신 부분 유의하여 3단계에 반영토록 하겠습니다~

2021-04-06 09:20 UTC, GwangYeol-Im commented on src/js/templates/videoList.js
> +function createVideoSnippetTemplate({ id, snippet }, buttonListTemplate) {
아... 그런 의도에서 주신 리뷰였군요! 해당 부분 고민해서 수정해볼게요 :)