[3단계 - 나만의 유튜브 강의실] 엘라(김현주) 미션 제출합니다.
woowacourse/youtube-classroom pull request #55
Opened 2021-03-17 15:22 UTC by HyuuunjuKim

ㅎ ㅎ 유투브 3단계 미션을 들고 나타난 엘라입니다😎😎😎
데모 페이지 https://classroom-mission.firebaseapp.com/

## 🤳 stpe3(유저 경험) 기능 구현 사항
- [x] 👍 좋아요 버튼을 누른 데이터만 필터링해서 보여줄 수 있는 메뉴를 만든다.
  - [x] 👍 좋아요 버튼을 누른 경우, 로컬에서 데이터를 변경한다.
  - [x] 👍 좋아요 버튼을 다시 클릭해서 해지할 수 있어야 한다.
- [x] 스크롤 페이징 방식을 이용해서 Lazy loading을 개선한다. -> 이전 단계에서 구현
- [x] 반응형 웹: 유저가 사용하는 디바이스의 가로 길이에 따라 검색결과의 row 당 column 갯수를 변경한다.
  - youtubeCard.css 파일에 있는 .video-wrapper의 css 속성 중 grid-template-columns의 속성을 auto-fill에서 아래의 요구사항에 맞게 변경한다.
    - 1280px 이하: 4개
    - 960px 이하: 3개
    - 600px 이하: 2개
    - 400px 이하: 1개

## 👀 미리보기
-  👍좋아요 누른 영상 버튼 클릭시 `likeType`이 `liked`인 `videoInfos`만 보여준다.
<img src="https://user-images.githubusercontent.com/43339385/111490162-21f0f280-877e-11eb-810a-387704cea07a.png" width="660">

- 디바이스 가로 길이에 따라 검색 결과의 row당 알맞은 column 갯수만큼 보여준다.

<img src="https://user-images.githubusercontent.com/43339385/111490925-c07d5380-877e-11eb-8b5a-fd8687ca6075.png" width="400" height="400">        <img src="https://user-images.githubusercontent.com/43339385/111491120-f15d8880-877e-11eb-9c54-8ba8214520b6.png" width="260" height="400">

항상 디테일한 피드백 너무 감사드립니다😁 이번에도 잘 부탁 드리겠습니다❗❗❗

2021-03-18 09:02 UTC, HyeonaKwon requested changes
안녕하세요! 구조를 잘 잡아놓으니 코드 수정할 것도 별로 없는 것 같아 보기 좋네요! 👍 
UX 개선점으로 하나만 말씀드리면, 좋아요 눌렀을 때 렌더링이 다시되어서 영상이 깜빡거리는 현상이 있는데 요거만 개선해보면 좋을 것 같아요!

2021-03-18 09:02 UTC, HyeonaKwon commented on src/js/viewControllers/app.js
> +  }
```javascript
const targetType = videoListType === 'liked' ? 'likeType' : 'watchType';
const filteredVideoInfos = [...videoInfos].filter(
    videoInfo => videoListType === videoInfo[targetType]
);
```

요렇게도 할 수 있겠네요!

2021-03-22 12:26 UTC, HyuuunjuKim commented on src/js/viewControllers/app.js
> +  }
호곡 이런 방법이 있었군요~!~!!!!😮😮😮 감탄하고 갑니다 현아님ㅎ ㅎ 수정했습니다. 

감사합니다❗❗❗

2021-03-22 12:44 UTC, HyuuunjuKim commented
좋아요 버튼 클릭 할 때 좋아요 버튼 상태만 변하게 하고 싶었는데,,,,,
좋아요 버튼을 target으로 잡아놓고 '이제 좋아요 버튼을 어떻게 잡아야하지,,?' 하는 이상한 고민을 하다가 video 하나 전체를 새로 렌더링하는 이상한 로직을 구현해 놓았네요 허허😂😂😂

좋아요 눌렀을 때 전체 렌더링 안되게 수정했습니다. 감사합니당 ㅎ ㅎ🥰

2021-03-22 13:40 UTC, HyeonaKwon approved these changes
수정하신 부분 확인했습니다 :) 미션 수행하느라 고생하셨습니다!

2021-03-22 13:40 UTC, merged

2021-03-30 02:36 UTC, HyuuunjuKim commented on src/js/viewControllers/app.js
> +        { ...videoInfo, watchType: 'toWatch', likeType: 'toLike' },
지금 와서 보니 이런 'toWatch', 'toLike' 같은 부분도 상수화를 해줘야했나 하는 생각이 든다.

2021-03-30 02:38 UTC, HyuuunjuKim commented on README.md
> -- [ ] 동영상 로딩 최적화
엇 x표시 안했네,,ㅎㅎ,,

2021-04-26 16:39 UTC, HyuuunjuKim commented
# 학습로그
## 함수 표현식 vs 함수 선언문
- https://hjuu.tistory.com/13

## 태그
- 함수 표현식, 함수 선언문