[2단계 - 나만의 유튜브 강의실] 그루밍(강민경) 미션 제출합니다.
woowacourse/youtube-classroom pull request #62
Opened 2021-03-22 00:33 UTC by ddongule

안녕하세요 리뷰어님!
3단계 미션을 제출하러 온 그루밍입니다~!🤓
아직 3단계 구현을 마무리 못한채로 다음 미션을 시작해버려서 미션 제출이 늦었습니다..! ㅠㅠ
앞으로 약속된 미션 제출 시간을 놓치지 않도록 더 노력하겠습니다!
항상 꼼꼼한 리뷰 해주셔서 배우는 내용이 정말 많습니다. 늘 감사합니다!
마지막 3단계 미션 리뷰도 잘 부탁드립니다! 감사합니다🥺

## 💻 나만의 유튜브 강의실 미션 3 요약

### 1. 구현한 기능 및 테스트
- [x] 👍 **좋아요 버튼을 누른 데이터만 필터링**해서 보여줄 수 있는 메뉴를 만든다.
  - [x] 👍 좋아요 버튼을 누른 경우, 로컬에서 데이터를 변경한다.
  - [x] 👍 좋아요 버튼을 **다시 클릭해서 해지**할 수 있어야 한다.
- [x] 스크롤 페이징 방식을 이용해서 **Lazy loading**을 개선한다.
- [x] **반응형 웹**: 유저가 사용하는 디바이스의 가로 길이에 따라 검색결과의 row 당 column 갯수를 변경한다.
  - [x] youtubeCard.css 파일에 있는 .video-wrapper의 css 속성 중 grid-template-columns의 속성을 auto-fill에서 아래의 요구사항에 맞게 변경한다.
  - [x] 1280px 이하: 4개
  - [x] 960px 이하: 3개
  - [x] 600px 이하: 2개
  - [x] 400px 이하: 1개

### 📹 구현한 내용에 대한 화면 capture
**1. 좋아요 기능**
   ![thumbs_up](https://user-images.githubusercontent.com/26598561/111923751-fe160f80-8ae3-11eb-8e88-fa8224290eb9.gif)

**2. Lazy scroll 기능**
  ![lazy_scroll](https://user-images.githubusercontent.com/26598561/111923802-45040500-8ae4-11eb-8651-1ef23b42295a.gif)

**3. 반응형 웹** 
![viewport](https://user-images.githubusercontent.com/26598561/111923866-ad52e680-8ae4-11eb-8cb3-569918b7da17.gif)

### 2. 폴더 구조 
(2단계 구조랑 동일합니다!)
```
├── api
│   └── youtubeAPI.js
├── constants
│   └── constant.js
├── controller
│   ├── modal.js
│   ├── saved.js
│   └── search.js
├── index.js
├── model
│   ├── storage.js
│   └── youtube.js
├── templates
│   └── video-template.js
├── utils
│   └── util.js
└── view
    ├── saved.js
    ├── search.js
    └── snackbar.js
```

### 🧐 저번 PR에 말씀주셨던 내용에 대해 다시 고민해 본 점, 다시 궁금한 점
- **함수의 의존성 관련 고민**
  알려주신 함수형 프로그래밍 강의를 조금씩 듣고 있습니다! 좋은 강의 추천해주셔서 감사합니다! 🥺 
  천천히 들으면서 함수에 대한 기본기를 다지고 또 의존성에 대한 고민도 점차 해결해나가겠습니다! 감사합니다!
- **Error Catch**
   LocalStorage에서 Item을 가져오는 것은 사용자가 고민해야 할 문제가 아닌데, `alert`를 이용해 사용자에게 문제를 알려주는 것이 자연스럽지 못하다고 느꼈습니다. 이는 개발자가 알아야 할 문제이므로, console에 에러를 남겨주는 것이 더 좋다고 생각했고, 그렇게 변경했습니다.
  (+) throw new Error가 새로운 에러를 만들어 보여주는 역할인 줄 알고있었는데, Error 객체를 일부러 만들어 내 동작을 멈추게 한다는 것을 배웠습니다. 그러므로 `catch()` 문 안에서 throw new Error를 하는 것이 아니라, `Try` 문에서 제가 원하는 상황이 아닐 때 일부러 Error를 throw하고, 그 내용을 catch에서 잡는 것이 더 좋은 방향인 것 같아 그렇게 변경했습니다. 이 부분은 제가 제대로 공부하지 않고 사용했던 부분이라 더 어색하게 느껴졌던 것 같습니다. ㅠㅠ 이번 기회에 Error 객체에 대해 조금 더 알아갈 수 있어서 좋았습니다!
- **Lazy Loading**
  이번에 공부하면서 Lazy Loading에 대해 알게 되었는데, 로딩을 기다리는 iframe들의 data속성에 src를 넣어두고, scroll 이벤트에 따라 data-src의 내용을 src에 넣어서 로딩하는 방법을 선택해 구현했습니다. 제 컴퓨터가 느린건지(?)ㅠㅠ 로딩 늘어지면서 웹이 아주 느려지는 현상이 있었는데, 이 내용을 적용하면서 확연히 빨라진 웹의 동작을 볼 수 있어서 기분이 좋았습니다.😚 
- **parameter가 많아지는 고민**
   음.. 함수에 들어가는 parameter가 많아지면 그 함수가 의존하는 parameter들이 많아져 좋지 않다고 생각했습니다. 들어가는 parameter에 변경이 일어났을 때, 그에 의존하는 함수 또한 변경될 가능성이 커지기 때문입니다. 원래 `Controller`에 `Model`, `View` 두 가지의 parameter만 넣으려고 했었는데, 미션을 구현하면서 Model과 View가 커져 분리하게 되면서 parameter가 많아지게 되었습니다. parameter로 넘기지 않으려면... Controller 내부에서 직접 Model과 View를 불러내는 방법이 있는데... 어차피 같은 의존성을 가지게 될 것 같아서 좋지 않아보입니다. ㅠㅠ 아직도 고민중이지만 반짝이는 해결책을 찾지는 못했습니다. ㅠㅠ

이번 유튜브 미션을 통해서 MVC 패턴을 적용해보면서 `Class`를 조금 더 유용하게 사용할 수 있게 되었고, API를 Fetch해 필요한 내용을 동기적으로 받아오고, 사용할 수 있게 되었습니다! 시간이 조금 더 있었더라면.. 다크 모드라던지 더 나은 사용자 경험에 대해  더 고민해보고 또 구현해볼 수 있었을텐데, 그러지 못한 부분은 조금 아쉽습니다 ㅠㅠ.. 늦어진 만큼.. 더 열심히하는 모습 보여드리겠습니다~!! 
마지막으로 3단계 리뷰 잘 부탁드립니다! 감사합니다 >__< 🐤 🐤

2021-03-23 17:07 UTC, ysm0622 requested changes
피드백 드릴게 많지 않네요!

코드에 일관성이 있어서 너무 좋습니다 👍

2021-03-23 17:07 UTC, ysm0622 commented on src/js/model/storage.js
> +    return (this.#filterOption = newFilter);
setter 에서는 굳이 return 문을 넣지 않아도 될것 같아요 👍

2021-03-23 17:07 UTC, ysm0622 commented on src/js/templates/video-template.js
> +              return `<a class="chip ml-2">${keyword}</a>`;
한줄로작성해도 될것같아요 ㅎㅎ

2021-03-23 17:07 UTC, ysm0622 commented on src/css/ui/modules/youtubeCard.css
> +}
👏 👏 👏 👏 👏

2021-03-23 17:43 UTC, ddongule commented on src/js/model/storage.js
> +    return (this.#filterOption = newFilter);
헉 그렇군요! get과 같이 쓰다보니 제가 헷갈려서 이렇게 넣었나봅니다.😳😳 
다음부터는 더 꼼꼼하게 확인해서 실수를 줄이도록 하겠습니다! 감사합니다!!👍

2021-03-23 17:44 UTC, ddongule commented on src/js/templates/video-template.js
> +              return `<a class="chip ml-2">${keyword}</a>`;
오.. `{return ... }`을 없애고 한 줄의 line으로 만들게 되면 더욱 가독성이 높아지겠군요!!!
미처 생각지 못했었는데 세심한 부분까지 신경써주셔서 감사합니다!! 🥺🥺!!

2021-03-23 17:46 UTC, ddongule commented
아직 미숙한 코드인데도 세심하게 리뷰 남겨주셔서 정말 감사합니다🤩🤩!!
3단계 리뷰 반영해 올려놓았습니다!! 감사합니다아~!!

2021-03-24 02:08 UTC, ysm0622 approved these changes
3단계까지 고생하셨어요! 👏 👏 👏 👏 👏 

나날이 개선되는 모습이 눈에 보입니다 👍

2021-03-24 02:08 UTC, merged

2021-03-30 03:21 UTC, ddongule commented
# 💊03월 30일 Self Review
`preview`
나만의 유튜브 강의실에서는 인치와 함께 MVC 패턴을 적용해 미션을 구현했다.
MVC 패턴이 `Model` - `View` - `Controller` 이라는 것은 알고 있었지만, 안의 세부 로직이 어떻게 돌아가는 지에 대해서는 무지했기 때문에 패턴을 적용해보면서 그 안의 세부 로직을 만들어나가는 것이 재미있었다.
그 중에서 어려웠던 내용은 `Modal`과 `View`가 서로 분리된 것에 대해서는 잘 알 수 있었는데 `Controller`와 `View`의 역할이 가끔 헷갈리는 경우가 있었다. 서로 맞물려 돌아가는 형태이다보니, 어디까지가 각자의 역할인지에 대해 고민을 많이 했다. 페어인 인치가 많이 도와줘서 역할을 잘 분리할 수 있었다. 
새로이 배운 내용은 throttle과 lazy loading이 있다. throttle은 snackbar를 만들면서 배웠고, lazy loading은 유튜브를 불러올 때에 쓰면서 배웠다. 두가지 다 새로운 내용이라 조금 더 연습이 필요해 보인다.

### 1. 내가 고민한 구조는 1달이 지난 지금 봐도 명확해 보이는가? 그리고 한 단계 더 추상화해서 분리할 수 있는 부분은 없는가?
구조 자체는 명확해 보이지만, Mdoel과 View에 비해 Controller가 각 역할이 점점 비대해지는 것을 볼 수 있었다. 지금 subway 미션을 하면서 class 상속에 대해 조금 더 알게 되었는데, 이부분을 적용해 같은 역할을 하는 부분을 core Component로 묶어도 좋을 것 같다는 생각을 했다. 

### 2. 모듈화, 계층화가 잘 이루어졌는가?
전체적으로 봤을 때에는 잘 이루어 진 것 같지만, utils에 있는 내용이나 세부 templates들을 조금 더 명확히 구분해 파일로 빼내도 좋을 것 같다.

### 3. 상수화가 적절히 이루어졌는가?
상수화를 과도히(?) 한 것 같기도 하다. url, message들 뿐만 아니라 ClassName, Id 등과 같은 Selector도 모두 상수화시켰다. 
subway 미션을 진행하면서는 Selector와 같은 친구들은 따로 상수화시켜주고 있지는 않은데, 아직까지 어떤 것이 더 낫다고 판단하지 못하겠다. 두가지 모두 장단점이 거의 비슷한 수준에서 있는 것 같다.
무언가.. 더 좋은 상수화 방법이 있을 법도 한데 한번 찾아보고, 고민해봐야겠다.

### 4. 예외를 위한 고민이 적절한가?
유튜브 미션 구현을 위해 API를 사용하면서 사용자가 알아야 할 예외와 그렇지 않아야 할 예외가 있다는 것에 대해 조금 더 명확히 알 수 있었다. 어떤 예외는 console에만 찍혀도 되고, 어떤 예외는 사용자들에게 보여주어서 잘못된 요청을 시정하게 만들어야 한다. 이 두 차이점에 대해 배울 수 있었다. 
그런데 예외를 얼마나 꼼꼼히 해야하는 지에 대해서도 고민이 든다. Back단에서 처리해주는 내용을 Front에서 얼마나 처리를 해주어야하는지, 사용자를 얼마나 믿고 얼마나 믿지 못해야하는지 등의 고민이다. 앞으로 미션을 진행하면서 더 고민을 해야 할 부분인 것 같다. 

### 5. 그 때는 보이지 않았지만 지금은 보이는게 있는가?
추상화를 잘 모르기도 했고, 아무리 찾아봐도 개념은 알겠지만 어떻게 적용하는 지 잘 감이 오지 않았었는데, 이제 유튜브 미션을 돌아보니 추상화를 할 수 있을 만한 구석이 보인다!! (정말 신기하다!! 꺅!!) 
추상화에 대해 어렴~풋이 알게 된 느낌! 이래서 사람들이 추상화를 하는구나- 이런 느낌을 받고 있다. 
아무것도 없는 바닥부터 시작해보기도 하고, 또 몇가지 패턴을 적용해보면서 구조에 대한 시야를 넓혀나가고 있는 것 같다.
나름 뿌듯하지만, 아직 갈 길이 멀다 🥺

2021-04-26 12:40 UTC, ddongule commented
# 🍯 그루밍의 학습로그
## 🐝 [Throttle, Debounce] - 3

**내용**
- **Throttle** 
  - 이벤트가 일정한 주기마다 발생할 수 있도록 하는 기술
  - 마지막 함수가 호출된 후, 일정 시간이 지나기 전에 다시 호출하지 않도록 함
  - ex) Snack Bar
- **Debounce**
  -  연이어 호출되는 함수 중, 가장 마지막 혹은 가장 처음의 함수만 호출되도록 함 
  - ex) Scroll Event, Resize Event

**링크**
- [블로그 정리 글](https://mingule.tistory.com/53)

## 🐝 [동기, 비동기, Callback] - 4
**링크**
- [블로그 정리 글](https://mingule.tistory.com/55)