[3단계 - 나만의 유튜브 강의실] 미키(권세진) 미션 제출합니다.
woowacourse/youtube-classroom pull request #65
Opened 2021-04-01 08:12 UTC by 0307kwon

## 3단계 - 나만의 유튜브 강의실 👩🏻‍💻

[데모페이지](https://0307kwon.github.io/javascript-youtube-classroom/)

안녕하세요 @HyeonaKwon 님! 😁 미키입니다! 🐭 
이전 단계 미션 코드의 구조를 많이 바꾸었습니다.

원래 2단계에서는 `본 영상`의 mvc와 `볼 영상`의 mvc로 나뉘어 있었습니다.
그런데 두 mvc의 동작이 너무나도 유사하고, navigation 버튼은 비디오를 필터링 해주는 역할만 하고 있다는 것을 깨달았습니다.
그래서 `본 영상`과 `볼 영상`의 mvc를 합쳐 하나의 mvc로 구성하게 하였고
그렇게 하니 `좋아요 한 영상`의 구현은 정말 쉬웠습니다.

혹시 의아한 부분이 있다면 피드백 부탁드립니다!

## 🙋‍♂️ 질문

현재 iframe의 srcdoc을 사용하여 영상의 썸네일만을 띄우고 있습니다.
그런데 만약 볼 영상에 100개의 영상이 저장되어 있다면
100개의 모든 영상이 화면에 보이지 않아도
100개의 이미지를 모두 불러오고 있습니다.

srcdoc을 사용하지 않는다면
iframe의 loading="lazy"를 사용할 수 있겠지만
srcdoc을 사용하는 경우, 어떻게 해야할지 고민이 되어 질문드립니다!

2021-04-12 13:35 UTC, HyeonaKwon commented
헉.. 저 왜 이거 이제 봤을까요 😭
제가 내일까지 꼭 리뷰 남기도록 하겠습니다!

2021-04-13 13:59 UTC, HyeonaKwon requested changes
안녕하세요 미키님! 리뷰를 늦게 남겨서 정말 죄송해요ㅠ 

전체적으로 상속구조로 통일시켜서 하나 읽으니까 다음꺼는 유추하면서 읽기 좋았어요 👍 
세부적인건 코멘트로 남겼구요, UI 관련해서는
1. 스낵바의 텍스트가 배경색과 조화가 됐으면(?) 좋겠다는 생각을 했습니당
2. 최근 검색어를 누르면 검색이 다시 될 줄 알았는데 안되네요! 확인 한 번 부탁드려요!

2021-04-13 13:59 UTC, HyeonaKwon commented on src/controller/ModalController.js
> +    const processedVideos = service.modal.getProcessedVideos(videos);
음.. 저는 서비스 코드를 아직 보지 못하고 이 컨트롤러만 보는 입장에서
서비스가 모달 객체를 가지고 있는것만 같은 느낌이 들어서 갸우뚱해져요!
modalService. getProcessedVideos() 가 아니라 그런지 왜 서비스의 모달이라는 애를 밖에서 직접 접근하지? 이런 생각이 듭니당!

그리고 스토리지가 어떻게 보면 DB 의 역할 또는 스토어의 역할을 하는거잖아요!
그런데 코드를 보면 여러 레이어에서 저장하고 꺼내쓰고 하는 것 같아요. 예를 들면 컨트롤러에서만 스토리지에 접근한다던지 서비스만 접근한다던지 해서 스토리지를 관리하고 접근하는 주체가 있으면 좋을 것 같단 생각이 들었습니당

2021-04-13 13:59 UTC, HyeonaKwon commented on src/controller/VideoController.js
> +    const isWatchedAfter = !isWatchedBefore;
오 노... 이런 변수 생성은 삼가해주세요! 같은 변수일 뿐입니당!

2021-04-13 13:59 UTC, HyeonaKwon commented on src/controller/VideoController.js
> +    const isFavoriteAfter = !isFavoriteBefore;
마찬가지입니당

2021-04-13 13:59 UTC, HyeonaKwon commented on src/service/videoService.js
> +}
```javascript
  return {
    ...dataset,
    isSaved: true,
    [STORAGE_KEYWORD.IS_WATCHED]: false,
    [STORAGE_KEYWORD.IS_FAVORITE]: false,
  };
```
이렇게는 안되는걸까요??

2021-04-13 13:59 UTC, HyeonaKwon commented on src/storage/VideoStorage.js
> +    });
```javascript
const targetVideo = videos.filter(
  video => video.videoId === targetVideoId
);

Object.keys(property).forEach(key => {
  if (!targetVideo[key]) return;

  targetVideo[key] = property[key];
});
```

2021-04-13 13:59 UTC, HyeonaKwon commented on src/storage/VideoStorage.js
> +          );
여기서는 리턴 안해줘도 되나요??

2021-04-13 13:59 UTC, HyeonaKwon commented on src/view/LayoutView.js
> +  }
```javascript
showCheckSnackbar(isWatchedAfter) {
  const message = isWatchedAfter 
    ? SNACKBAR_MESSAGE.WATCHED_VIDEO_SAVE_SUCCESS 
    : SNACKBAR_MESSAGE.WATCHING_VIDEO_SAVE_SUCCESS;

  this.showSnackbar(message, true);
}
```

2021-04-13 13:59 UTC, HyeonaKwon commented on src/view/LayoutView.js
> +    this.showSnackbar(SNACKBAR_MESSAGE.FAVORITE_VIDEO_CANCEL_SUCCESS, true);
위와 마찬가지입니당! 분기쳐야할 것만 분기치는게 더 읽기 좋아보여요~!

2021-04-18 12:30 UTC, 0307kwon reviewed
@HyeonaKwon 님! 꼼꼼한 피드백 감사합니다 ㅎㅎ 👍👍

## 학습로그

## [기타] {코드컨벤션} - 3/5
### 내용
- [ ] 삼항 연산자로 처리가능한 분기는 삼항 연산자로 처리해 코드의 중복을 줄이기
- [ ] Array.filter를 잘 활용을 못하는 것 같다. 기본 라이브러리 활용에 대해 좀 더 고민하면서 코드를 작성하자

## [코드 구조] {코드 복잡도} - 4/5
### 내용
- [ ] 하나의 레이어는 최대한 적은 레이어를 참조하도록 구현하기
- [ ] 레이어 관계를 적절히 정의하고 이를 바탕으로 일관성 유지하기 

### 링크
[코드 구조에 대한 고찰](https://velog.io/@0307kwon/%EC%99%9C-%EA%B0%9C%EB%B0%9C%EC%9E%90%EB%8A%94-%EC%BD%94%EB%93%9C-%EA%B5%AC%EC%A1%B0%EB%A5%BC-%EB%82%98%EB%88%84%EA%B3%A0-%EC%9D%98%EC%A1%B4%EC%84%B1%EC%9D%84-%EA%B3%A0%EB%A0%A4%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C)

2021-04-18 12:30 UTC, 0307kwon commented on src/controller/VideoController.js
> +    const isWatchedAfter = !isWatchedBefore;
가독성을 더 좋게하려다 오버엔지니어링이 되어버렸네요 ㅠㅠ 😭
지금보니 의미없는 코드인 것 같습니다! 감사합니다 ㅎㅎ 👍

2021-04-18 12:30 UTC, 0307kwon commented on src/service/videoService.js
> +}
헉 너무 깔끔하네요! 감사합니다 👍👍👍

2021-04-18 12:30 UTC, 0307kwon commented on src/storage/VideoStorage.js
> +    });
훨씬 깔끔해졌네요! 감사합니다 😊

2021-04-18 12:30 UTC, 0307kwon commented on src/storage/VideoStorage.js
> +          );
헉! 리턴을 깜빡했네요ㅠㅠ 꼼꼼히 봐주셔서 감사합니다! 😊

2021-04-18 12:30 UTC, 0307kwon commented on src/view/LayoutView.js
> +  }
삼항 연산자로 깔끔하게 줄일 수 있었네요! 코드 최적화에 대해 더 고민하겠습니다! 😊

2021-04-18 12:30 UTC, 0307kwon commented on src/controller/ModalController.js
> +    const processedVideos = service.modal.getProcessedVideos(videos);
실제로는 service가 modal을 이어줄 뿐이지만 확실히 modal 객체를 소유하고 있다는 느낌이 드네요! 
이런 오해를 줄 수 있다는 생각은 해보지 않았는데 새로운 관점을 얻을 수 있어 너무 좋습니다 😊
이 부분은 각 레이어의 폴더에 index를 두어 re-export하는 방식으로 바꾸고 
export 객체 형태도 오해의 여지가 없도록 바꾸어주었습니다.

또한 서비스와 컨트롤러의 역할이 명확히 나누어져 있지 않고 두 레이어가 모두 storage에 접근하는 현 방식을
storage <--- service <--- controller 의 구조로 명확히 해주었습니다!

오랜만에 저의 코드를 돌아보니 구조적으로 의존성이 높고 일관성이 부족한 면이 보이네요!
리뷰어님의 말씀을 어느정도 이해하게 된 것을 보니 성장하고 있는 것 같습니다 ㅎㅎ
항상 감사합니다 @HyeonaKwon 님! 앞으로도 복잡도를 낮추는 구조를 고민하겠습니다! 😁

2021-04-18 15:45 UTC, HyeonaKwon commented on src/controller/ModalController.js
> +    const processedVideos = service.modal.getProcessedVideos(videos);
크 성장하고 있다니.. 제일 보기좋은 말이네요 👍

2021-04-18 15:56 UTC, HyeonaKwon approved these changes
미키님은 말도 너무 예쁘게 해주시네요 👍 성장하고 있다고 느끼셔서 다행이에요!
꼼꼼하게 고쳐주신 내용도 보았고 블로그 내용도 봤습니당! 잘 정리해주셨네요
블로그 쓰시는거 보니까 초심 잃은 저에게 현타가 왔습니다.. (?) ㅋㅋㅋㅋㅋ

유튜브 미션 진행하시느라 고생하셨어요!!

2021-04-18 15:56 UTC, merged