[1단계 - 나만의 유튜브 강의실] 체프(심문성) 미션 제출합니다
woowacourse/youtube-classroom pull request #8
Opened 2021-03-05 12:51 UTC by Puterism

### [🚀 데모 페이지](https://puterism.github.io/javascript-youtube-classroom/)

안녕하세요! 이번에 [피터](https://github.com/iborymagic)와 함께 페어를 진행한 체프입니다!
이번 리뷰도 잘 부탁드립니다!

### 고려했던 부분
(작성중)

2021-03-06 16:17 UTC, HyeonaKwon requested changes
안녕하세요! 이번 유튜브 미션의 리뷰를 맡게된 HyeonaKwon 입니다 :)

코드 잘 보았구요! 전체적으로 api 의 에러처리가 되어있지 않아보입니다. try-catch 를 이용해 에러처리를 추가했으면 좋겠습니다.

그리고 UX 관련해서는
1. 볼 영상이 하나도 없을 때의 처리
2. 유튜브 검색 모달을 닫았다가 다시 눌렀을 때의 초기화 처리
가 필요해보입니다! 미션 수행하시느라 고생하셨어요 👍

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/components/WatchList.js
> +          `<article class="clip d-flex flex-col">
이 html 코드를 리턴하는 get~~~() 함수가 따로 있고 여기서는 
```javascript
$(SELECTORS.CLASS.WATCH_LIST).insertAdjacentHTML('beforeend', get~~~(...));
```
이렇게 하는게 가독성에 더 좋을 것 같습니다 👍

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/store.js
> +    if (localStorage.length <= 1) {
주석도 달아주셨지만 요거는 수정되어야할 부분 같습니다!

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/store.js
> +    return JSON.parse(localStorage.getItem(key));
localStorage.getItem() 이 JSON 객체가 아닐 때의 예외처리가 필요해보입니당

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/api.js
> +    `);
요거는 그냥 객체 리턴하지 않고 JSON.parse() 으로 파싱하는 이유가 있을까요?

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/components/YoutubeSearchManager.js
> +            <article class="clip d-flex flex-col">
요거는 WatchList 의 renderSavedVideos 에 있는 template 과 재활용할 수 있지 않을까요?

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/lib/Store.js
> +      this.state = { ...this.state, [KEY]: data || [] };
```javascript
if (!data) this.save(KEY, []);
```
여기서 data 를 업데이트하지 않으면
```javascript
this.state = { ...this.state, [KEY]: data || [] };
```
여기서 [Key] 에 들어가는 data 와 this.save() 를 통해 KEY 에 들어간 기본 [] 값이 다르지 않을까요?? 이거는 괜찮은건가요?

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/components/YoutubeSearchManager.js
> +    $(SELECTORS.CLASS.SAVED_VIDEO_COUNT).textContent = this.store.get()[LOCAL_STORAGE_KEYS.WATCH_LIST].length;
src/js/lib/Store.js 16라인에 남긴 코멘트로 인해 `this.store.get()[LOCAL_STORAGE_KEYS.WATCH_LIST]` 가 undefined 가 될 수도 있지 않나요??

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/components/YoutubeSearchManager.js
> +    renderSkeletonUI(SELECTORS.CLASS.YOUTUBE_SEARCH_RESULT, 8);
8도 상수로 빼면 좋겠네요!

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/components/YoutubeSearchManager.js
> +    const $selectedButton = event.target;
이렇게 변수 선언을 했다면 아래의 코드에서는 event.target 대신 이 변수를 사용하는게 좋을 것 같습니다.

2021-03-06 16:17 UTC, HyeonaKwon commented on src/js/components/YoutubeSearchManager.js
> +    if (!event.target.classList.contains('btn-save')) return;
if 문 조건이 변수 선언 전 함수 제일 처음 시작에 존재하는게 좋아보입니다!

2021-03-06 16:25 UTC, HyeonaKwon commented
앗 그리고 YoutubeSearchManager 가 컴포넌트에 있는게 맞는지는 의문입니다. 보통 매니저는 컴포넌트가 아니니까요!
YoutubeSearchManager 가 매니저 역할과 컴포넌트 역할, 즉 너무 많은 역할을 하고 있지는 않나 고민이 필요해보여요!

2021-03-07 13:24 UTC, Puterism commented on src/js/api.js
> +    `);
이 함수는 base64로 변환된 JSON 더미 데이터를 return 하는 테스트용 가짜 API입니다
데이터를 문자열로 가져오기 때문에 JSON.parse가 필요했습니다

2021-03-07 13:25 UTC, Puterism commented on src/js/components/WatchList.js
> +          `<article class="clip d-flex flex-col">
이 template도 함수로 분리하는 게 좋겠네요! 짚어주셔서 감사합니다!

2021-03-07 13:26 UTC, Puterism commented on src/js/store.js
> +    if (localStorage.length <= 1) {
앗, 사실 이 store.js는 더 이상 사용하지 않는 코드인데 제가 실수로 커밋했나봐요!
새로운 Store에서는 조건을 잘 수정해서 올렸습니다!

2021-03-07 13:28 UTC, Puterism commented on src/js/store.js
> +    return JSON.parse(localStorage.getItem(key));
앗, 확실히 그렇네요! 예외 처리가 되어 있지 않은 부분이 많이 남아있네요 ㅠㅠ 체크 감사합니다!

2021-03-07 13:30 UTC, Puterism commented on src/js/components/YoutubeSearchManager.js
> +    const $selectedButton = event.target;
앗, 중복해서 event.target을 가져왔군요
수정하겠습니다!

2021-03-07 13:31 UTC, Puterism commented on src/js/components/YoutubeSearchManager.js
> +    if (!event.target.classList.contains('btn-save')) return;
저도 이 편이 성능에서나 코드 가독성 면에서 더 좋다고 생각합니다
수정하겠습니다!

2021-03-07 14:40 UTC, Puterism commented on src/js/components/YoutubeSearchManager.js
> +            <article class="clip d-flex flex-col">
맞아요! 완전 똑같은 부분인데 DRY하지 않았네요...
따로 template를 모아둔 파일을 만들어서 관리하는 게 좋겠다고 생각합니다!

2021-03-07 14:42 UTC, Puterism commented on src/js/components/YoutubeSearchManager.js
> +    renderSkeletonUI(SELECTORS.CLASS.YOUTUBE_SEARCH_RESULT, 8);
앗, 그렇네요! 같이 수정하겠습니다!

2021-03-07 14:51 UTC, Puterism commented
> 전체적으로 api 의 에러처리가 되어있지 않아보입니다. try-catch 를 이용해 에러처리를 추가했으면 좋겠습니다.

헉... API 에러 처리를 안해뒀었네요... 수정하겠습니다!

> 볼 영상이 하나도 없을 때의 처리

볼 영상이 하나도 없을 때의 처리는 Step2 기능 목록에 있어서 그 때 진행하려고 남겨두었습니다!

> 유튜브 검색 모달을 닫았다가 다시 눌렀을 때의 초기화 처리

기능 목록에
`검색 모달에 다시 접근했을 때 가장 마지막에 검색한 키워드로 검색한 결과를 보여준다.`
라는 조건이 있어서, 검색 모달을 닫았다가 다시 열었어도 그대로 남아있도록 만들어두었습니다! 

> 앗 그리고 YoutubeSearchManager 가 컴포넌트에 있는게 맞는지는 의문입니다. 보통 매니저는 컴포넌트가 아니니까요!
YoutubeSearchManager 가 매니저 역할과 컴포넌트 역할, 즉 너무 많은 역할을 하고 있지는 않나 고민이 필요해보여요!

- 제가 `YoutubeSearchManager`라고 이름 지었을 때는, 유튜브 검색 관련 로직이 담겨져 있는 컴포넌트의 의미에서 이름을 지었던 것이고, 컴포넌트라고 하기에는 너무 많은 기능을 가지고 있는 것 같아서 뒤에 Manager라고 이름을 지어두었습니다.

- `Manager`라는 네이밍을 특정 패턴에서 사용되는 요소의 역할을 생각하고 사용한 게 아니라서, 매니저의 역할이 정확히 어떤지 잘 이해하지 못했습니다. 어떻게 검색하면 알 수 있을지 키워드를 알려주시면 감사드리겠습니다.
- 
- 저도 `YoutubeSearchManager`가 너무 많은 역할을 하고 있다는 것에 매우 공감합니다. 좀 더 자잘하게 컴포넌트를 나눠서 구현할 수 있을지 고민하고 적용해보겠습니다!

2021-03-08 06:59 UTC, Puterism commented on src/js/lib/Store.js
> +      this.state = { ...this.state, [KEY]: data || [] };
> 여기서 data 를 업데이트하지 않으면

이라는 말이 정확하게 어떤 의미인지 잘 모르겠습니다... 조금만 더 힌트를 부탁드립니다!

이 코드는 페이지를 로드했을 때, localStorage에 저장된 값들을 가져와서 state에 저장해주는 코드입니다.
LOCAL_STORAGE_KEYS 라는 상수에서 관리하는 KEY들을 순회하면서
만약 localStorage에 해당 KEY로 저장된 값이 아무것도 없으면 빈 배열로 초기화시켜줍니다. 다음 코드가 바로 이겁니다.
```javascript
const data = this.load(KEY);
if (!data) this.save(KEY, []);
```
그리고 localStorage에서 불러온 값을 state 객체에도 같이 업데이트 시켜줍니다. 만약에 아무 것도 없어서 빈 배열로 초기화되었다면, state에도 같이 빈 배열로 초기화합니다.
```javascript
this.state = { ...this.state, [KEY]: data || [] };
```

얘는 처음에 페이지를 로드했을 때 딱 한번 init되는 메소드라서, KEY에 다른 기본 값이 들어가는 경우는 없을 거라고 생각합니다.


> localStorage.getItem() 이 JSON 객체가 아닐 때의 예외처리가 필요해보입니당

다른 파일에서 남겨주신 이 리뷰와 비슷하게
이 코드는 로컬 스토리지가 배열의 형태가 아닐 경우의 예외처리는 되어 있지 않습니다.

2021-03-08 08:14 UTC, Puterism commented on src/js/components/YoutubeSearchManager.js
> +    $(SELECTORS.CLASS.SAVED_VIDEO_COUNT).textContent = this.store.get()[LOCAL_STORAGE_KEYS.WATCH_LIST].length;
https://github.com/woowacourse/javascript-youtube-classroom/pull/8#discussion_r589205952

위와 같이 남겨주신 코멘트의 의미를 잘 모르겠습니다. 코멘트에 대해서 조금만 더 힌트를 부탁드립니다!

2021-03-10 10:37 UTC, HyeonaKwon commented on src/js/lib/Store.js
> +      this.state = { ...this.state, [KEY]: data || [] };
아하! 제가 코드를 잘 못 이해한 것 같습니다. 설명해주셔서 감사합니다 👍

2021-03-10 10:38 UTC, HyeonaKwon commented on src/js/components/YoutubeSearchManager.js
> +    $(SELECTORS.CLASS.SAVED_VIDEO_COUNT).textContent = this.store.get()[LOCAL_STORAGE_KEYS.WATCH_LIST].length;
요거는 무시해주세요! 죄송합니다 😭

2021-03-10 10:40 UTC, HyeonaKwon commented on src/js/components/WatchList.js
> +        return videoTemplate;
👍

2021-03-10 10:43 UTC, HyeonaKwon commented on src/js/components/WatchList.js
> +    }
여기의 에러처리와 api 내부의 에러처리 두 개로 나눈 이유가 있을까요~? api 내부에서 `throw error` 를 해주는거면 api 에서의 에러처리는 필요가 없어보입니다!

2021-03-10 10:43 UTC, HyeonaKwon commented on src/js/components/WatchList.js
> +      showSnackbar(error.message);
요기도 마찬가지 의견이에요!

2021-03-11 12:28 UTC, Puterism commented on src/js/components/WatchList.js
> +    }
`api.js`의 함수에서 `throw Error`를 해준 뒤, 이 에러의 메시지를 snackbar에 띄워주고 싶은데,
snackbar에 띄워주는 코드를 `api.js`에 넣는 것보다 컴포넌트 안에서 처리하는 게 맞다고 생각되서 `try catch`를 각각 사용해서 작성하게 되었습니다.

`api.js`에 API 호출 함수를 나누어서 작성했을 때, `try catch` 구문을 두번씩이나 사용해야 하는지 저도 의문이 듭니다. 하지만 이외의 방법이 잘 떠오르지가 않네요...

2021-03-13 11:50 UTC, HyeonaKwon commented on src/js/components/WatchList.js
> +    }
음 사실 try-catch 로 감싸는게 그 안에서 에러처리를 다 하겠다는 의미인데 catch 에서 Error 를 던지는 구조가 되어서..
차라리 사용청에서만 try-catch 로 감싸는게 더 괜찮을 것 같아요! 2단계 진행하면서 고민해보시면 좋을 것 같습니다 👍

2021-03-13 11:59 UTC, HyeonaKwon commented
YoutubeSearchManager 의 역할을 분리한다면 자연스럽게 Manager 라는 키워드는 사라질 수 있을 것 같은데요,
이거를 2단계에서 진행하시는거라면 머지하고 다음 단계로 넘어가도 좋을 것 같네요! 👍 

Manager 라는 말 그대로 객체들(ex. ObjectPool) 을 관리하거나, 특정 정보 또는 프로젝트 전반적으로 사용하는 정보들을 관리하는 역할을 Manager 로 이름을 붙이게 되는데요! 컴포넌트의 이름으로 붙이기에는 거리가 좀 있는 것 같아요.
차라리 YoutubeSearchModal 정도였으면 어땠을까 하는 생각이 들어요!

머지 진행해도 될까요~?

2021-03-13 12:05 UTC, Puterism commented
넵 머지 부탁드립니다
감사합니다!

2021-03-13 12:07 UTC, HyeonaKwon approved these changes
넵! :) 다음 단계에서 봬요!

2021-03-13 12:07 UTC, merged