[1단계 - 나만의 유튜브 강의실] 준찌(장준혁) 미션 제출합니다.
woowacourse/youtube-classroom pull request #83
Opened 2022-03-11 08:10 UTC by juunzzi

# 상태가 변경되면 등록된 컴포넌트 들에게 알리고, 그들이 각자의 파트를 재 렌더링 하도록 한다.

저희는 위 아이디어에만 집중하여 프로덕트를 개발하였습니다.

2022-03-11 11:44 UTC, juunzzi commented on src/js/components/SearchFormComponent.js
> +  #dispatchSubmitSearchKeyword() {
#### 질문 1 - 이 부분이 개인적인 생각에 `AppBusiness` 에 있어야 할 것 같습니다.


#### 이유

컴포넌트는 상태에 따라 화면을 그리는 모듈인데, 비즈니스 로직과 관련된 일을 수행한다고 생각됩니다. 여기서는 `dispatch(customevent)` 함수만 호출하여야 하지 않나 싶은데 어떻게 생각하시나요?

2022-03-11 11:44 UTC, juunzzi commented on src/js/components/VideoContainerComponent.js
> +    this.skeletonListComponent?.unmount();
#### 상위 컴포넌트에서 하위 컴포넌트의 메소드(`unmount`)에 접근하여 직접 호출하는 것이 자연스러운 일인가요?

제가 생각하기엔 선언적이지 않다고 보입니다 ㅠㅠ 무언가 하위컴포넌트에게 인자를 주어 동작하게 하는게 자연스러운것 같은데 .. 개선이 필요할까요? 또 어떤 아이디어로 개선해볼 수 있을까요? (질문이 너무 모호해서 죄송합니다.)

2022-03-11 20:47 UTC, lsw1164 requested changes
안녕하세요 준찌님, 코드 잘봤습니다. 

> 3-1. 전체적인 프로그램 구조에 대한 생각이 궁금합니다!!
- 비즈니스 로직과 뷰를 분리한 시도 좋았습니다 👍 
- flux 패턴의 느낌을 받았습니다.
- setState에서  값or함수를 받는데 의도를 파악하기 어렵습니다.
- 프로젝트가 커지면 전역에서 접근하는 방식은 수정해야겠다고 생각했습니다.

2022-03-11 20:47 UTC, lsw1164 commented on src/js/__test__/video.test.js
> +    }
expect문이 2개 있는데 상황에 따라 둘 중 하나만 테스트 되겠군요?
일관성 있는 테스트 결과를 내려면 어떻게 바꾸면 좋을까요?

2022-03-11 20:47 UTC, lsw1164 commented on src/js/components/VideoContainerComponent.js
> +    this.skeletonListComponent?.unmount();
이미 상위 컴포넌트가 하위 컴포넌트를 직접 생성하면서 강한 의존성을 갖고 있는 상황입니다.
따라서, 그냥 메서드 호출하는 건 자연스러워 보입니다 :)

가장 경계해야 되는 상황은 양방향 참조입니다.

2022-03-11 20:47 UTC, lsw1164 commented on src/js/components/SearchFormComponent.js
> +  #dispatchSubmitSearchKeyword() {
이미 로직이 분리됐다고 생각하는데요. validate, alert 띄우는 로직을 써주신 게 걸리는 걸까요?

2022-03-11 20:47 UTC, lsw1164 commented on src/js/utils/validation.js
> +export const isFirstSearchByKeyword = (prevVideoListLength) => prevVideoListLength === 0;
validation 따로 빼주셨네요 👍

2022-03-11 20:47 UTC, lsw1164 commented on src/js/modules/eventFactory.js
> +// window에 커스텀 이벤트를 바인딩하고 있는데, 이 부분에서 문제가 발생하지 않는지..?
window에 직접 바인딩하는 건 지양하는 게 좋겠습니다.

2022-03-12 07:50 UTC, juunzzi commented on src/js/components/SearchFormComponent.js
> +  #dispatchSubmitSearchKeyword() {
네 맞아요 !!! 그 부분이 걸리는데 상관없을까요 ?

2022-03-12 07:51 UTC, juunzzi commented on src/js/modules/eventFactory.js
> +// window에 커스텀 이벤트를 바인딩하고 있는데, 이 부분에서 문제가 발생하지 않는지..?
왜 직접 바인딩을 하면 안좋은지 여쭤봐도 될까요 ?

2022-03-12 08:10 UTC, juunzzi commented
> 비즈니스 로직과 뷰를 분리한 시도 좋았습니다

헤헤 우선 감사합니다. 하지만 아직은 비즈니스 로직과 뷰를 분리한단 말이 제게 너무 어려운데 지금 코드라면 `잘 분리된 것일까요?`

> * setState에서  값or함수를 받는데 의도를 파악하기 어렵습니다.
 상태를 최신화 하기위해 이전 상태값이 필요한 경우 이전 상태 값을 토대로 새로운 상태를 만들어내는 함수를 넣어 상태를 최신화하고자 하였습니다. ( 객체 형태의 상태 값인 경우 -> 객체의 프로퍼티들을 누락시키지 않고 상태를 최신화하기위해 )  지금 생각해보니 의도와는 다르게 사용해야하는 부분에서도 사용하지 않았네요... 🥲


> * 프로젝트가 커지면 전역에서 접근하는 방식은 수정해야겠다고 생각했습니다.

 전역에서 접근하는 방식이란 무엇일까요?? `stateStore` 모듈을 전역 상태 관리 모듈로 사용하는 부분을 말씀하시는 것일까요? 

혹시 어떤 부분에서 수정해야겠다고 느끼셨나요 ????

2022-03-12 08:15 UTC, juunzzi commented on src/js/__test__/video.test.js
> +    }
에러가 발생하면 테스트를 통과하게끔 만들면 될것같아요 수정해보겠습니다 !!

2022-03-12 15:18 UTC, lsw1164 requested changes

2022-03-12 15:18 UTC, lsw1164 commented on src/js/components/SearchFormComponent.js
> +  #dispatchSubmitSearchKeyword() {
저는 애초에 validation에 걸려서 submit이 이뤄지지 않았다고 봤어요, 
그래서 submit 로직이 잘분리됐다고 생각헀습니다 :)

2022-03-12 15:18 UTC, lsw1164 commented on src/js/modules/eventFactory.js
> +// window에 커스텀 이벤트를 바인딩하고 있는데, 이 부분에서 문제가 발생하지 않는지..?
전역에서 모두 접근할 수 있다는 건 장점이자 단점이라 생각합니다. 
여러 곳에서 접근해야 될 만큼 범용적인 코드만 들어있다면 좋겠지만 기능을 추가하다 보면 그렇지 않을 확률이 높습니다.

전역 이벤트를 등록하면 모든 컴포넌트에서 호출할 수 있어서 사용은 편하겠지만 어떤 이벤트를 어떤 컴포넌트에서 등록했고 이벤트 네임은 무엇이고 이런 정보를 모든 컴포넌트가 주의해서 알고 있어야 된다는 리스크가 생깁니다. 

이벤트 등록은 런타임 의존성을 추가하는 겁니다. 
즉, 의존성이 숨겨져 있다고 볼 수 있겠는데요. 지금처럼 전역 범위 이벤트가 숨져겨 있다면 프로젝트 규모가 커질수록 트래킹이 더 힘들어 질 것입니다. 

그리고 만약 이벤트 등록을 제거했는데 호출하는 곳에서는 지우지 못해서 사용하지 않는 코드 잔재가 남아서 혼동을 줄 수 있겠습니다.

2022-03-13 17:31 UTC, juunzzi commented on src/js/modules/eventFactory.js
> +// window에 커스텀 이벤트를 바인딩하고 있는데, 이 부분에서 문제가 발생하지 않는지..?
이해가 되었습니다 !!! 그럴수있겠군요 ㅎㅎ 근데 리뷰어님의 의견을 듣고 코드를 수정하려고했는데.. 

사실 지금 구조에서 `AppBusiness에서 Component가 갖는 DOM에 접근하기`가 힘든 것 같아요.. 어떻게 해야할지 감이 잘 오지 않네요 

그렇다고 `AppBusiness`에서 `Component의 DOM Element`를 알게끔하고싶지는 않은데 어떤 방법을 떠올릴 수 있을까요 ?

2022-03-14 16:41 UTC, lsw1164 commented on src/js/modules/eventFactory.js
> +// window에 커스텀 이벤트를 바인딩하고 있는데, 이 부분에서 문제가 발생하지 않는지..?
지금 구조에서 어떻게 바꾸는 걸 생각하신 걸까요?  
반드시 ``AppBusiness에서 Component가 갖는 DOM에 접근``해야 되는 상황인가요?

2022-03-14 16:49 UTC, lsw1164 commented on src/js/modules/eventFactory.js
> +// window에 커스텀 이벤트를 바인딩하고 있는데, 이 부분에서 문제가 발생하지 않는지..?
제 생각에는 이번 설계 컨셉을 이미 커스텀 이벤트로 모든 로직을 관리하는 방식으로 잡으셨으니 무리하게 구조를 바꾸기 보다는 최대한 지금같은 패턴을 경험해 보는 것도 의미 있다고 생각합니다. 구조를 유지하면서 작은 단위의 개선 포인트를 찾아보시고 장점/단점을 이해한다는 취지로 미션을 진행하는 게 좋을거 같습니다.

2022-03-14 16:50 UTC, lsw1164 approved these changes
준찌님 Approve 하겠습니다. 다음 스텝 진행해주세요!

2022-03-14 16:50 UTC, merged