[1단계 - 나만의 유튜브 강의실] 코이(정인교) 미션 제출합니다.
woowacourse/youtube-classroom pull request #92
Opened 2022-03-11 08:27 UTC by InKyoJeong

2022-03-11 20:01 UTC, lsw1164 requested changes
안녕하세요 코이님!

테스트는 mock, spy 등 키워드로 알아보시면 도움이 될 거 같습니다.
IntersectionObserver 활용 잘봤습니다 👍

2022-03-11 20:01 UTC, lsw1164 commented on src/js/utils/localStorage.js
> +};
|| 대신 ??는 어떨까요?

추가로 JSON.parse는 Exception이 발생할 경우가 없을까요?

2022-03-11 20:01 UTC, lsw1164 commented on src/js/components/SearchModal.js
> +  createObserver() {
> 페이지 스크롤은 intersection observer를 사용했는데, 현재 구현한 코드는 다음페이지를 불러올때 observer를 해제하고 재생성합니다. 그런데 이런식으로 구현하는것이 비효율적인 방법일수 있을것같다는 생각이 들었습니다.

어떻게 하면 개선할 수 있을까요?

2022-03-11 20:01 UTC, lsw1164 commented on src/js/components/SearchModal.js
> +export class SearchModal {
SerchModal에서 많은 역할을 맡고 있는거 같네요. 컴포넌트를 더 나눠볼 수 있을까요?

2022-03-12 10:18 UTC, InKyoJeong commented on src/js/utils/localStorage.js
> +};
nullish 연산자를 사용하는것이 더 좋겠네요! 또한 JSON.parse는 변환할 문자열이 유효한 JSON이 아닐 경우 SyntaxError에러가 발생하므로 그런경우도 생각해야겠네요

2022-03-12 10:19 UTC, InKyoJeong commented on src/js/components/SearchModal.js
> +export class SearchModal {
저도 그렇게생각합니다! 역할을 나눌방법을 생각해보고 적용해보겠습니당

2022-03-12 10:20 UTC, InKyoJeong commented on src/js/components/SearchModal.js
> +  createObserver() {
계속해서 생성하고 해제하기보다는, 한번만 생성하는 방식 등으로 개선해볼 예정입니다!

2022-03-14 16:30 UTC, lsw1164 approved these changes
코이님, 남은 피드백은
다음 스텝에 진행 하시면서 반영해주시면 될 거 같습니다 :)

2022-03-14 16:30 UTC, lsw1164 commented on src/js/utils/validation.js
> +export const verifySaveId = (storage, id) => {
storage를 파라미터로 받는 이유는 추상화를 고려한 걸까요? (추후에 다른 storage로 바꿀 수 있도록?)

2022-03-14 16:30 UTC, lsw1164 commented on src/js/manager/SearchManager.js
> +  }
이런 방법으로 subscribe/unsubscribe를 하면 등록할 때마다 index를 어딘가에서 기억하고 있어야될까요?

2022-03-14 16:30 UTC, lsw1164 commented on src/js/components/App.js
> +    this.searchManager = new SearchManager();
SearchManager가 App.js에서 쓰이지 않는군요. App.js에 생성한 이유가 있을까요?

2022-03-14 16:30 UTC, merged

2022-03-14 17:40 UTC, InKyoJeong commented on src/js/components/App.js
> +    this.searchManager = new SearchManager();
SearchManager는 App에서 SearchModal로 전달하기보다는, 바로 SearchModal에서 생성하는게 낫겠네요!!

2022-03-14 17:40 UTC, InKyoJeong commented on src/js/manager/SearchManager.js
> +  }
이렇게하면 배열로 만들어서 푸시만 했을때보다, 인덱스를 기억해서 unsubscribe 해야한다면 쉽게 할수 있을것같아서 만들었습니다! 그런데 등록할때마다 인덱스를 기억해야한다는 단점이 있네요! unsubscribe를 사용할 일이 없을것같다면 굳이 이렇게 Map보다는 배열에 push 하는 형태로 만드는게 더 나을것같기도 하네요. 리뷰어님도 이렇게 생각하시는지 궁금합니다!!

2022-03-14 17:45 UTC, InKyoJeong commented
앗 아침에 변경한 부분들 정리해서 요청 드리려고했는데 머지가 되었네요ㅎㅎ 
빠르게 리뷰해주셔서 감사합니다! 코멘트 남겨주신부분들이랑 개선하고싶은 부분들을 변경해보았습니다.
그럼 2단계때 다시 요청 드리겠습니다~!

2022-03-14 17:51 UTC, InKyoJeong commented on src/js/utils/validation.js
> +export const verifySaveId = (storage, id) => {
스토리지배열과 추가할 아이디는,
중복값과 배열길이를 검증하기 위해 파라미터로 넘겼는데요! 
storage를 넘기는 대신에 verifySaveId 함수 내에서 getLocalStorage를 이용해서 불러오는것이 나을까요??
아니면 파라미터 네이밍이 좀 어색한가요!?