[1단계 - 나만의 유튜브 강의실] 민초(홍영민) 미션 제출합니다.
woowacourse/youtube-classroom pull request #94
Opened 2022-03-11 08:32 UTC by jswith

## 데모페이지
https://jswith.github.io/javascript-youtube-classroom/

2022-03-12 12:58 UTC, austinpark420 reviewed
```
Q. 대부분의 요구사항이 UI와 관련되어 있어 어떤 로직들을 단위테스트로 수행해야 할지 결정하는 것이 어려웠습니다. 페어와 고민 끝에 스토리지에 저장하는 부분과 api를 통해 받아온 시간 값을 원하는 형식으로 바꾸어주는 부분만 테스트를 진행했습니다.
이러한 상황에서는 보통 어떠한 것들을 단위 테스트로 테스트할 수 있을지 궁금합니다!
```
> 더미데이터를 활용해서 테스트코드를 추가 작성해보시는 건 어떨까요? 그렇다면 요구사항에 많은 부분들을 테스트할 수 있을것 같습니다 😄

2022-03-12 12:58 UTC, austinpark420 commented on src/js/constants/index.js
> +export { MAX_SAVE_COUNT, MESSAGE, STORAGE_KEY };
깔끔하게 export 하시네요 👍

2022-03-12 12:58 UTC, austinpark420 commented on index.html
> +    <div id="snack-bar"></div>
UX/UI에 대해서 고민하신 흔적이 보이네요 👍

2022-03-12 12:58 UTC, austinpark420 commented on index.html
> +        <!-- 2-2 검색 결과가 없을 경우, `search-result--no-result` class를 붙이고 아래와 같은 no-result를 보여줍니다.-->
불필요한 주석은 없애주셔도 좋을 것 같습니다!

2022-03-12 12:58 UTC, austinpark420 commented on src/js/domain/youtubeApi.js
> +};
tryCatch문 사용해보시면 어떨까요?ㅎ

2022-03-12 12:58 UTC, austinpark420 commented on src/js/ui/Result.js
> +  foundResultTemplate(items) {
네이밍으로보고 하는 역할을 유추하기가 힘드네요 ㅠ

2022-03-12 12:58 UTC, austinpark420 commented on src/js/ui/Result.js
> +  renderSkeletonUI() {
스크롤시 해당 함수가 호출이 안되서 skeleton이 노출 안됩니다.

2022-03-12 12:58 UTC, austinpark420 commented on src/js/ui/Result.js
> +    const io = new IntersectionObserver(
IntersectionObserver을 활용하셨군요.👍

2022-03-12 12:58 UTC, austinpark420 commented on src/js/ui/Search.js
> +    this.result = new Result();
Result를 Search에서 초기화하는 이유를 알 수 있을까요?

2022-03-12 12:58 UTC, austinpark420 commented on src/js/ui/Modal.js
> +import { $ } from '../utils/dom';
UI 폴더에 있는 파일명이 좀 더 명시적이면 좋을 것 같습니다.ㅎ

2022-03-12 12:58 UTC, austinpark420 requested changes
안녕하세요 민초!
만나뵙게되서 반갑습니다.

전체적으로 코드를 깔끔하게 작성해주신 것 같아요. 👍 
UX/UI에 대해 고민도 많이 하셨던것 같구요.

관련해서 코멘트 남겨놓았습니다! 확인부탁드릴게요!

2022-03-13 23:44 UTC, jswith commented on src/js/ui/Search.js
> +    this.result = new Result();
Result의 메소드를 Search에서 사용하려고 초기화했습니다. 
다시보니 Result는 constructor가 비어 있어 굳이 클래스로 만들지 않아도 괜찮을 것 같네요!

2022-03-13 23:45 UTC, jswith commented on src/js/ui/Modal.js
> +import { $ } from '../utils/dom';
네 너무 일반적인 이름인 것 같습니다. YoutubeSearchModal과 같은 형태로 수정하도록 하겠습니다!

2022-03-13 23:47 UTC, jswith commented on index.html
> +        <!-- 2-2 검색 결과가 없을 경우, `search-result--no-result` class를 붙이고 아래와 같은 no-result를 보여줍니다.-->
앗 주석을 놓쳤네요! 😅

2022-03-13 23:49 UTC, jswith commented on src/js/ui/Result.js
> +  foundResultTemplate(items) {
검색 결과에 관련한 템플릿을 의도했는데 무얼 found 했는지가 애매하긴 하네요 ㅎㅎ
searchResultFoundTemplate으로 수정하려고 합니다!

2022-03-13 23:58 UTC, jswith commented on src/js/ui/Result.js
> +  renderSkeletonUI() {
초기 로딩시에만 스켈레톤 UI를 보여주는 걸로만 알고 스크롤시에는 적용하지 않았습니다!
다른 크루들의 페이지를 보니 스크롤시에도 스켈레톤 UI를 보여주고 있었네요.
사용자 입장에서 보면 스크롤시마다 스켈레톤 UI를 보여주는게 더 나을 것 같습니다 ㅎㅎ 반영해보도록 할게요.

2022-03-14 00:04 UTC, jswith commented on src/js/domain/youtubeApi.js
> +};
넵 api 호출하면서 async await를 처음 사용해봐서 사용 방식에 좀 익숙하지 않았었습니다!
주말에 비동기 부분을 공부했고, 적용해보겠습니다!

2022-03-14 12:35 UTC, jswith commented on index.html
> +        <!-- 2-2 검색 결과가 없을 경우, `search-result--no-result` class를 붙이고 아래와 같은 no-result를 보여줍니다.-->
수정하였습니다. [4ddf2a7](https://github.com/woowacourse/javascript-youtube-classroom/pull/94/commits/4ddf2a7b036180eb7c2b454333c2006ed635a028)

2022-03-14 12:36 UTC, jswith commented on src/js/domain/youtubeApi.js
> +};
수정하였습니다. [12ce218](https://github.com/woowacourse/javascript-youtube-classroom/pull/94/commits/12ce218f800db05cd5595ca0d6233479a9b1e10b)

2022-03-14 12:36 UTC, jswith commented on src/js/ui/Result.js
> +  foundResultTemplate(items) {
수정하였습니다. [7f71861](https://github.com/woowacourse/javascript-youtube-classroom/pull/94/commits/7f71861b3569a6576adef9033e621f6ae0e2581d)

2022-03-14 12:37 UTC, jswith commented on src/js/ui/Result.js
> +  renderSkeletonUI() {
수정하였습니다. [6a1de2c](https://github.com/woowacourse/javascript-youtube-classroom/pull/94/commits/6a1de2cc81e0693bc397e9144248eb3b0b10df86)

2022-03-14 12:37 UTC, jswith commented on src/js/ui/Search.js
> +    this.result = new Result();
초기화가 필요없는 부분인 것 같아서 객체로 변경했습니다. [92bc917](https://github.com/woowacourse/javascript-youtube-classroom/pull/94/commits/92bc91771a0219a2eb570a006bd3abe85b3a38fc)

2022-03-14 12:38 UTC, jswith commented on src/js/ui/Modal.js
> +import { $ } from '../utils/dom';
수정했습니다. [aeb469c](https://github.com/woowacourse/javascript-youtube-classroom/pull/94/commits/aeb469c4369b1d06a8f607ff16e4ad131677039c)

2022-03-14 12:52 UTC, jswith commented
피드백 주신 부분에 대해서는 반영한 부분 comment에 commit link 남겨놓았습니다!

추가로 수정한 사항은
- a 태그 클릭시 새 창에서 열리도록 수정
- saveButton에 이벤트 바인딩 하는 방식을 일일이 다 달아주는 방식에서 이벤트 위임 방식으로 수정

입니다.

2022-03-16 08:15 UTC, jswith commented
추가 수정 사항입니다.

- video 저장하는 부분을 result에서 분리
- esc 키 누르면 모달창 닫히는 기능 구현
- button 마크업에 type 추가
- css 색상에 변수 적용
- submit 이벤트 debounce 처리

2022-03-16 12:16 UTC, woowapark approved these changes
안녕하세요 민초🌿  
오스틴 대타로 찾아온 공원🏞 입니다.      
전체적으로 
- 불필요한 패턴 적용이나 추상화를 굳이 하지 않고 민초의 생각이 많이 담긴 코드 같아서
- 중복 검색 방어나 서버 오류 시 스낵바 메시지를 띄워주는 등 사용자 입장에서도 고민하신 부분들이 보여서    
좋았어요!     

추가로 개선해주신 부분들 확인해서 추가 코멘트 남긴 부분들과 아래 사항들은
스텝2에서 이어서 고민해보시면 좋을 것 같습니다!      
꼭 다 수정하신다기보단 민초가 잘 선택적으로 반영해주시면 좋을 것 같아요.
고생 많으셨어요, 스텝2에서 이어서 만나요! 

### 네이밍
- Search, Result, json, io 등 종종 너무 일반적인 용어가 쓰이는 것 같아요! 
- 조금 더 구체적인 역할이 드러나는 이름으로 한번 더 고민해보면 어떨까 제안 드려봅니다 :)  

### 상수화
- 상수화도 필요하지 않은 부분들은 굳이 하지 않으셨던 것 같아 좋았어요. 
- 다만 threshold나 snackbar의 노출 시간 등 이후에 충분히 옵션값으로 자주 수정할 수도 있을 부분들, 의미있게 사용되는 부분들에 대해서는 중복으로 사용되지 않더라도 의미 있는 이름을 지어준다는 취지에서 상수화를 고려해보시면 좋을 것 같아요

### 일관성 
- 모듈 간의 연결방식이 각각 다른 것 같아요! 
- 어떤 방식이든 나름의 의도가 있다면 괜찮지만, 가능한 '일관성'은 꼭 지킬 수 있으면 좋겠습니다! 그래야 혹시 수정하게 되더라도 일관되게 수정이 가능하고, 이후 추가로 구현할 때에도 예측이 가능하니까요~!

### 테스트 코드
- 도메인 영역을 분리해주셨으니! 검색에 관한 테스트도 시도해보시면 어떨까요?

### 기능 테스트 제보 사항 
- 검색 결과 없음 -> 이후 재검색 시 결과 없음 이미지와 스켈레톤이 겹쳐보이는 오류가 있는 것 같아요! 
<img width="959" alt="스크린샷 2022-03-16 오후 9 10 55" src="https://user-images.githubusercontent.com/81607552/158587069-24d6e387-034c-4d85-82f2-a2a013d58b5b.png"> 
- 오류가 발생한 뒤에는 스켈레톤이 그대로 남아있는데요. 요 상태도 혹시 개선해보면 어떨까요?

2022-03-16 12:16 UTC, woowapark commented on src/js/domain/youtubeApi.js
> +    }
리뷰 받으셨던 것처럼 try...catch문으로 잘 감싸주셨네요 :)
- fetch 대상 url이 다소 복잡한 편인데, [URLSearchParams](https://developer.mozilla.org/ko/docs/Web/API/URLSearchParams)와 같은 API를 적용해보는 것도 고려해보시면 어떨까요?     
검색 파라미터를 변경해야 하는 경우, 지금처럼 url 스트링 내에 있는 것보다 조금 더 관리가 편리할 수 있을 것 같아요. 
- 응답은 왔으나 `reponse.ok`가 아닌 상황에 대한 대응이 빠져있는 것으로 보입니다. 이 경우 아무것도 return하지 않을 것 같네요! 어떻게 추가 대응하면 좋을 지 고민해보셔도 좋을 것 같아요 🙂

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/Result.js
> +  searchResultFoundTemplate(items) {
이름과 가독성은 사람마다 의견이 다를 수 있는 부분이라 항상 어려운데요..!     
`searchResultFoundTemplate`와 요 시리즈로 같이 사용해주고 있는 함수들의 역할은     
각 케이스에 맞는 `템플릿을 만들어주는 역할`인 것 같은데,       
언뜻 읽기에는 뭔가 '검색 하는' 혹은 '검색 결과를 ~하는'으로 읽힐 수도 있을 것 같아요..!          
뒤에 `-template`이 붙어 이전보단 개선된 것 같지만! 그래도 조금 더 적절한 이름이 혹시 있을까요?

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/YoutubeSearchModal.js
> +      if (e.keyCode === KEY_CODE_ESC) {
keyCode는 [현재 기준 deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)로 지정되어, 다른 옵션으로 가능하다면 다른 걸 권장드리고 싶은데요! 
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key 한번 비교해보시면 좋을 것 같습니당

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/Result.js
> +    $('.video-list').addEventListener('click', e => {
event delegation 적용 좋네요! 👍

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/Result.js
> +        video.save(e);
video를 도메인 영역으로 잘 분리해주셨는데요!     
요렇게 분리를 하셨다면...! 아래와 같은 부분도 추가로 고민해보실 수 있을 것 같아요
- save 함수로 event 객체를 그대로 넘겨주고 있는데요! event 객체라는 건 ui 영역에서만 알면 되는 정보이지 않을까요?
- save 내에서 `const videoId = e.target.closest('li').dataset.videoId;` 요렇게 꺼내서 쓰고 있는데요, DOM 구조가 변경되면 어떻게 될까요?

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/Result.js
> +        await delay(500);
- delay가 꼭 필요한가용 ?-?     
  - 스낵바를 위해 필요한 옵션이라면, 스낵바에서 자체적으로 제어할 수 있다면 더 좋을 것 같네요~?
-  `500`! 이라고만 되어 있으면 어떤 의미로 쓴 숫자인지 나중엔 까먹지 않을까요! (매직넘버 라고도 합니다 🙂)    

+)    
- 개인적으로는 promise 체인 내에 async/await가 혼용되어 잠시 멈칫...! 하기도 했습니당 🤔 약간 어색해보인다는 생각이 드는데 민초는 어떠신가요?

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/Search.js
> +    this.searchForm.addEventListener('submit', debounce(this.handleSubmit, 300));
debounce 적용 좋네요! 👏

2022-03-16 12:16 UTC, woowapark commented on src/js/domain/video.js
> +      e.target.setAttribute('hidden', true);
(domain으로 요 로직들이 분리되어 있다면)
12번 라인은 UI영역에서 해주어야 할 일이지 않을까요~?

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/Result.js
> +  renderInitialVideoList(json) {
사소하긴 하지만 요기의 `json`도 좀 더 구체적인 네이밍이 있지 않을까요~?

2022-03-16 12:16 UTC, woowapark commented on src/js/utils/dom.js
> +  }, 2000);
요기의 2000도 snackbar가 노출되는 시간이니, 충분히 의미 있는 상수로 빼도 좋을 것 같아요~ 
snackbar 노출시간을 조정해보고 싶다고 하면 찾아서 수정하기 쉽도록!

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/YoutubeSearchModal.js
> +    this.search = new Search();
모듈 간에 연결되는 방식이 어떤 경우에는 요렇게 멤버 변수로, 
어떤 경우에는 단순 import를 통해 가지고 오고 있는데요! 
요 차이에 대한 민초의 기준이 있으실까요?

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/Search.js
> +export default class Search {
요친구도 좀 더 구체적인 역할이 드러나는 이름이면 더 좋지 않을까...! 고민해보게 되네요!

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/Result.js
> +        $('.video-list').insertAdjacentHTML('beforeend', this.searchResultFoundTemplate(json.items));
DOM 셀렉팅은 꽤나 비싼 작업인데요! 
현재는 스크롤해서 다음 페이지를 불러올 때마다 `.video-list`를 새로 셀렉팅해오는 것 같아요. 
조금 더 브라우저의 일을 줄여줄 방법은 없을까요~?

2022-03-16 12:16 UTC, woowapark commented on src/js/ui/Search.js
> +      showSnackBar(MESSAGE.ERROR_BLANK_SEARCH_INPUT);
요구사항에 없었지만 스낵바도 적용해주셔서 좀 더 사용자 입장에서 친절하게 느껴지는 구현을 해주셔서 좋았어요! 👍👍👍
요건 민초가 스낵바까지 고민해주셔서 한번 남겨보는 제안! 
input의 필수값이니, 스낵바로 보여주는 방식 외에 input의 required 값을 지정해서 자체적으로 보여주는 방식도 있을 것 같아요.   
어떤 방식이 사용자 입장에서 보기 좋을 지 등에 대해 다양하게 고민해보시면 좋을 것 같습니다! (꼭 뭐가 더 낫다 아니다는 아닙니당ㅎㅎ)

2022-03-16 12:18 UTC, merged

2022-03-19 06:25 UTC, jswith commented on src/js/domain/youtubeApi.js
> +    }
- URLSearchParams 적용해보았습니다! 확실히 가독성이 더 좋아지고 관리하기 좋아졌다는 느낌이 들었습니다. [c9019b5](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/c9019b59ad6e2010aa6b503b055f4479833d331f)
- !response.ok가 발생할 시 오류를 던져주고, reponse.ok일 경우 정상적으로 리턴하도록 수정했습니다. 여기서 궁금한 점이 있는데, 개발자 입장에서는 HTTP 상태 코드에 따라 에러의 원인을 다르게 파악하겠지만 사용자 입장에서는 어떤 상태 코드로 인한 에러인지 알 필요가 없다고 생각해서 한 가지 메시지로만 표시해주었는데, 실제로는 보통 어떤 방식이 많이 사용되는지 궁금합니다. [cd3c6cf](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/cd3c6cf676586f63e5c55ddd78d46d011aaa94f5)

2022-03-19 06:28 UTC, jswith commented on src/js/ui/Result.js
> +  searchResultFoundTemplate(items) {
네이밍은 정말 너무 어려운 것 같습니다 ㅠㅠ grep.app에서 검색해보고 `searchResultTemplate`, `noSearchResultTemplate`으로 수정해보았습니다. [eb95efd](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/eb95efd78821aba22f9b7a6b9a42359b58ad9a2c)

2022-03-19 06:31 UTC, jswith commented on src/js/ui/YoutubeSearchModal.js
> +      if (e.keyCode === KEY_CODE_ESC) {
depreacted된 속성인 줄 몰랐었네요 🤦‍♂️ `key`로 수정하였고, keyCode뿐만 아니라 keypress도 deprecated된 속성이라는 걸 새롭게 알아갑니다! [08f9efb](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/08f9efbbd41d33936a7fbb870517a5a6ef398e22)

2022-03-19 06:37 UTC, jswith commented on src/js/ui/Result.js
> +        video.save(e);
- step2 진행하면서 video 내부 구조가 바뀌어서 아래 링크와는 구조가 조금 다를 수도 있습니다. 우선적으로 event 객체를 인자로 넘겨주는 부분을 수정했었습니다. event 객체를 다루는 부분이 UI인지 Domain인지 헷갈렸었는데 어느 정도 기준이 잡힌 것 같아요! 
- 구조가 변경되면 closest를 통해 dataset을 찾을 수 없을 것 같습니다. button에 직접적으로 dataset을 부여하는 방식으로 수정했습니다. 

[884d5e9](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/884d5e9efd98231e98cf0a42ec1433845d70f6a2)

2022-03-19 06:40 UTC, jswith commented on src/js/ui/Result.js
> +        await delay(500);
스낵바가 일정 시간 딜레이 후에 출력되도록 하기 위한 코드였습니다. 0.5초라는 짧은 시간이어서 사실 크게 체감이 없는 것 같아 딜레이 부분은 삭제하기로 결정했고, 수정했습니다! [2848c52](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/2848c528cfd2c58c46eb1067db9124ac511809b7)

2022-03-19 06:42 UTC, jswith commented on src/js/domain/video.js
> +      e.target.setAttribute('hidden', true);
> * step2 진행하면서 video 내부 구조가 바뀌어서 아래 링크와는 구조가 조금 다를 수도 있습니다. 우선적으로 event 객체를 인자로 넘겨주는 부분을 수정했었습니다. event 객체를 다루는 부분이 UI인지 Domain인지 헷갈렸었는데 어느 정도 기준이 잡힌 것 같아요!
> * 구조가 변경되면 closest를 통해 dataset을 찾을 수 없을 것 같습니다. button에 직접적으로 dataset을 부여하는 방식으로 수정했습니다.
> 
> [884d5e9](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/884d5e9efd98231e98cf0a42ec1433845d70f6a2)

위 코멘트와 함께 수정했습니다!

2022-03-19 06:44 UTC, jswith commented on src/js/ui/Result.js
> +  renderInitialVideoList(json) {
videoData로 수정해보았습니다! [edad87c](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/edad87c1787be49c2cf991f717dce2ae41c614cc)

2022-03-19 06:48 UTC, jswith commented on src/js/utils/dom.js
> +  }, 2000);
누구나 알아볼 수 있는 숫자라고 생각해서 따로 상수화를 하진 않았었는데, 차후에 노출 시간을 수정할 상황까지는 고려하진 못했었네요! 의미도 부여하고, 관리도 수월해져서 상수 처리 하는게 맞는 것 같습니다. [b290645](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/b2906452c58d34a501c35016a090f6f6e9905fca)

2022-03-19 06:51 UTC, jswith commented on src/js/ui/YoutubeSearchModal.js
> +    this.search = new Search();
무언가 기준이 있다기보다는 `페어와 처음 구현할 때는 전부 클래스로 구현 -> constructor가 비어 있는 클래스를 객체로 변경` 하는 과정에서 어디는 import로 불러오고, 어디는 new로 인스턴스화해서 불러오는 코드가 섞이게 된 것 같습니다! step2 진행하면서 일관성 있게 수정하였습니다. [1e12930](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/1e1293060ee6dd268896168bccf71e38a0a7483c)

2022-03-19 06:52 UTC, jswith commented on src/js/ui/Search.js
> +export default class Search {
YoutubeSearch 수정했습니다. 근데도 뭔가 마음에 들진 않네요 ㅠㅠ [5f2ed2e](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/5f2ed2ef5f60edb0737e45652b7fdc9f7ca8fd05)

2022-03-19 06:58 UTC, jswith commented on src/js/ui/Result.js
> +        $('.video-list').insertAdjacentHTML('beforeend', this.searchResultFoundTemplate(json.items));
한 번 검색해서 변수에 저장해두고, 해당 변수를 재사용하는 방식으로 수정했습니다.  

[ac345a1](https://github.com/woowacourse/javascript-youtube-classroom/pull/130/commits/ac345a13f76f682bfa9ddea9f5fca71d8b84a148)

2022-03-19 07:04 UTC, jswith commented on src/js/ui/Search.js
> +      showSnackBar(MESSAGE.ERROR_BLANK_SEARCH_INPUT);
이렇게 진행했던 이유는 사용자에게 메시지를 보여주는 방식을 통일하기 위해서였습니다! 로또 미션 진행하면서  HTML 자체적으로 form validation 해주는 부분이 개발자가 처리하는 부분보다 조금 더 안전하고, 실수할 여지를 줄여준다는 느낌이 들긴 했었습니다. HTML에서 지원해주는 부분은 적극 사용하고, 그렇지 않은 부분은 직접 구현해서 사용하는 방식으로 하는 것도 괜찮은 방법일 것 같아 required 속성 사용해보았습니다!