[1단계 - 나만의 유튜브 강의실] 호프(김문희) 미션 제출합니다.
woowacourse/youtube-classroom pull request #96
Opened 2022-03-11 08:39 UTC by moonheekim0118

# 나만의 유튜브 강의실
### [데모링크](https://moonheekim0118.github.io/javascript-youtube-classroom/)
안녕하세요 월터님 :) 리뷰이 호프라고 합니다! 만나뵙게 되어 영광입니다! 이번 미션 하면서 페어랑 이것저것 시도해보면서 정말정말 많이 소통할 수 있어서 재미있게 미션 수행했던 것 같습니다.
먼저 사용할 패턴을 정해놓지 않고 그 때 그 때 소통하며 필요한 부분을 채워나가고 저희만의 정답을 찾아가는 과정에서 많이 배웠습니다. 
 기능 목록, 설계 관련해서 아래에 정리해놓았습니다 :) 잘부탁드립니다.

## Step 1 기능 구현 목록 

- [x] [유튜브 검색 API](https://developers.google.com/youtube/v3/getting-started?hl=ko)를 사용해 내가 보고 싶은 영상들을 검색할 수 있다.
- [x] 엔터키를 눌러 검색할 수 있다.
- [x] 검색 버튼을 클릭해 검색할 수 있다.
- [x] 데이터를 불러오는 동안 현재 데이터를 불러오는 중임을 skeleton UI로 보여준다.
- [x] 검색 결과가 없는 경우 결과 없음 이미지를 보여준다.
- [x] 검색 결과 없음 이미지는 src/images/status/not_found.png 경로에 있다.
- [x] 최초 검색 결과는 10개까지만 보여준다. 스크롤을 내려 추가 검색 결과를 불러올 수 있다.
- [x] 검색 결과 화면에서 유저가 브라우저 스크롤 바를 끝까지 이동시켰을 경우, 그 다음 10개 아이템을 추가로 불러온다.
- [x] 내가 검색한 영상들의 json 데이터를 저장할 수 있다.
- [x] 실제로 동영상을 저장하는 것이 아니라, 영상 id를 Web Storage에 저장한다.
- [x] 이미 저장된 영상이라면 저장 버튼이 보이지 않도록 한다.
- [x] 저장 가능한 최대 동영상의 갯수는 100개이다.

## 구조

![](https://i.ibb.co/f27Zvs2/image.png)

### **Core**

- **Display**

  > DOM 요소를 직접적으로 조작하는 영역
  > **화면을 조작하는 영역과 UI 개발(마크업 개발) 영역 분리**를 의도
  > index.html : UI 개발 (마크업 개발) 영역
  > Display 내부 파일 : 앱 접속 이후 화면을 직접적으로 조작하는 영역
  
- **Store**

  > 비즈니스 로직을 담당하고, 그에 따라 업데이트 된 데이터를 저장하고 업데이트 되면 구독 중인 Display에게 알려주는 영역
### **Display**

- **Share**

	- Modal

	  > 모달의 경우 단순히 1개만 존재하는 것이 아닌, 범용성이 있는 요소라 생각하여 분리
	
- **YoutubeClassRoom**

	- Navigation

	  > 메인 화면의 상단 메뉴를 조작하는 영역
	  
	- SearchForm

	  > 유튜브 검색 모달의 사용자의 검색어 입력을 담당
	  
	- SearchResult

	  > 유튜브 검색 후 검색 결과를 출력하는 영역
	  
	  
### **Domain**

- YoutubeSearchStore

  > 현재 로딩 상태, 검색어와 유튜브에서 가져온 데이터를 저장하고 관리한다
  
- YoutubeSaveStorage

  > 사용자가 저장한 동영상의 아이디를 웹 로컬 스토리지에 저장 및 관리한다.
  >
  > ​	**데이터 저장 방식**
  > ​	[videoId, videoId, ...]
### **Api**

> API는 여러곳에서 사용될 것으로 예상하여 범용성을 위해 분리
## **Webpack 설정**
- 절대 경로 설정
- 환경 변수 설정
- 파일 로더 설정
- Sass 설정 : Step 2를 통해 추후 사용성을 고려할 시 가독성 좋은 스타일시트를 위해 설치

## Display - Store 는 아래와 같이 동작합니다.
- Display 에서 구독 할 Store 저장
- Display 내 이벤트 핸들링 시 필요 시 Store 에 Dispatch 하여 상태 변경 요청
- Store 에서 Dispatch 호출하여 상태 변경 및 비즈니스 로직 처리
- Store 에서 상태 변경시, 구독 중인 Display 내 함수 호출 

<br/>

그럼 잘부탁드립니다 :)  아직 부족한 코드지만 예쁘게 봐주세요.. 😺 .. 코드에서 나쁜 점이나 궁금한 점 콕콕 찝어주시면 감사하겠습니다. 👍 👍 👍

2022-03-12 15:35 UTC, inwalter99 commented
8ㅅ8 스크롤를 좀 쎄게(?) 내렸더니 API 요청이 엄청 쌓이는 바람에 (이러면 안되지만..) API 요청이 막혔네요 죄송합니다...
이 부분에 대해 보완이 필요해보이는데 코드 보면서 말씀 드려보겠습니당...

2022-03-12 16:32 UTC, inwalter99 requested changes
반가워요 호프 :)
구조에 신경을 많이 쓰신 게 느껴집니다 💯 짝코딩하면서 즐거우셨다니 부럽습니다 🥲 나만 페어 없어..
일단 코멘트 드린 것처럼 버그가 있어서 할당량을 순식간에 채워버렸습니다 죄송...
전반적으로 구조에 신경을 많이 쓰신만큼 코드 읽기도 프로젝트 흐름도 쉽게 파악할 수 있어서 좋았습니다 👍  궁금한 점과 제 생각들을 남겨봤는데 의견 주시면 감사하겠습니다!

2022-03-12 16:32 UTC, yongholeeme commented on src/js/__tests__/YoutubeSearchValidator.test.js
> +  });
제목과 달리 단순히 두 키워드의 동일한 지에 대한 테스트 케이스인 거 같습니다.
그리고 해당 함수에 대한 유닛 테스트가 필요할까? 라는 생각도 드네요..!

2022-03-12 16:32 UTC, yongholeeme commented on src/js/__tests__/YoutubeSearchStore.test.js
> +});
`__tests__` 디렉토리로 분리하는 것도 좋지만,
나중에 같은 depth 에 YoutubeSearchStore.test.js 로 위치해도 좋을 거 같아요.
비슷한 역할과 목적은 모여있으면 파악하기 쉽다고 생각하는데, 테스트 코드는 말그대로 역할과 목적, 그리고 대상이 뚜렷하니 함께 붙어있으면 어떨까합니다ㅎ

2022-03-12 16:32 UTC, yongholeeme commented on src/js/api.js
> +      }&pageToken=${nextPageToken}`,
이 부분이 한 눈에 안들어오는 거 같아요! URI builder 함수를 만들어봐도 좋고 https://developer.mozilla.org/ko/docs/Web/API/URLSearchParams 를 이용해도 좋을 거 같습니다 ;)

2022-03-12 16:32 UTC, yongholeeme commented on src/js/constants/Selector.js
> +  return Object.freeze(output);
createElement 를 하기 위해서 removeSelectorSymbol 가 필요해졌군요...
해당 코드를 forEach 대신 reduce 로 바꿔봐도 좋을 거 같습니다 ;) 
(바꾸지 않아도 충분하긴 해요ㅎ)

2022-03-12 16:32 UTC, yongholeeme commented on src/js/constants/String.js
> +});
string 은 단순 문자열을 기대하는 게 됩니다. ACTION_TYPE 은 constants/action..? 정도로 분리되면 어떨까 싶네요.

그리고 파일명은 보통.. 클래스나 컴포넌트만 PascalCase 로 작성하는 거 같아요 ;ㅁ;

2022-03-12 16:32 UTC, yongholeeme commented on src/js/core/Display.js
> +  }
별도로 init 을 묶어줄 필요는 없어보입니다.

```suggestion
    this.setContainer();
    this.defaultElement();
    this.bindEvents();
    this.subscribeStores();
  }
```

2022-03-12 16:32 UTC, yongholeeme commented on src/js/core/Display.js
> +      if (eventType === 'submit') event.preventDefault();
preventDefault 가 eventType 이 submit일 때만 필요할까요? 👀 
현재는 그럴 수도 있지만, 추상클래스로 정의하신 이상 조금 더 범용성있게 작성되면 좋을 거 같습니다 ;)

2022-03-12 16:32 UTC, yongholeeme commented on src/js/core/Display.js
> +  defaultElement() {}
보통 함수의 네이밍은 동사/명령형으로 작성을 합니다!

2022-03-12 16:32 UTC, inwalter99 commented on src/js/domain/YoutubeSearchStore.js
> +    stateByType[type] && stateByType[type]();
매 번 함수들이 새롭게 만들어질 필요는 없을 거 같은데,
함수를 별도로 정의하고 switch 등을 이용해서 호출하면 어떨까요?

2022-03-12 16:32 UTC, inwalter99 commented on src/js/domain/YoutubeSearchStore.js
> +      },
UPDATE_SEARCH_LOADING_STATUS 와 isLoading: true 로 만드는 것간의 동작이 100% 일치하는 것 같진 않습니다!

2022-03-12 16:32 UTC, inwalter99 commented on src/js/display/index.js
> +  youtubeClassRoomPage() {
요 함수의 역할은 뭘까용?

2022-03-12 16:32 UTC, inwalter99 commented on src/js/display/YoutubeClassRoom/SearchResult.js
> +  }
이 부분이 문제가 되고 있는 거 같습니다!
observing 되고 있을 때 계속해서 핸들러가 호출되니까요. 로딩 상태 제어라던지.. 수정이 되어야 할 거 같아요.

2022-03-12 16:32 UTC, inwalter99 commented on src/js/display/YoutubeClassRoom/SearchResult.js
> +  drawResultNotFound() {
draw 보단 get 같은 게 더 어울리는 함수같습니당

2022-03-13 03:30 UTC, moonheekim0118 commented on src/js/__tests__/YoutubeSearchValidator.test.js
> +  });
지금보니 테스트 제목이 올바르지 않네요.. 그런데, validation을 처리해주는 함수들은 모두 유닛테스트를 진행해줬는데, 이정도로 간단한 함수는 테스트를 별도로 하지 않아도 될까요..? 이런부분은 e2e테스트로 진행해주는 편이 더 좋을까요?

2022-03-13 03:31 UTC, moonheekim0118 commented on src/js/__tests__/YoutubeSearchStore.test.js
> +});
그렇게 쓸 생각은 못했는데, 확실히 그러면 테스트 수정하기도 용이하겠네요! 감사합니다 !

2022-03-13 03:52 UTC, moonheekim0118 commented on src/js/core/Display.js
> +  }
저는 나중에 코드 읽을 때 '아 이게 초기화 함수구나~'라는 걸 개발자가 쉽게 알게해주도록 init이란 메서드로 묶어줬었는데요, 생각해보니 생성자 자체가 초기화의 역할을 하기 때문에 굳이 분리해줄 필요가 없다는 것을 깨달았습니다.. :) 감사합니다!

[ad1659f](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/ad1659f18551a00f6ce4dac06c49f54451979fc9)

2022-03-13 04:06 UTC, moonheekim0118 commented on src/js/core/Display.js
> +      if (eventType === 'submit') event.preventDefault();
그 부분까지는 고려하지 못했습니다ㅎㅎ. 그래서 아래와 같이 바꾸어봤습니다. 매개변수가 4개를 넘어가서 함수 쓸 때 불편해서 객체로 받아오도록 수정해보았습니다.
일단 preventDefault 여부를 함수 외부에서 정할 수 있도록 수정했는데요, isPreventedDefault..라는 네이밍이 적절할지 고민입니다. t/f 값이여서 is~로 네이밍을 해보았습니다!

```javascript
addEvent({ eventType, selector, handler, isPreventedDefault = false }) {
    const children = [...this.container.querySelectorAll(selector)];
    const isTarget = target => children.includes(target) || target.closest(selector);

    this.container.addEventListener(eventType, event => {
      if (isPreventedDefault) event.preventDefault();
      if (!isTarget(event.target)) return false;
      handler(event);
    });
  }
```

[95c07e9](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/95c07e95cece488092ccce506c0ffb3b23f127b9)

2022-03-13 05:37 UTC, moonheekim0118 commented on src/js/display/YoutubeClassRoom/SearchResult.js
> +  }
넵 이 부분에서 isLoading 이 true 면 핸들러 호출을 하지 않도록 막았습니다 ! 

[c5a3dcf](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/c5a3dcfd7b58418339dc9031861717572a6eab12)

2022-03-13 05:52 UTC, moonheekim0118 commented on src/js/domain/YoutubeSearchStore.js
> +      },
동의합니다! 그래서 아래와 같이 인자를 받아와서 해당 인자값으로 update 시켜주도록 수정했는데 괜찮을까요?
따로 isLoading:true 로 만들어주는 메서드보다 재사용성이 좋을 것 같아서요!
```javascript
    [ACTION_TYPE.UPDATE_SEARCH_LOADING_STATUS]: isLoading => {
        this.setState({ ...this.state, isLoading });
      },
```
[1a702e6](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/1a702e6b590ec6023e20e3a485ade1cb09a1d7b1)

2022-03-13 06:08 UTC, moonheekim0118 commented on src/js/constants/String.js
> +});
지금보니 String 이라는 파일명이 올바르지 않았었네요. 두개 모두 action 과 message 로 분리해주었으며 Constants 폴더 내부 파일명도 수정했습니다 :) 이 부분 페어랑 상의를 했어야했는데 놓쳤네요 😭 집어주셔서 감사합니다!

[6de443b](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/6de443b12ce4aad09094b921ea54595394d45840)

2022-03-13 06:21 UTC, moonheekim0118 commented on src/js/core/Display.js
> +  defaultElement() {}
넵. 위에서는 setContainer 라고 해놓고 여기에는 defaultElement라고하니 일관성도 없네요..다음부터는 잘 챙기겠습니다ㅎㅎ 메서드명 setDefaultElement로 수정해주었습니다 👍 

[d769cb7](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/d769cb7318642da98b6b615f50100ab7283e838d)

2022-03-13 06:33 UTC, moonheekim0118 commented on src/js/domain/YoutubeSearchStore.js
> +    stateByType[type] && stateByType[type]();
생각해보니 dispatch 호출할 때마다 객체,함수를 계속 새로 생성해주고 있었군요 😱 .. 이 부분 반영해서 아예 클래스 생성시 reducer 객체를 선언하는 함수 (setRedcuer)를 실행하고, dispatch 에서는 reducer를 호출만 하도록 수정했습니다. 
그런데 reducer 라는 네이밍 괜찮을까요? 대체로 리덕스에서 switch 문으로 새로운 값을 생성하는 함수를 reducer라고 사용하는걸로 알고 있는데,, 그냥 저렇게 바로 상태를 바꿔주는 함수를 값으로 갖는 객체에도 reducer라는 네이밍이 유의미할지 고민입니다. 더 좋은 이름이 떠오르지 않습니다 !! 😭 월터님의 의견이 궁금합니다...!!

[d819bec](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/d819bece12f030095f778725eb9f997183340cec)

2022-03-13 09:35 UTC, moonheekim0118 commented on src/js/api.js
> +      }&pageToken=${nextPageToken}`,
우왓 .. URLSearchParams라는 인터페이스가 있는지 처음 알았어요! 첨부해주신 자료 잘 읽었습니다 🙇 🙇🙇
이번에는 직접 uriBuilder 함수를 만들어보고싶어서 아래와 같이 만들어보았습니다. 일단 params 객체를 매개변수로 받아와서 key,value 값을 직접 넣어주었어요. 이렇게하니 훨씬 읽기 편하네요. 감사합니다 😃 

```javascript
export const uriBuilder = (uri, params = {}) =>
  `${uri}?${Object.entries(params)
    .map(([key, value]) => `${key}=${value}`)
    .join('&')}`;

```

2022-03-13 14:06 UTC, moonheekim0118 commented on src/js/constants/Selector.js
> +  return Object.freeze(output);
reduce메서드로 쉽게 객체를 생성 할 수 있었군요... 😱  처음알아가는 사실입니다 감사합니다!!
그런데, 해당 함수가 꼭 필요할지는 고민입니다..저도 이번에 removeSelectorSymbol을 처음사용해보았거든요.
모든 DOM_ELEMENTS를 일일이 선언해주는게 좋을까요? 아니면 위와 같이 함수로 자동으로(?) 생성되게 해주는게 좋을까요?
물론 성능 상은 미세하게나마 일일이 선언해주는게 좋겠지만, 나중에 DOM 구조가 변경될 경우에 모두 다 수정해야해서 굉장히 번거로울 것 같거든요. 월터님 생각은 어떠신지 궁금합니다 :) 

[7181d75](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/7181d755ffdf86a01ed363583a63316dcfc49d57)

2022-03-13 15:07 UTC, moonheekim0118 commented on src/js/display/YoutubeClassRoom/SearchResult.js
> +  drawResultNotFound() {
넵. 다시보니 draw해주는게 아니라, 단순히 템플릿을 리턴해주는 메서드여서 prefix를 get으로 모두 수정해주었습니다 : ) 다음부터는 주의해보겠습니다. ㅎㅎ 
[43eeeab](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/43eeeab8e0eddf5027ef6ba9f557402ce818d696)

2022-03-13 15:14 UTC, moonheekim0118 commented on src/js/display/index.js
> +  youtubeClassRoomPage() {
저와 페어의 의도는 Modal 은 범용적으로 사용되는 Display이기 때문에 생성자에서 생성해주었고 ,그 외의 youtubeClassRoomPage에만 한정된다고 생각되는 Display는 youtubeClassRoomPage에서 선언을 해주었습니다.
그런데 지금 보니 굳이 이렇게 메서드로 분리하여 Display를 생성하는게 되게 불필요하게 느껴지고 심지어 IndexDisplay를 클래스로 선언해야하는 이유도 모르겠네요..ㅎㅎ 굳이? 생성자 실행하자고 클래스로 선언하는건 불필요하게 느껴졌거든요.
그래서 아래와 같이 그냥 함수로 수정했습니다.

```javascript
const initDisplays = () => {
  new Modal();
  new Navigation();
  new SearchForm();
  new SearchResult();
};
```

[a992fd8](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/a992fd8ca9cb112eadea2cd05417bd9f962669ff)

2022-03-13 16:22 UTC, moonheekim0118 commented
안녕하세요 월터님 😃  너무너무 좋은 피드백 감사드립니다. 🙇 🙇  정말 많이 고민하고 생각하면서 코드를 다시 살펴볼 수 있었던 기회였습니다. 👍
일단 피드백 반영한 부분은 아래와 같아요.

- [x] 제보해주신 버그! 제거했습니다. (로딩상태일 때에도 데이터를 로드하는 에러)
- [x] uriBuilder 함수를 생성하여 uri 파라미터 지정을 간단하게 해주었습니다.
- [x] 불필요한 파스칼 케이스 파일명 제거 
- [x] 테스트 파일 위치 수정 (이렇게 하니까 원본 함수랑 비교하기도 수월하고 어떤 테스트코드를 작성했는지 한눈에 볼 수 있어서 증말 좋드라구용.. 짱짱..👍 )
- [x] 불필요한 init 메서드 제거
- [x] 메서드명 수정 ( draw -> get)
- [x] dispatch 호출시 계속해서 객체가 새로 생성되는 문제 리팩토링 



그리고 추가로 코드를 고치면서 고민들이 많이 늘어났는데요, 월터님의 의견을 듣고싶습니다. 
**1. 서버 에러 처리 관련**
- 현재 같은 경우에는 유튜브 api 가 !response.ok 일 경우 '서버에러'라고 통칭하여 사용자에게도 그냥 서버에러가 일어났습니다~라고 알려주고 끝냈는데, 이렇게 하는 방식이 괜찮을까요 ? 사용자는 서버에러의 디테일을 알 필요 없다고 생각해서 이렇게 처리했습니다. 현업에서는 프론트엔드에서 서버에러를 어떻게 처리하는지 궁금해요!

**2. 추상클래스를..사용해야할까요?**
- 지금 같은 경우 Core에 Display와 Store 추상클래스가 있는데요, display 추상클래스의 경우 반복되는 것을 줄이기 위해서 만들어서 어느정도 납득은 되지만, 다시 돌아보니 Store 추상클래스는 성급한 추상화가 아닐까 생각이들어요. 🥲 
그리고 또한 단순히 '반복되는 로직'을 하나로 뭉치기 위해서 추상클래스를 사용하는 것이 올바른지도 의문이 들기도 해요.
월터님의 경우는 어떨 때 추상클래스를 사용하는지, 현재 단계에서 추상화는 어떻게 생각하시는지 의견을 구하고 싶어요!


**3. 테스트 관련**
- 테스트 관련해서 정말정말 많이 고민하고 있는데요, 현재는 유틸성 함수랑 Store의 dispatch 메서드만 한정적으로 테스트하고 있습니다. 웹스토리지를 조작하는 클래스는 따로 테스트하지 않은 이유가 제가 웹스토리지를 mocking해야하기 때문인데요, _웹스토리지를 mocking하여 웹스토리지를 조작하는 클래스를 테스트한다?_ 는  테스트를 위한 테스트같아서 작성하지 않았습니다. 월터님은 웹스토리지를 조작하는 메서드를 어떻게 유닛테스팅하시나요? 이 부분은 따로 테스트하지 않는게 맞을까요?
- 아래와 같은 유틸성 함수나 Store 관련 메서드를 테스트하면서도 ,,, 어떻게하면 더 잘 테스트할 수 있을지 고민입니다. 테스트 할 데이터를 더 추가하는게 좋을 듯한데, 그렇다면 그 데이터는 어떠한 기준으로 추가해야할까요? 이에 대한 답변이 절실합니다 🥲 ..

```javascript
test('시스템 시간을 YYYY년 MM월 DD일의 형태로 반환한다.', () => {
  const timeString = '2020-11-27T08:13:35Z';
  const parsedTime = '2020년 11월 27일';
  expect(getParsedTime(timeString)).toBe(parsedTime);
});

test('파라미터값을 받아서 올바른 uri을 생성한다.', () => {
  const baseUri = 'http://google.com';
  const params = {
    q: 'keyword',
    maxResult: 5,
  };
  const uri = `${baseUri}?q=keyword&maxResult=5`;
  expect(uriBuilder(baseUri, params)).toBe(uri);
});

```

2022-03-14 14:16 UTC, yongholeeme commented on src/js/__tests__/YoutubeSearchValidator.test.js
> +  });
지극히 개인적인 생각입니다만, isSameKeyword 같이 단순 문자열을 비교하는 함수를 테스트해줘야할까?라는 생각을 합니다..ㅎ
테스트코드도 비용이거든요, e2e 테스트나 통합테스트로 작성한 다음 다른 사이드이펙트 방지를 테스트하는 건 의미가 있을 순 있겠으나 === 만 수행하는 테스트를 해야하나!!!해야할까? 라는 생각으로 의견을 드렸습니다!

2022-03-14 14:18 UTC, inwalter99 commented on src/js/api.js
> +      }&pageToken=${nextPageToken}`,
커밋 링크까지 공유해주셔서 넘넘 감사합니다 ㅎㅎ 👍 
URIBuilder 에 대한 테스트도 이루어지면 어떨까해요 예를 들면 지금 params 가 빈 객체라면 뒤에 불필요한 문자가 들어갈 거 같아영 (문제는 ㅇ전혀 없지만)

2022-03-14 14:21 UTC, yongholeeme commented on src/js/constants/Selector.js
> +  return Object.freeze(output);
개인적으로는 글쎄입니다 ㅠㅠㅎ 사실 현업에서는 DOM 을 Selector 로 조작할 일은 거의 없다고 봐도 되는데요...
물론 상수를 사용함으로써 변경에 용이하겠지만,  HTML 에도 상수를 사용하는 게 아니라면 글쎼.. 개인적으론 가독성이 크게 떨어지는 것 같아서 사용하진 않을 듯 합니다ㅎㅎ..

2022-03-14 14:22 UTC, yongholeeme commented on src/js/constants/Selector.js
> +  return Object.freeze(output);
추가로 Object.freeze 하시는 것도 필요할까 의문이 들어용ㅎㅎ.. 해당 객체에 접근할 수 있는 건 우리 개발자들 밖에 없는데, 변수명부터 나 상수야!!!!!! 건들지마!!! 라서 ㅎㅎㅋㅋㅋㅋ

2022-03-14 14:25 UTC, inwalter99 commented on src/js/constants/String.js
> +});
진리의 케바케.... 죄성합니다ㅜ
프로젝트 규모가 작다면 그냥 constants.js 에 모두 정의할 때도 있고, 점점 커져 역할에 나눌 필요가 있다면 분리할 때도 있습니다.
(개인적으론 작을 땐 constants.js 에 정의하고 커짐에 따라 개선하는 걸 선호합니다! [YAGNI](https://martinfowler.com/bliki/Yagni.html) 원칙을 좋아합니다ㅋㅋ)
그리고 범용성있게 사용되지 않는 상수는 보통 그 상수를 사용하는 파일 내에 정의할 때가 많은 거 같구요!

2022-03-14 14:27 UTC, yongholeeme commented on src/js/core/Display.js
> +      if (eventType === 'submit') event.preventDefault();
먼저 객체로 수정하신 것 너무 좋습니다 :) 함수 3개 이상일 땐 객체로 바꾸는 게 좋다는 의견 (클린코드 책) https://github.com/qkraudghgh/clean-code-javascript-ko#%ED%95%A8%EC%88%98functions 도 있습니다 ㅎㅎ

2022-03-14 14:30 UTC, yongholeeme commented on src/js/core/Display.js
> +      if (eventType === 'submit') event.preventDefault();
그리고 저는 preventDefault 는 사용하는 핸들러에서 명시적으로 사용하는 게 더 나을 것 같아요! 보통 event.preventDefault 는 핸들러 내부에서 호출하는데, 그 코드가 한 depth 더 위에 있기 때문에 코드 파악하는 데 어려움이 있을 수도 있을 것 같습니다!
isPreventedDefault 란 네이밍은 적절한..것 같습니다ㅎ 사실 이렇게 파라미터로 컨트롤한 적이 없어서 어색하긴 하네요ㅜㅋㅋ

2022-03-14 14:41 UTC, inwalter99 commented on src/js/domain/YoutubeSearchStore.js
> +    stateByType[type] && stateByType[type]();
ㅎㅎ말씀해주신 것처럼 우리가 알고 있는 reducer 처럼 동작하게 하려면 dispatch 함수 부분이 변경되어야할 것 같긴해요 :0

2022-03-14 14:42 UTC, yongholeeme commented on src/js/domain/YoutubeSearchStore.js
> +      },
ㅎㅎ넵 위에서 말씀해주신 것과 유사하게 보면 payload 를 넘기는거죵ㅎ

2022-03-14 15:08 UTC, yongholeeme commented
흑흑 그나저나 아직 API 요청 초과이군요..

> 1. 서버 에러 처리 관련

에러는 친절할수록 좋습니다만, 진짜 에러를 보여줘선 안되겠죠ㅎㅎ 진짜 에러를 보여준다면 보안과 직결된 문제이기 때문에 프론트엔드에선 에러에 대해서 직접적으로 보여주지 않고, 얼럿이나 토스트를 통해서 친절하게 풀어서... 제공합니다ㅎ

> 2. 추상클래스를..사용해야할까요?

아무래도 오버엔지니어링이나 지금 이 구조에서 이게 과연 맞을까?에 대해서 고민이 많으실 거 같아요! 걍 말씀드리자면ㅋ 웬만한 패턴 다 안맞을거에요ㅎㅎ; 지금도 앞으로도 비교적 작은 프로젝트일테니까요..ㅎ 다만 지금은 학습과정에서 이것저것 해보면서 느껴보는 게 중요하다고 생각해요. 지금 MVC, 추상화 등을 해보면서 호프가 느껴야할 점은 일단 '일단 지금같이 작은 프로젝트에서는 좀 맞지 않네ㅎ.., 이 프로젝트가 ~~~~~방향으로 발전하면 이렇게 쓰이려나? 쓰이겠구나 그러면 이 부분이 유효하게 작용할 거 같다.' 정도..이지 않을까 싶습니다!

> 3. 테스트 코드

말씀주신 것처럼 저도 웹스토리지 자체를 테스트할 필요는 없다고 생각해요. 다만 웹스토리지에서 **가져와서 데이터를 조작하는 비즈니스 로직 부는 테스트해야합니당.** 만약 비즈니스 로직이 웹스토리지가 필요하다면 디펜던시를 줄여서 모킹할 수 있는 구조로 변경을 해야할 것 같습니다.

널리 쓰이는 유틸성 함수같은 경우, 현업에서도 있는 라이브러리를 사용할 때도 있고, 재미상(?) 직접 만들어 쓰는 경우도 (사실 더 많음) 왕왕 있습니다. 그럴 때 비슷한 유틸 라이브러리를 찾아서 테스트 코드를 보면서 엣지 케이스나 고려할 점들을 참고하면서 테스트 코드를 짜곤 합니다ㅎㅎ.. 
그게 아니라 프로덕트 내에 특정 상황을 다루는 유틸 함수라면 기획이나 엣지 케이스를 직접 만들어서 최대한 범위를 맞춰야겠죠 : 0 
테스트 코드는 어디까지나 우리 개발자가 작성하는 거기 때문에 완벽할 순 없고, 개발자 역량과 경험에 따라 그 촘촘함도 달라진다고 생각합니다. 이 부분은 다른 테스트코드를 많이 보면서 경험을 쌓는 것 밖에 없다고 답을 드릴 수 밖에..ㅠ..

2022-03-14 15:11 UTC, inwalter99 requested changes
고생하셨어요 호프 :0 
친절하게 커밋 링크 남겨주신 부분 덕분에 리뷰하게 너무 수월했습니다 👍 
step2 넘어가기 전에 event.preventDefault 랑 말씀주신 reducer 부분만 개선되면 좋겠습니다..!
전반적으로 넘 좋습니다 ㅎㅎ 질문에 대해 답변도 남겼는데 , 의견 또 환영입니다!

2022-03-15 11:06 UTC, moonheekim0118 commented on src/js/constants/Selector.js
> +  return Object.freeze(output);
ㅋㅋㅋㅋ Object.freeze에 관한 설명 감사합니다!! 너무 잘 이해되었어요 😄 
그리고 아무리 생각해도 Selector 상수는 대부분 한번, 최대 두번밖에 쓰이지 않아서 제거했습니다. 👍 

[e231fc7](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/e231fc715d5abab006e7f15cda9a694b6244866e)

2022-03-15 11:15 UTC, moonheekim0118 commented on src/js/constants/String.js
> +});
아닙니다 너무 도움되었어요! 
정리하고나니.....상수 객체가 딱 세 개 뿐이어서 저 역시 constants.js 파일에 정의하는 방향으로 수정했습니다. 이러니 훨씬 간결해지네요 👍 👍  감사합니다.

[983179b](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/983179b9296db0cc217b36824c7d60ffc701869b)

2022-03-15 11:24 UTC, moonheekim0118 commented on src/js/core/Display.js
> +      if (eventType === 'submit') event.preventDefault();
네 감사합니다 :) 어차피 핸들러에 event 를 인자로 넘겨주기 때문에 핸들러에서 처리하는게 맞다고 판단했습니다.
addEvent 할 때, preventDefault 여부를 처리하기 어렵기두 하구요 ! 👍 👍  좋은 의견 감사합니다!
첨부해주신 문서도 잘 읽겠습니다 :)

[618888b](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/618888bb0b6b133b94ad46533f31611a0cc58e62)

2022-03-15 11:28 UTC, moonheekim0118 commented on src/js/__tests__/YoutubeSearchValidator.test.js
> +  });
네. 저도 계속 고민한 결과 이렇게 간단하고 따로 데이터 조작이나 연산이 없는 함수에는 굳이 테스트가 필요하지 않다고 결론지었습니다 :)
테스트코드도 비용!! 새기겠습니다 ... 💯 👍 

[5f6fd89](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/5f6fd8990d7ff0f3e16e689c9ab3127a444b8d68)

2022-03-16 00:35 UTC, moonheekim0118 commented on src/js/api.js
> +      }&pageToken=${nextPageToken}`,
네네! 
일단..원래는 uriBuilder를 위처럼 직접 만들어봤지만, 웹 api를 사용 할 수 있으면 사용하는게 좋다고 판단되어 URLSearchParams를 사용하는 방향으로 변경했습니다 :) [ee0a81a](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/ee0a81a07bca0915c1cb5394b5b4af573f386f57)

그리구 uriBuilder [테스트코드](https://github.com/moonheekim0118/javascript-youtube-classroom/blob/moonheekim0118/src/js/utils/dataManager.test.js)도 이렇게 작성하긴 했는데...ㅠ_ㅠ..충분한지는 모르겠네요. 일단 params가 들어간 경우, 빈 객체가 들어간 경우 모두 테스트해주었습니다.[f259949](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/f25994968eadfe425427e8f91805f13b296dbb8c)
  흑 흑 감사합니다 👍

2022-03-16 00:36 UTC, moonheekim0118 commented on src/js/domain/YoutubeSearchStore.js
> +      },
UPDATE_SEARCH_LOADING_STATUS는 리듀서 작동방식을 바꾸면서..제거되었습니다 👍 👍

2022-03-16 07:18 UTC, moonheekim0118 commented
안녕하세요 월터님 :) 친절한 답변 너무너무 감사드립니다. 정말 많이 도움되었어요. 특히나 2번 질문에 대한 답변을 듣고…많은걸 깨달았습니다. ㅎㅎㅎ 월터님 조언 듣고 완벽한 설계를 찾으려고하지 않고 그냥 이것저것 많이 시도해보고 실패해보는걸 목표로 삼고 이번 피드백을 반영해보았어요. 그랬더니 !!! 더 즐겁게 코딩하게 되더라구요 ㅋㅋㅋ정말정말 감사합니다. 
에러처리,테스트코드에 대한 조언도 정말 감사드립니다 :) 시간상 지금 당장 적용은 못했지만 ^_ㅠ..2단계에 꼬오옥 더 성장한 에러처리&테스트코드를 들고와보도록 노력하겠습니다 : ) 친절한 답변 다시 한번 감사드립니다 ( _ _ )

월터님께서 말씀해주신 preventDefault랑 리듀서 뿐만 아니라 여러가지 변경해본 사항 아래 정리했습니다 :) 너무너무 감사했습니다 !


### 추상 클래스 제거
 [64759b9](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/64759b9952ed9beda7554fa0b47be201c433eb10) 
 [8f9feb0](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/8f9feb0e0bd14fb400f75f46a88df239f46c5a38) 
이번 미션에서는 괜한 추상화라는 것을 깨달았어요. 오히려 추상클래스를 제거하니까 더 코드 읽기도 편하고 깔끔해진 것 같아요. 특히나 Store같은 경우는..사실상 하나 밖에 없기 때문에 아예 필요가 없었네요 ㅋㅋㅋ… 
또한, 모든 Display에서도 addEvent를 메서드로 들고있어야 할 필요도 없다고 판단하여 util 로 분리했습니다.


### 이벤트 핸들러 메서드를 클래스 필드로 수정
 [38f1eb1](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/38f1eb17398d3c31904082c70cf1112d589d3adc) 
이건 제가 학습하면서 고쳐본 부분인데요 월터님의 의견도 궁금합니다. 이벤트 핸들러를 클래스 메서드로 정의 할 경우 꼭 this binding을 해주면서 결과적으로 새로 생성한 함수를 핸들러로 사용하게  되잖아요?? 근데 그게 너무 비효율적이라고 판단되어 이벤트 핸들러 메서드를 화살표 함수로 변경해보았습니다 .물론, 이러면 클래스필드로 등록이 되어서 나~~중에 성능상 문제가 생길 수 있겠지만, 현재 규모에서는 무리없고 오히려 좋다고 생각했습니다 !

### 리듀서 / 디스패치 수정
 [a90cbac](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/a90cbacd736641fa632d750977745d3a0e4a1d5c) 

- 이전에는 리듀서에서 setState를 직접 호출해서 상태를 변경했는데요, 그렇게 구현했던 이유가 비동기 처리 때문이었습니다. 근데 그러다보니 월터님이 피드백 주신대로 ‘리듀서’의 주 목적(새로운 상태 반환)에서 벗어나게 되더라고요. 그래서 실제 리덕스에서는 어떻게 리듀서에서 비동기 처리를 작업하는가?? 봤더니 미들웨어 라이브러리 (redux-thunk,saga…)를 사용하고 액션타입을 3가지 (REQUEST,SUCCESS,FAIL)로 나누더라구요!
그래서 저도 일단 api호출과 관련된 액션타입은 세 가지(REQUEST,SUCCESS,FAIL)로 나누어봤어요
1. 사용자가 검색했을 때 REQUEST dispatch
2. REQUEST dispatch가 들어오면 리듀서 실행 / 미들웨어 실행
3. 미들웨어에서 api 호출
4. Api 에서 연산 후 ,SUCCESS or. FAIL dispatch

그래서 간단하게 아래처럼 middleware에 비동기 호출 함수를 넣어놓고 dispatch 에서 리듀서 호출시 함께 호출해주도록 구현해봤어요 .. ~..확실히 이렇게하니까 리듀서가 새로운 상태 반환의 역할만 해주니까 책임 분리가 명확해진 것 같습니다. 
```javascript

const middleware = {
  [YOUTUBE_SEARCH_ACTION.UPDATE_SEARCH_RESULT_REQUEST]: async state => {
    await requestYoutubeSearch(state.searchKeyword, state.nextPageToken);
  },
};

dispatch(type, payload) {
    if (!this.reducer[type]) return;
    this.setState(this.reducer[type](this.state, payload) ?? this.state);
    this.middleware[type] && this.middleware[type](this.state, payload);
  }


```

그리고 리듀서랑 미들웨어는 생성자에서 인자로 넣어주도록 했습니다. ( [d4e83de](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/d4e83de3dcbcf52856637e82c5559c2d53067f5a) )


### UriBuilder 수정
[ee0a81a](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/ee0a81a07bca0915c1cb5394b5b4af573f386f57)
- 이전에는 그냥 제가 직접 Object 순회해서 map해주었는데요...그냥 웹 api 를 믿기로 했습니다 ㅋㅋㅋㅋㅎㅎ 해당 테스트코드([f259949](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/f25994968eadfe425427e8f91805f13b296dbb8c))도 간단하게나마 작성했습니다.


### api timeout 구현
[94ce14b](https://github.com/woowacourse/javascript-youtube-classroom/pull/96/commits/94ce14b80489c13fec28c8f4daf67b5c5008233e)
생각해보니 api 요청 로딩시간이 길어지면 무한대로 스켈레톤 UI만 보여지게 되더라고요 ? 그러면 사용성이 떨어질 것 같아서 방법을 강구하다가 AbortController 라는 웹 api를 사용해서 아래와 같이 api request timeout 을 구현해보았습니다 !
테스트코드도 작성해보고싶었지만...AbortController가 웹 api라서 테스트가 안되더라구요ㅋㅋㅋㅎㅋㅋㅋ그래서 일단 구현만 해놓았습니다 혹시 잘못된 사항 있다면 알려주시면 감사하겠습니다 :) 

```javascript
const controller = new AbortController();
const { signal } = controller;
const timeout = 8000;

const request = async (uri, options) => {
  const timer = setTimeout(() => controller.abort(), timeout);
  const response = await fetch(uri, { ...options, signal });

  if (!response.ok) throw new Error('서버 오류');
  const data = await response.json();
  clearTimeout(timer);
  return data;
};

```

그러면 혹시 또 수정하거나 반영해야 할 사항 있다면 알려주시면 감사하겠습니다 👍 👍 👍 👍

2022-03-16 11:40 UTC, inwalter99 commented
배포된 버전에서 검색 쿼리값에 잘못된 값이 들어가고 있는 거 같아요 @.@
<img width="439" alt="image" src="https://user-images.githubusercontent.com/28642472/158582053-0865d2ae-bb9c-4d9a-aaf6-6efbde52f482.png">

2022-03-16 11:54 UTC, moonheekim0118 commented
@inwalter99 앗...죄성합니다 ㅠ_ㅠ 금방고치겠습니다

2022-03-16 12:09 UTC, moonheekim0118 commented
@inwalter99 
월터님...! 제가아무리 요리조리 돌려보고 배포도 다시해봐도 쿼리값이 잘 들어가는데 혹시 어떤 환경인지 알려주실 수 있으실까요 ?ㅅ? 
![](https://i.ibb.co/TbnhDMy/2022-03-16-9-08-24.png)

2022-03-16 12:17 UTC, inwalter99 commented
아까는 저렇게 들어갔는데 @.@ 지금은 잘 요청되는 거 같습니다. 
근데 q 를 인코딩해서 보내야하나용? 디코딩을 따로 안하는 거 같아요! 한글은 이상한 결과가...

2022-03-16 12:21 UTC, moonheekim0118 commented
이 부분 수정했습니다..ㅎㅎㅎ그냥 별 생각없이 인코딩해서 보내야한다고 생각했네요..인코딩 제거했습니다 감사합니다 👍 👍

2022-03-16 12:29 UTC, inwalter99 commented
@moonheekim0118 엇 한글로 검색하면 결과가 이상하지 않나용??????

2022-03-16 12:30 UTC, moonheekim0118 commented
@inwalter99 인코딩 제거하기 전에도 지금과 같이 잘 처리되었었어요...!! @.@......

2022-03-16 12:33 UTC, inwalter99 commented
@moonheekim0118 앗 그래요..? 검색 자체는 가능했으나 결과가 키워드와 다른 게 나왔는데.. 8ㅅ8

2022-03-16 12:36 UTC, inwalter99 commented
그럼 저의 문제였던걸로 .. <img src="https://media4.giphy.com/media/OPU6wzx8JrHna/giphy.gif"/>

2022-03-16 12:36 UTC, moonheekim0118 commented
@inwalter99 
아..월터님 말이 맞습니다 ㅠ_ㅠ 제가 지금 다시 인코딩 버전과 인코딩 안한 버전을 비교해봤더니
검색 결과가 다르네요...! 인코딩해서 검색 결과가 달라지는 검색어가 있고, 그렇지 않은 검색어가 있나봅니다...
짚어주셔서 감사합니다!!
저의 문제였습니다...........

= 결론적으로 한글 인코딩 안해야합니다!! ㅎㅎ 감사합니다

2022-03-16 12:45 UTC, inwalter99 approved these changes
수정해주신 부분 모두 좋습니다 👍 
동작상 버그가 하나 있는데 이 부분은 step2 에서 진행해도 좋을 것 같아요 :)
빠르게 코멘트 답장해주셔서 감샇바니다!!

2022-03-16 12:46 UTC, inwalter99 commented
동작상 버그는 스크롤을 ㅇ위아래로 빠르게했을 때 같은 API를 여러 번 호출하는 것 같아요, 이 부분 원인 파악해서 코드까지 개선되면 좋겠습니다!
<img width="775" alt="image" src="https://user-images.githubusercontent.com/28642472/158592907-ffae1c27-6c07-4885-8795-f251d009dafa.png">

2022-03-16 12:48 UTC, merged

2022-03-16 12:49 UTC, moonheekim0118 commented
감사합니다 : ) 
정말 수고많으셨습니다... 👍 👍 
알려주신 버그는 고쳐서 스텝투에서 뵙겠습니다 🙇 🙇

2022-03-16 12:51 UTC, inwalter99 commented
아 그리고 제가 놓친 부분이 있으면 스텝투에서 말씀부탁드리겠습니다! 9ㅅ9 화이팅!